// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module my_prj_decision_function_32 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_1_val,
        x_2_val,
        x_3_val,
        x_7_val,
        x_15_val,
        x_18_val,
        x_19_val,
        x_25_val,
        x_29_val,
        x_33_val,
        x_34_val,
        x_40_val,
        x_46_val,
        x_47_val,
        x_48_val,
        x_49_val,
        x_50_val,
        x_52_val,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] x_1_val;
input  [17:0] x_2_val;
input  [17:0] x_3_val;
input  [17:0] x_7_val;
input  [17:0] x_15_val;
input  [17:0] x_18_val;
input  [17:0] x_19_val;
input  [17:0] x_25_val;
input  [17:0] x_29_val;
input  [17:0] x_33_val;
input  [17:0] x_34_val;
input  [17:0] x_40_val;
input  [17:0] x_46_val;
input  [17:0] x_47_val;
input  [17:0] x_48_val;
input  [17:0] x_49_val;
input  [17:0] x_50_val;
input  [17:0] x_52_val;
output  [11:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln86_fu_384_p2;
reg   [0:0] icmp_ln86_reg_1460;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln86_848_fu_396_p2;
reg   [0:0] icmp_ln86_848_reg_1469;
wire   [0:0] icmp_ln86_851_fu_414_p2;
reg   [0:0] icmp_ln86_851_reg_1475;
wire   [0:0] icmp_ln86_852_fu_420_p2;
reg   [0:0] icmp_ln86_852_reg_1481;
wire   [0:0] icmp_ln86_857_fu_450_p2;
reg   [0:0] icmp_ln86_857_reg_1487;
wire   [0:0] icmp_ln86_858_fu_456_p2;
reg   [0:0] icmp_ln86_858_reg_1493;
wire   [0:0] icmp_ln86_1393_fu_472_p2;
reg   [0:0] icmp_ln86_1393_reg_1499;
wire   [0:0] icmp_ln86_860_fu_478_p2;
reg   [0:0] icmp_ln86_860_reg_1505;
wire   [0:0] icmp_ln86_869_fu_532_p2;
reg   [0:0] icmp_ln86_869_reg_1511;
wire   [0:0] icmp_ln86_870_fu_538_p2;
reg   [0:0] icmp_ln86_870_reg_1516;
wire   [0:0] icmp_ln86_871_fu_544_p2;
reg   [0:0] icmp_ln86_871_reg_1521;
wire   [0:0] icmp_ln86_872_fu_550_p2;
reg   [0:0] icmp_ln86_872_reg_1526;
wire   [0:0] icmp_ln86_873_fu_556_p2;
reg   [0:0] icmp_ln86_873_reg_1531;
wire   [0:0] icmp_ln86_874_fu_562_p2;
reg   [0:0] icmp_ln86_874_reg_1536;
wire   [0:0] icmp_ln86_875_fu_568_p2;
reg   [0:0] icmp_ln86_875_reg_1541;
wire   [0:0] icmp_ln86_876_fu_574_p2;
reg   [0:0] icmp_ln86_876_reg_1546;
wire   [4:0] select_ln117_834_fu_954_p3;
reg   [4:0] select_ln117_834_reg_1551;
wire    ap_block_pp0_stage0;
wire   [14:0] tmp_fu_462_p4;
wire   [0:0] icmp_ln86_847_fu_390_p2;
wire   [0:0] xor_ln104_406_fu_586_p2;
wire   [0:0] icmp_ln86_849_fu_402_p2;
wire   [0:0] and_ln102_fu_580_p2;
wire   [0:0] xor_ln104_408_fu_604_p2;
wire   [0:0] icmp_ln86_850_fu_408_p2;
wire   [0:0] and_ln104_fu_592_p2;
wire   [0:0] xor_ln104_409_fu_622_p2;
wire   [0:0] icmp_ln86_853_fu_426_p2;
wire   [0:0] and_ln102_815_fu_598_p2;
wire   [0:0] icmp_ln86_854_fu_432_p2;
wire   [0:0] and_ln104_167_fu_610_p2;
wire   [0:0] icmp_ln86_855_fu_438_p2;
wire   [0:0] and_ln102_816_fu_616_p2;
wire   [0:0] icmp_ln86_856_fu_444_p2;
wire   [0:0] and_ln104_168_fu_628_p2;
wire   [0:0] icmp_ln86_861_fu_484_p2;
wire   [0:0] and_ln102_819_fu_634_p2;
wire   [0:0] icmp_ln86_862_fu_490_p2;
wire   [0:0] xor_ln104_412_fu_640_p2;
wire   [0:0] and_ln102_843_fu_688_p2;
wire   [0:0] icmp_ln86_863_fu_496_p2;
wire   [0:0] and_ln102_820_fu_646_p2;
wire   [0:0] icmp_ln86_864_fu_502_p2;
wire   [0:0] xor_ln104_413_fu_652_p2;
wire   [0:0] and_ln102_844_fu_706_p2;
wire   [0:0] icmp_ln86_865_fu_508_p2;
wire   [0:0] and_ln102_821_fu_658_p2;
wire   [0:0] icmp_ln86_866_fu_514_p2;
wire   [0:0] xor_ln104_414_fu_664_p2;
wire   [0:0] and_ln102_845_fu_724_p2;
wire   [0:0] icmp_ln86_867_fu_520_p2;
wire   [0:0] and_ln102_822_fu_670_p2;
wire   [0:0] icmp_ln86_868_fu_526_p2;
wire   [0:0] xor_ln104_415_fu_676_p2;
wire   [0:0] and_ln102_846_fu_742_p2;
wire   [0:0] and_ln102_827_fu_682_p2;
wire   [0:0] xor_ln117_fu_754_p2;
wire   [0:0] and_ln102_828_fu_694_p2;
wire   [1:0] zext_ln117_fu_760_p1;
wire   [0:0] or_ln117_fu_764_p2;
wire   [1:0] select_ln117_fu_770_p3;
wire   [1:0] select_ln117_821_fu_778_p3;
wire   [0:0] and_ln102_829_fu_700_p2;
wire   [2:0] zext_ln117_93_fu_786_p1;
wire   [0:0] or_ln117_777_fu_790_p2;
wire   [2:0] select_ln117_822_fu_796_p3;
wire   [0:0] or_ln117_778_fu_804_p2;
wire   [0:0] and_ln102_830_fu_712_p2;
wire   [2:0] select_ln117_823_fu_810_p3;
wire   [0:0] or_ln117_779_fu_818_p2;
wire   [2:0] select_ln117_824_fu_824_p3;
wire   [2:0] select_ln117_825_fu_832_p3;
wire   [0:0] and_ln102_831_fu_718_p2;
wire   [3:0] zext_ln117_94_fu_840_p1;
wire   [0:0] or_ln117_780_fu_844_p2;
wire   [3:0] select_ln117_826_fu_850_p3;
wire   [0:0] or_ln117_781_fu_858_p2;
wire   [0:0] and_ln102_832_fu_730_p2;
wire   [3:0] select_ln117_827_fu_864_p3;
wire   [0:0] or_ln117_782_fu_872_p2;
wire   [3:0] select_ln117_828_fu_878_p3;
wire   [0:0] or_ln117_783_fu_886_p2;
wire   [0:0] and_ln102_833_fu_736_p2;
wire   [3:0] select_ln117_829_fu_892_p3;
wire   [0:0] or_ln117_784_fu_900_p2;
wire   [3:0] select_ln117_830_fu_906_p3;
wire   [0:0] or_ln117_785_fu_914_p2;
wire   [0:0] and_ln102_834_fu_748_p2;
wire   [3:0] select_ln117_831_fu_920_p3;
wire   [0:0] or_ln117_786_fu_928_p2;
wire   [3:0] select_ln117_832_fu_934_p3;
wire   [3:0] select_ln117_833_fu_942_p3;
wire   [4:0] zext_ln117_95_fu_950_p1;
wire   [0:0] xor_ln104_fu_962_p2;
wire   [0:0] xor_ln104_407_fu_972_p2;
wire   [0:0] and_ln102_814_fu_967_p2;
wire   [0:0] xor_ln104_410_fu_988_p2;
wire   [0:0] and_ln104_166_fu_977_p2;
wire   [0:0] xor_ln104_411_fu_1004_p2;
wire   [0:0] and_ln102_817_fu_983_p2;
wire   [0:0] and_ln104_169_fu_993_p2;
wire   [0:0] and_ln102_818_fu_999_p2;
wire   [0:0] and_ln104_170_fu_1009_p2;
wire   [0:0] and_ln102_823_fu_1015_p2;
wire   [0:0] xor_ln104_416_fu_1020_p2;
wire   [0:0] and_ln102_847_fu_1060_p2;
wire   [0:0] and_ln102_824_fu_1025_p2;
wire   [0:0] xor_ln104_417_fu_1030_p2;
wire   [0:0] and_ln102_848_fu_1076_p2;
wire   [0:0] and_ln102_825_fu_1035_p2;
wire   [0:0] xor_ln104_418_fu_1040_p2;
wire   [0:0] and_ln102_849_fu_1092_p2;
wire   [0:0] and_ln102_826_fu_1045_p2;
wire   [0:0] xor_ln104_419_fu_1050_p2;
wire   [0:0] and_ln102_850_fu_1108_p2;
wire   [0:0] and_ln102_835_fu_1055_p2;
wire   [0:0] or_ln117_787_fu_1119_p2;
wire   [0:0] or_ln117_788_fu_1124_p2;
wire   [0:0] and_ln102_836_fu_1065_p2;
wire   [4:0] select_ln117_835_fu_1129_p3;
wire   [0:0] or_ln117_789_fu_1136_p2;
wire   [4:0] select_ln117_836_fu_1142_p3;
wire   [0:0] or_ln117_790_fu_1150_p2;
wire   [0:0] and_ln102_837_fu_1071_p2;
wire   [4:0] select_ln117_837_fu_1155_p3;
wire   [0:0] or_ln117_791_fu_1163_p2;
wire   [4:0] select_ln117_838_fu_1169_p3;
wire   [0:0] or_ln117_792_fu_1177_p2;
wire   [0:0] and_ln102_838_fu_1081_p2;
wire   [4:0] select_ln117_839_fu_1183_p3;
wire   [0:0] or_ln117_793_fu_1191_p2;
wire   [4:0] select_ln117_840_fu_1197_p3;
wire   [0:0] or_ln117_794_fu_1205_p2;
wire   [0:0] and_ln102_839_fu_1087_p2;
wire   [4:0] select_ln117_841_fu_1210_p3;
wire   [0:0] or_ln117_795_fu_1218_p2;
wire   [4:0] select_ln117_842_fu_1224_p3;
wire   [0:0] or_ln117_796_fu_1232_p2;
wire   [0:0] and_ln102_840_fu_1097_p2;
wire   [4:0] select_ln117_843_fu_1238_p3;
wire   [0:0] or_ln117_797_fu_1246_p2;
wire   [4:0] select_ln117_844_fu_1252_p3;
wire   [0:0] or_ln117_798_fu_1260_p2;
wire   [0:0] and_ln102_841_fu_1103_p2;
wire   [4:0] select_ln117_845_fu_1266_p3;
wire   [0:0] or_ln117_799_fu_1274_p2;
wire   [4:0] select_ln117_846_fu_1280_p3;
wire   [0:0] or_ln117_800_fu_1288_p2;
wire   [0:0] and_ln102_842_fu_1113_p2;
wire   [4:0] select_ln117_847_fu_1294_p3;
wire   [0:0] or_ln117_801_fu_1302_p2;
wire   [4:0] select_ln117_848_fu_1308_p3;
wire   [11:0] agg_result_fu_1324_p65;
wire   [4:0] agg_result_fu_1324_p66;
wire   [11:0] agg_result_fu_1324_p67;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [4:0] agg_result_fu_1324_p1;
wire   [4:0] agg_result_fu_1324_p3;
wire   [4:0] agg_result_fu_1324_p5;
wire   [4:0] agg_result_fu_1324_p7;
wire   [4:0] agg_result_fu_1324_p9;
wire   [4:0] agg_result_fu_1324_p11;
wire   [4:0] agg_result_fu_1324_p13;
wire   [4:0] agg_result_fu_1324_p15;
wire   [4:0] agg_result_fu_1324_p17;
wire   [4:0] agg_result_fu_1324_p19;
wire   [4:0] agg_result_fu_1324_p21;
wire   [4:0] agg_result_fu_1324_p23;
wire   [4:0] agg_result_fu_1324_p25;
wire   [4:0] agg_result_fu_1324_p27;
wire   [4:0] agg_result_fu_1324_p29;
wire   [4:0] agg_result_fu_1324_p31;
wire  signed [4:0] agg_result_fu_1324_p33;
wire  signed [4:0] agg_result_fu_1324_p35;
wire  signed [4:0] agg_result_fu_1324_p37;
wire  signed [4:0] agg_result_fu_1324_p39;
wire  signed [4:0] agg_result_fu_1324_p41;
wire  signed [4:0] agg_result_fu_1324_p43;
wire  signed [4:0] agg_result_fu_1324_p45;
wire  signed [4:0] agg_result_fu_1324_p47;
wire  signed [4:0] agg_result_fu_1324_p49;
wire  signed [4:0] agg_result_fu_1324_p51;
wire  signed [4:0] agg_result_fu_1324_p53;
wire  signed [4:0] agg_result_fu_1324_p55;
wire  signed [4:0] agg_result_fu_1324_p57;
wire  signed [4:0] agg_result_fu_1324_p59;
wire  signed [4:0] agg_result_fu_1324_p61;
wire  signed [4:0] agg_result_fu_1324_p63;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

(* dissolve_hierarchy = "yes" *) my_prj_sparsemux_65_5_12_1_1_x0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 12 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 12 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 12 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 12 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 12 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 12 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 12 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 12 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 12 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 12 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 12 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 12 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 12 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 12 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 12 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 12 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 12 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 12 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 12 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 12 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 12 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 12 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 12 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 12 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 12 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 12 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 12 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 12 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
sparsemux_65_5_12_1_1_x0_U119(
    .din0(12'd323),
    .din1(12'd3811),
    .din2(12'd92),
    .din3(12'd541),
    .din4(12'd424),
    .din5(12'd3676),
    .din6(12'd4082),
    .din7(12'd3343),
    .din8(12'd3630),
    .din9(12'd3507),
    .din10(12'd3947),
    .din11(12'd3682),
    .din12(12'd173),
    .din13(12'd3828),
    .din14(12'd3964),
    .din15(12'd3698),
    .din16(12'd1091),
    .din17(12'd3724),
    .din18(12'd3657),
    .din19(12'd122),
    .din20(12'd240),
    .din21(12'd3592),
    .din22(12'd4002),
    .din23(12'd3687),
    .din24(12'd816),
    .din25(12'd3640),
    .din26(12'd3819),
    .din27(12'd3555),
    .din28(12'd6),
    .din29(12'd3671),
    .din30(12'd3635),
    .din31(12'd3573),
    .def(agg_result_fu_1324_p65),
    .sel(agg_result_fu_1324_p66),
    .dout(agg_result_fu_1324_p67)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln86_1393_reg_1499 <= icmp_ln86_1393_fu_472_p2;
        icmp_ln86_848_reg_1469 <= icmp_ln86_848_fu_396_p2;
        icmp_ln86_851_reg_1475 <= icmp_ln86_851_fu_414_p2;
        icmp_ln86_852_reg_1481 <= icmp_ln86_852_fu_420_p2;
        icmp_ln86_857_reg_1487 <= icmp_ln86_857_fu_450_p2;
        icmp_ln86_858_reg_1493 <= icmp_ln86_858_fu_456_p2;
        icmp_ln86_860_reg_1505 <= icmp_ln86_860_fu_478_p2;
        icmp_ln86_869_reg_1511 <= icmp_ln86_869_fu_532_p2;
        icmp_ln86_870_reg_1516 <= icmp_ln86_870_fu_538_p2;
        icmp_ln86_871_reg_1521 <= icmp_ln86_871_fu_544_p2;
        icmp_ln86_872_reg_1526 <= icmp_ln86_872_fu_550_p2;
        icmp_ln86_873_reg_1531 <= icmp_ln86_873_fu_556_p2;
        icmp_ln86_874_reg_1536 <= icmp_ln86_874_fu_562_p2;
        icmp_ln86_875_reg_1541 <= icmp_ln86_875_fu_568_p2;
        icmp_ln86_876_reg_1546 <= icmp_ln86_876_fu_574_p2;
        icmp_ln86_reg_1460 <= icmp_ln86_fu_384_p2;
        select_ln117_834_reg_1551 <= select_ln117_834_fu_954_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign agg_result_fu_1324_p65 = 'bx;

assign agg_result_fu_1324_p66 = ((or_ln117_801_fu_1302_p2[0:0] == 1'b1) ? select_ln117_848_fu_1308_p3 : 5'd31);

assign and_ln102_814_fu_967_p2 = (xor_ln104_fu_962_p2 & icmp_ln86_848_reg_1469);

assign and_ln102_815_fu_598_p2 = (icmp_ln86_849_fu_402_p2 & and_ln102_fu_580_p2);

assign and_ln102_816_fu_616_p2 = (icmp_ln86_850_fu_408_p2 & and_ln104_fu_592_p2);

assign and_ln102_817_fu_983_p2 = (icmp_ln86_851_reg_1475 & and_ln102_814_fu_967_p2);

assign and_ln102_818_fu_999_p2 = (icmp_ln86_852_reg_1481 & and_ln104_166_fu_977_p2);

assign and_ln102_819_fu_634_p2 = (icmp_ln86_853_fu_426_p2 & and_ln102_815_fu_598_p2);

assign and_ln102_820_fu_646_p2 = (icmp_ln86_854_fu_432_p2 & and_ln104_167_fu_610_p2);

assign and_ln102_821_fu_658_p2 = (icmp_ln86_855_fu_438_p2 & and_ln102_816_fu_616_p2);

assign and_ln102_822_fu_670_p2 = (icmp_ln86_856_fu_444_p2 & and_ln104_168_fu_628_p2);

assign and_ln102_823_fu_1015_p2 = (icmp_ln86_857_reg_1487 & and_ln102_817_fu_983_p2);

assign and_ln102_824_fu_1025_p2 = (icmp_ln86_858_reg_1493 & and_ln104_169_fu_993_p2);

assign and_ln102_825_fu_1035_p2 = (icmp_ln86_1393_reg_1499 & and_ln102_818_fu_999_p2);

assign and_ln102_826_fu_1045_p2 = (icmp_ln86_860_reg_1505 & and_ln104_170_fu_1009_p2);

assign and_ln102_827_fu_682_p2 = (icmp_ln86_861_fu_484_p2 & and_ln102_819_fu_634_p2);

assign and_ln102_828_fu_694_p2 = (and_ln102_843_fu_688_p2 & and_ln102_815_fu_598_p2);

assign and_ln102_829_fu_700_p2 = (icmp_ln86_863_fu_496_p2 & and_ln102_820_fu_646_p2);

assign and_ln102_830_fu_712_p2 = (and_ln104_167_fu_610_p2 & and_ln102_844_fu_706_p2);

assign and_ln102_831_fu_718_p2 = (icmp_ln86_865_fu_508_p2 & and_ln102_821_fu_658_p2);

assign and_ln102_832_fu_730_p2 = (and_ln102_845_fu_724_p2 & and_ln102_816_fu_616_p2);

assign and_ln102_833_fu_736_p2 = (icmp_ln86_867_fu_520_p2 & and_ln102_822_fu_670_p2);

assign and_ln102_834_fu_748_p2 = (and_ln104_168_fu_628_p2 & and_ln102_846_fu_742_p2);

assign and_ln102_835_fu_1055_p2 = (icmp_ln86_869_reg_1511 & and_ln102_823_fu_1015_p2);

assign and_ln102_836_fu_1065_p2 = (and_ln102_847_fu_1060_p2 & and_ln102_817_fu_983_p2);

assign and_ln102_837_fu_1071_p2 = (icmp_ln86_871_reg_1521 & and_ln102_824_fu_1025_p2);

assign and_ln102_838_fu_1081_p2 = (and_ln104_169_fu_993_p2 & and_ln102_848_fu_1076_p2);

assign and_ln102_839_fu_1087_p2 = (icmp_ln86_873_reg_1531 & and_ln102_825_fu_1035_p2);

assign and_ln102_840_fu_1097_p2 = (and_ln102_849_fu_1092_p2 & and_ln102_818_fu_999_p2);

assign and_ln102_841_fu_1103_p2 = (icmp_ln86_875_reg_1541 & and_ln102_826_fu_1045_p2);

assign and_ln102_842_fu_1113_p2 = (and_ln104_170_fu_1009_p2 & and_ln102_850_fu_1108_p2);

assign and_ln102_843_fu_688_p2 = (xor_ln104_412_fu_640_p2 & icmp_ln86_862_fu_490_p2);

assign and_ln102_844_fu_706_p2 = (xor_ln104_413_fu_652_p2 & icmp_ln86_864_fu_502_p2);

assign and_ln102_845_fu_724_p2 = (xor_ln104_414_fu_664_p2 & icmp_ln86_866_fu_514_p2);

assign and_ln102_846_fu_742_p2 = (xor_ln104_415_fu_676_p2 & icmp_ln86_868_fu_526_p2);

assign and_ln102_847_fu_1060_p2 = (xor_ln104_416_fu_1020_p2 & icmp_ln86_870_reg_1516);

assign and_ln102_848_fu_1076_p2 = (xor_ln104_417_fu_1030_p2 & icmp_ln86_872_reg_1526);

assign and_ln102_849_fu_1092_p2 = (xor_ln104_418_fu_1040_p2 & icmp_ln86_874_reg_1536);

assign and_ln102_850_fu_1108_p2 = (xor_ln104_419_fu_1050_p2 & icmp_ln86_876_reg_1546);

assign and_ln102_fu_580_p2 = (icmp_ln86_fu_384_p2 & icmp_ln86_847_fu_390_p2);

assign and_ln104_166_fu_977_p2 = (xor_ln104_fu_962_p2 & xor_ln104_407_fu_972_p2);

assign and_ln104_167_fu_610_p2 = (xor_ln104_408_fu_604_p2 & and_ln102_fu_580_p2);

assign and_ln104_168_fu_628_p2 = (xor_ln104_409_fu_622_p2 & and_ln104_fu_592_p2);

assign and_ln104_169_fu_993_p2 = (xor_ln104_410_fu_988_p2 & and_ln102_814_fu_967_p2);

assign and_ln104_170_fu_1009_p2 = (xor_ln104_411_fu_1004_p2 & and_ln104_166_fu_977_p2);

assign and_ln104_fu_592_p2 = (xor_ln104_406_fu_586_p2 & icmp_ln86_fu_384_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return = agg_result_fu_1324_p67;

assign icmp_ln86_1393_fu_472_p2 = (($signed(tmp_fu_462_p4) < $signed(15'd1)) ? 1'b1 : 1'b0);

assign icmp_ln86_847_fu_390_p2 = (($signed(x_19_val) < $signed(18'd1892)) ? 1'b1 : 1'b0);

assign icmp_ln86_848_fu_396_p2 = (($signed(x_29_val) < $signed(18'd7585)) ? 1'b1 : 1'b0);

assign icmp_ln86_849_fu_402_p2 = (($signed(x_7_val) < $signed(18'd6759)) ? 1'b1 : 1'b0);

assign icmp_ln86_850_fu_408_p2 = (($signed(x_1_val) < $signed(18'd222325)) ? 1'b1 : 1'b0);

assign icmp_ln86_851_fu_414_p2 = (($signed(x_46_val) < $signed(18'd81)) ? 1'b1 : 1'b0);

assign icmp_ln86_852_fu_420_p2 = (($signed(x_1_val) < $signed(18'd16589)) ? 1'b1 : 1'b0);

assign icmp_ln86_853_fu_426_p2 = (($signed(x_48_val) < $signed(18'd78494)) ? 1'b1 : 1'b0);

assign icmp_ln86_854_fu_432_p2 = (($signed(x_40_val) < $signed(18'd495)) ? 1'b1 : 1'b0);

assign icmp_ln86_855_fu_438_p2 = (($signed(x_1_val) < $signed(18'd189279)) ? 1'b1 : 1'b0);

assign icmp_ln86_856_fu_444_p2 = (($signed(x_25_val) < $signed(18'd310)) ? 1'b1 : 1'b0);

assign icmp_ln86_857_fu_450_p2 = (($signed(x_1_val) < $signed(18'd243545)) ? 1'b1 : 1'b0);

assign icmp_ln86_858_fu_456_p2 = (($signed(x_48_val) < $signed(18'd76680)) ? 1'b1 : 1'b0);

assign icmp_ln86_860_fu_478_p2 = (($signed(x_33_val) < $signed(18'd197)) ? 1'b1 : 1'b0);

assign icmp_ln86_861_fu_484_p2 = (($signed(x_18_val) < $signed(18'd3679)) ? 1'b1 : 1'b0);

assign icmp_ln86_862_fu_490_p2 = (($signed(x_1_val) < $signed(18'd219109)) ? 1'b1 : 1'b0);

assign icmp_ln86_863_fu_496_p2 = (($signed(x_1_val) < $signed(18'd92864)) ? 1'b1 : 1'b0);

assign icmp_ln86_864_fu_502_p2 = (($signed(x_18_val) < $signed(18'd3093)) ? 1'b1 : 1'b0);

assign icmp_ln86_865_fu_508_p2 = (($signed(x_52_val) < $signed(18'd40449)) ? 1'b1 : 1'b0);

assign icmp_ln86_866_fu_514_p2 = (($signed(x_52_val) < $signed(18'd42497)) ? 1'b1 : 1'b0);

assign icmp_ln86_867_fu_520_p2 = (($signed(x_50_val) < $signed(18'd84520)) ? 1'b1 : 1'b0);

assign icmp_ln86_868_fu_526_p2 = (($signed(x_1_val) < $signed(18'd21009)) ? 1'b1 : 1'b0);

assign icmp_ln86_869_fu_532_p2 = (($signed(x_2_val) < $signed(18'd260414)) ? 1'b1 : 1'b0);

assign icmp_ln86_870_fu_538_p2 = (($signed(x_29_val) < $signed(18'd5643)) ? 1'b1 : 1'b0);

assign icmp_ln86_871_fu_544_p2 = (($signed(x_49_val) < $signed(18'd6128)) ? 1'b1 : 1'b0);

assign icmp_ln86_872_fu_550_p2 = (($signed(x_47_val) < $signed(18'd85036)) ? 1'b1 : 1'b0);

assign icmp_ln86_873_fu_556_p2 = (($signed(x_47_val) < $signed(18'd90758)) ? 1'b1 : 1'b0);

assign icmp_ln86_874_fu_562_p2 = (($signed(x_3_val) < $signed(18'd83817)) ? 1'b1 : 1'b0);

assign icmp_ln86_875_fu_568_p2 = (($signed(x_50_val) < $signed(18'd160331)) ? 1'b1 : 1'b0);

assign icmp_ln86_876_fu_574_p2 = (($signed(x_34_val) < $signed(18'd451)) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_384_p2 = (($signed(x_7_val) < $signed(18'd7436)) ? 1'b1 : 1'b0);

assign or_ln117_777_fu_790_p2 = (and_ln102_829_fu_700_p2 | and_ln102_815_fu_598_p2);

assign or_ln117_778_fu_804_p2 = (and_ln102_820_fu_646_p2 | and_ln102_815_fu_598_p2);

assign or_ln117_779_fu_818_p2 = (or_ln117_778_fu_804_p2 | and_ln102_830_fu_712_p2);

assign or_ln117_780_fu_844_p2 = (and_ln102_fu_580_p2 | and_ln102_831_fu_718_p2);

assign or_ln117_781_fu_858_p2 = (and_ln102_fu_580_p2 | and_ln102_821_fu_658_p2);

assign or_ln117_782_fu_872_p2 = (or_ln117_781_fu_858_p2 | and_ln102_832_fu_730_p2);

assign or_ln117_783_fu_886_p2 = (and_ln102_fu_580_p2 | and_ln102_816_fu_616_p2);

assign or_ln117_784_fu_900_p2 = (or_ln117_783_fu_886_p2 | and_ln102_833_fu_736_p2);

assign or_ln117_785_fu_914_p2 = (or_ln117_783_fu_886_p2 | and_ln102_822_fu_670_p2);

assign or_ln117_786_fu_928_p2 = (or_ln117_785_fu_914_p2 | and_ln102_834_fu_748_p2);

assign or_ln117_787_fu_1119_p2 = (icmp_ln86_reg_1460 | and_ln102_835_fu_1055_p2);

assign or_ln117_788_fu_1124_p2 = (icmp_ln86_reg_1460 | and_ln102_823_fu_1015_p2);

assign or_ln117_789_fu_1136_p2 = (or_ln117_788_fu_1124_p2 | and_ln102_836_fu_1065_p2);

assign or_ln117_790_fu_1150_p2 = (icmp_ln86_reg_1460 | and_ln102_817_fu_983_p2);

assign or_ln117_791_fu_1163_p2 = (or_ln117_790_fu_1150_p2 | and_ln102_837_fu_1071_p2);

assign or_ln117_792_fu_1177_p2 = (or_ln117_790_fu_1150_p2 | and_ln102_824_fu_1025_p2);

assign or_ln117_793_fu_1191_p2 = (or_ln117_792_fu_1177_p2 | and_ln102_838_fu_1081_p2);

assign or_ln117_794_fu_1205_p2 = (icmp_ln86_reg_1460 | and_ln102_814_fu_967_p2);

assign or_ln117_795_fu_1218_p2 = (or_ln117_794_fu_1205_p2 | and_ln102_839_fu_1087_p2);

assign or_ln117_796_fu_1232_p2 = (or_ln117_794_fu_1205_p2 | and_ln102_825_fu_1035_p2);

assign or_ln117_797_fu_1246_p2 = (or_ln117_796_fu_1232_p2 | and_ln102_840_fu_1097_p2);

assign or_ln117_798_fu_1260_p2 = (or_ln117_794_fu_1205_p2 | and_ln102_818_fu_999_p2);

assign or_ln117_799_fu_1274_p2 = (or_ln117_798_fu_1260_p2 | and_ln102_841_fu_1103_p2);

assign or_ln117_800_fu_1288_p2 = (or_ln117_798_fu_1260_p2 | and_ln102_826_fu_1045_p2);

assign or_ln117_801_fu_1302_p2 = (or_ln117_800_fu_1288_p2 | and_ln102_842_fu_1113_p2);

assign or_ln117_fu_764_p2 = (and_ln102_828_fu_694_p2 | and_ln102_819_fu_634_p2);

assign select_ln117_821_fu_778_p3 = ((or_ln117_fu_764_p2[0:0] == 1'b1) ? select_ln117_fu_770_p3 : 2'd3);

assign select_ln117_822_fu_796_p3 = ((and_ln102_815_fu_598_p2[0:0] == 1'b1) ? zext_ln117_93_fu_786_p1 : 3'd4);

assign select_ln117_823_fu_810_p3 = ((or_ln117_777_fu_790_p2[0:0] == 1'b1) ? select_ln117_822_fu_796_p3 : 3'd5);

assign select_ln117_824_fu_824_p3 = ((or_ln117_778_fu_804_p2[0:0] == 1'b1) ? select_ln117_823_fu_810_p3 : 3'd6);

assign select_ln117_825_fu_832_p3 = ((or_ln117_779_fu_818_p2[0:0] == 1'b1) ? select_ln117_824_fu_824_p3 : 3'd7);

assign select_ln117_826_fu_850_p3 = ((and_ln102_fu_580_p2[0:0] == 1'b1) ? zext_ln117_94_fu_840_p1 : 4'd8);

assign select_ln117_827_fu_864_p3 = ((or_ln117_780_fu_844_p2[0:0] == 1'b1) ? select_ln117_826_fu_850_p3 : 4'd9);

assign select_ln117_828_fu_878_p3 = ((or_ln117_781_fu_858_p2[0:0] == 1'b1) ? select_ln117_827_fu_864_p3 : 4'd10);

assign select_ln117_829_fu_892_p3 = ((or_ln117_782_fu_872_p2[0:0] == 1'b1) ? select_ln117_828_fu_878_p3 : 4'd11);

assign select_ln117_830_fu_906_p3 = ((or_ln117_783_fu_886_p2[0:0] == 1'b1) ? select_ln117_829_fu_892_p3 : 4'd12);

assign select_ln117_831_fu_920_p3 = ((or_ln117_784_fu_900_p2[0:0] == 1'b1) ? select_ln117_830_fu_906_p3 : 4'd13);

assign select_ln117_832_fu_934_p3 = ((or_ln117_785_fu_914_p2[0:0] == 1'b1) ? select_ln117_831_fu_920_p3 : 4'd14);

assign select_ln117_833_fu_942_p3 = ((or_ln117_786_fu_928_p2[0:0] == 1'b1) ? select_ln117_832_fu_934_p3 : 4'd15);

assign select_ln117_834_fu_954_p3 = ((icmp_ln86_fu_384_p2[0:0] == 1'b1) ? zext_ln117_95_fu_950_p1 : 5'd16);

assign select_ln117_835_fu_1129_p3 = ((or_ln117_787_fu_1119_p2[0:0] == 1'b1) ? select_ln117_834_reg_1551 : 5'd17);

assign select_ln117_836_fu_1142_p3 = ((or_ln117_788_fu_1124_p2[0:0] == 1'b1) ? select_ln117_835_fu_1129_p3 : 5'd18);

assign select_ln117_837_fu_1155_p3 = ((or_ln117_789_fu_1136_p2[0:0] == 1'b1) ? select_ln117_836_fu_1142_p3 : 5'd19);

assign select_ln117_838_fu_1169_p3 = ((or_ln117_790_fu_1150_p2[0:0] == 1'b1) ? select_ln117_837_fu_1155_p3 : 5'd20);

assign select_ln117_839_fu_1183_p3 = ((or_ln117_791_fu_1163_p2[0:0] == 1'b1) ? select_ln117_838_fu_1169_p3 : 5'd21);

assign select_ln117_840_fu_1197_p3 = ((or_ln117_792_fu_1177_p2[0:0] == 1'b1) ? select_ln117_839_fu_1183_p3 : 5'd22);

assign select_ln117_841_fu_1210_p3 = ((or_ln117_793_fu_1191_p2[0:0] == 1'b1) ? select_ln117_840_fu_1197_p3 : 5'd23);

assign select_ln117_842_fu_1224_p3 = ((or_ln117_794_fu_1205_p2[0:0] == 1'b1) ? select_ln117_841_fu_1210_p3 : 5'd24);

assign select_ln117_843_fu_1238_p3 = ((or_ln117_795_fu_1218_p2[0:0] == 1'b1) ? select_ln117_842_fu_1224_p3 : 5'd25);

assign select_ln117_844_fu_1252_p3 = ((or_ln117_796_fu_1232_p2[0:0] == 1'b1) ? select_ln117_843_fu_1238_p3 : 5'd26);

assign select_ln117_845_fu_1266_p3 = ((or_ln117_797_fu_1246_p2[0:0] == 1'b1) ? select_ln117_844_fu_1252_p3 : 5'd27);

assign select_ln117_846_fu_1280_p3 = ((or_ln117_798_fu_1260_p2[0:0] == 1'b1) ? select_ln117_845_fu_1266_p3 : 5'd28);

assign select_ln117_847_fu_1294_p3 = ((or_ln117_799_fu_1274_p2[0:0] == 1'b1) ? select_ln117_846_fu_1280_p3 : 5'd29);

assign select_ln117_848_fu_1308_p3 = ((or_ln117_800_fu_1288_p2[0:0] == 1'b1) ? select_ln117_847_fu_1294_p3 : 5'd30);

assign select_ln117_fu_770_p3 = ((and_ln102_819_fu_634_p2[0:0] == 1'b1) ? zext_ln117_fu_760_p1 : 2'd2);

assign tmp_fu_462_p4 = {{x_15_val[17:3]}};

assign xor_ln104_406_fu_586_p2 = (icmp_ln86_847_fu_390_p2 ^ 1'd1);

assign xor_ln104_407_fu_972_p2 = (icmp_ln86_848_reg_1469 ^ 1'd1);

assign xor_ln104_408_fu_604_p2 = (icmp_ln86_849_fu_402_p2 ^ 1'd1);

assign xor_ln104_409_fu_622_p2 = (icmp_ln86_850_fu_408_p2 ^ 1'd1);

assign xor_ln104_410_fu_988_p2 = (icmp_ln86_851_reg_1475 ^ 1'd1);

assign xor_ln104_411_fu_1004_p2 = (icmp_ln86_852_reg_1481 ^ 1'd1);

assign xor_ln104_412_fu_640_p2 = (icmp_ln86_853_fu_426_p2 ^ 1'd1);

assign xor_ln104_413_fu_652_p2 = (icmp_ln86_854_fu_432_p2 ^ 1'd1);

assign xor_ln104_414_fu_664_p2 = (icmp_ln86_855_fu_438_p2 ^ 1'd1);

assign xor_ln104_415_fu_676_p2 = (icmp_ln86_856_fu_444_p2 ^ 1'd1);

assign xor_ln104_416_fu_1020_p2 = (icmp_ln86_857_reg_1487 ^ 1'd1);

assign xor_ln104_417_fu_1030_p2 = (icmp_ln86_858_reg_1493 ^ 1'd1);

assign xor_ln104_418_fu_1040_p2 = (icmp_ln86_1393_reg_1499 ^ 1'd1);

assign xor_ln104_419_fu_1050_p2 = (icmp_ln86_860_reg_1505 ^ 1'd1);

assign xor_ln104_fu_962_p2 = (icmp_ln86_reg_1460 ^ 1'd1);

assign xor_ln117_fu_754_p2 = (1'd1 ^ and_ln102_827_fu_682_p2);

assign zext_ln117_93_fu_786_p1 = select_ln117_821_fu_778_p3;

assign zext_ln117_94_fu_840_p1 = select_ln117_825_fu_832_p3;

assign zext_ln117_95_fu_950_p1 = select_ln117_833_fu_942_p3;

assign zext_ln117_fu_760_p1 = xor_ln117_fu_754_p2;

endmodule //my_prj_decision_function_32
