// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conifer_jettag_accelerator_decision_function_73 (
        ap_clk,
        ap_rst,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] p_read1;
input  [17:0] p_read2;
input  [17:0] p_read3;
input  [17:0] p_read4;
input  [17:0] p_read5;
input  [17:0] p_read6;
input  [17:0] p_read7;
input  [17:0] p_read8;
input  [17:0] p_read9;
input  [17:0] p_read10;
input  [17:0] p_read11;
input  [17:0] p_read12;
input  [17:0] p_read13;
input  [17:0] p_read14;
input  [17:0] p_read15;
input  [17:0] p_read16;
input  [17:0] p_read17;
input  [17:0] p_read18;
input  [17:0] p_read19;
input  [17:0] p_read20;
input  [17:0] p_read21;
output  [11:0] ap_return;
input   ap_ce;

wire   [0:0] icmp_ln86_fu_408_p2;
reg   [0:0] icmp_ln86_reg_1406;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln86_reg_1406_pp0_iter1_reg;
reg   [0:0] icmp_ln86_reg_1406_pp0_iter2_reg;
reg   [0:0] icmp_ln86_reg_1406_pp0_iter3_reg;
wire   [0:0] icmp_ln86_744_fu_414_p2;
reg   [0:0] icmp_ln86_744_reg_1417;
wire   [0:0] icmp_ln86_745_fu_420_p2;
reg   [0:0] icmp_ln86_745_reg_1422;
reg   [0:0] icmp_ln86_745_reg_1422_pp0_iter1_reg;
reg   [0:0] icmp_ln86_745_reg_1422_pp0_iter2_reg;
wire   [0:0] icmp_ln86_746_fu_426_p2;
reg   [0:0] icmp_ln86_746_reg_1428;
wire   [0:0] icmp_ln86_747_fu_432_p2;
reg   [0:0] icmp_ln86_747_reg_1434;
reg   [0:0] icmp_ln86_747_reg_1434_pp0_iter1_reg;
wire   [0:0] icmp_ln86_748_fu_438_p2;
reg   [0:0] icmp_ln86_748_reg_1440;
reg   [0:0] icmp_ln86_748_reg_1440_pp0_iter1_reg;
reg   [0:0] icmp_ln86_748_reg_1440_pp0_iter2_reg;
reg   [0:0] icmp_ln86_748_reg_1440_pp0_iter3_reg;
wire   [0:0] icmp_ln86_749_fu_444_p2;
reg   [0:0] icmp_ln86_749_reg_1446;
reg   [0:0] icmp_ln86_749_reg_1446_pp0_iter1_reg;
reg   [0:0] icmp_ln86_749_reg_1446_pp0_iter2_reg;
reg   [0:0] icmp_ln86_749_reg_1446_pp0_iter3_reg;
wire   [0:0] icmp_ln86_750_fu_450_p2;
reg   [0:0] icmp_ln86_750_reg_1452;
wire   [0:0] icmp_ln86_751_fu_456_p2;
reg   [0:0] icmp_ln86_751_reg_1458;
reg   [0:0] icmp_ln86_751_reg_1458_pp0_iter1_reg;
wire   [0:0] icmp_ln86_752_fu_462_p2;
reg   [0:0] icmp_ln86_752_reg_1464;
reg   [0:0] icmp_ln86_752_reg_1464_pp0_iter1_reg;
reg   [0:0] icmp_ln86_752_reg_1464_pp0_iter2_reg;
wire   [0:0] icmp_ln86_753_fu_468_p2;
reg   [0:0] icmp_ln86_753_reg_1470;
reg   [0:0] icmp_ln86_753_reg_1470_pp0_iter1_reg;
reg   [0:0] icmp_ln86_753_reg_1470_pp0_iter2_reg;
reg   [0:0] icmp_ln86_753_reg_1470_pp0_iter3_reg;
wire   [0:0] icmp_ln86_754_fu_474_p2;
reg   [0:0] icmp_ln86_754_reg_1476;
reg   [0:0] icmp_ln86_754_reg_1476_pp0_iter1_reg;
reg   [0:0] icmp_ln86_754_reg_1476_pp0_iter2_reg;
reg   [0:0] icmp_ln86_754_reg_1476_pp0_iter3_reg;
wire   [0:0] icmp_ln86_755_fu_480_p2;
reg   [0:0] icmp_ln86_755_reg_1482;
reg   [0:0] icmp_ln86_755_reg_1482_pp0_iter1_reg;
reg   [0:0] icmp_ln86_755_reg_1482_pp0_iter2_reg;
reg   [0:0] icmp_ln86_755_reg_1482_pp0_iter3_reg;
reg   [0:0] icmp_ln86_755_reg_1482_pp0_iter4_reg;
wire   [0:0] icmp_ln86_756_fu_486_p2;
reg   [0:0] icmp_ln86_756_reg_1488;
reg   [0:0] icmp_ln86_756_reg_1488_pp0_iter1_reg;
reg   [0:0] icmp_ln86_756_reg_1488_pp0_iter2_reg;
reg   [0:0] icmp_ln86_756_reg_1488_pp0_iter3_reg;
reg   [0:0] icmp_ln86_756_reg_1488_pp0_iter4_reg;
reg   [0:0] icmp_ln86_756_reg_1488_pp0_iter5_reg;
wire   [0:0] icmp_ln86_757_fu_492_p2;
reg   [0:0] icmp_ln86_757_reg_1494;
reg   [0:0] icmp_ln86_757_reg_1494_pp0_iter1_reg;
reg   [0:0] icmp_ln86_757_reg_1494_pp0_iter2_reg;
reg   [0:0] icmp_ln86_757_reg_1494_pp0_iter3_reg;
reg   [0:0] icmp_ln86_757_reg_1494_pp0_iter4_reg;
reg   [0:0] icmp_ln86_757_reg_1494_pp0_iter5_reg;
reg   [0:0] icmp_ln86_757_reg_1494_pp0_iter6_reg;
wire   [0:0] icmp_ln86_758_fu_498_p2;
reg   [0:0] icmp_ln86_758_reg_1500;
reg   [0:0] icmp_ln86_758_reg_1500_pp0_iter1_reg;
wire   [0:0] icmp_ln86_759_fu_514_p2;
reg   [0:0] icmp_ln86_759_reg_1505;
wire   [0:0] icmp_ln86_760_fu_520_p2;
reg   [0:0] icmp_ln86_760_reg_1510;
reg   [0:0] icmp_ln86_760_reg_1510_pp0_iter1_reg;
wire   [0:0] icmp_ln86_761_fu_526_p2;
reg   [0:0] icmp_ln86_761_reg_1515;
reg   [0:0] icmp_ln86_761_reg_1515_pp0_iter1_reg;
wire   [0:0] icmp_ln86_762_fu_532_p2;
reg   [0:0] icmp_ln86_762_reg_1520;
reg   [0:0] icmp_ln86_762_reg_1520_pp0_iter1_reg;
reg   [0:0] icmp_ln86_762_reg_1520_pp0_iter2_reg;
wire   [0:0] icmp_ln86_763_fu_538_p2;
reg   [0:0] icmp_ln86_763_reg_1525;
reg   [0:0] icmp_ln86_763_reg_1525_pp0_iter1_reg;
reg   [0:0] icmp_ln86_763_reg_1525_pp0_iter2_reg;
wire   [0:0] icmp_ln86_764_fu_544_p2;
reg   [0:0] icmp_ln86_764_reg_1530;
reg   [0:0] icmp_ln86_764_reg_1530_pp0_iter1_reg;
reg   [0:0] icmp_ln86_764_reg_1530_pp0_iter2_reg;
wire   [0:0] icmp_ln86_765_fu_550_p2;
reg   [0:0] icmp_ln86_765_reg_1535;
reg   [0:0] icmp_ln86_765_reg_1535_pp0_iter1_reg;
reg   [0:0] icmp_ln86_765_reg_1535_pp0_iter2_reg;
reg   [0:0] icmp_ln86_765_reg_1535_pp0_iter3_reg;
wire   [0:0] icmp_ln86_766_fu_556_p2;
reg   [0:0] icmp_ln86_766_reg_1540;
reg   [0:0] icmp_ln86_766_reg_1540_pp0_iter1_reg;
reg   [0:0] icmp_ln86_766_reg_1540_pp0_iter2_reg;
reg   [0:0] icmp_ln86_766_reg_1540_pp0_iter3_reg;
wire   [0:0] icmp_ln86_767_fu_562_p2;
reg   [0:0] icmp_ln86_767_reg_1545;
reg   [0:0] icmp_ln86_767_reg_1545_pp0_iter1_reg;
reg   [0:0] icmp_ln86_767_reg_1545_pp0_iter2_reg;
reg   [0:0] icmp_ln86_767_reg_1545_pp0_iter3_reg;
wire   [0:0] icmp_ln86_768_fu_568_p2;
reg   [0:0] icmp_ln86_768_reg_1550;
reg   [0:0] icmp_ln86_768_reg_1550_pp0_iter1_reg;
reg   [0:0] icmp_ln86_768_reg_1550_pp0_iter2_reg;
reg   [0:0] icmp_ln86_768_reg_1550_pp0_iter3_reg;
reg   [0:0] icmp_ln86_768_reg_1550_pp0_iter4_reg;
wire   [0:0] icmp_ln86_769_fu_574_p2;
reg   [0:0] icmp_ln86_769_reg_1555;
reg   [0:0] icmp_ln86_769_reg_1555_pp0_iter1_reg;
reg   [0:0] icmp_ln86_769_reg_1555_pp0_iter2_reg;
reg   [0:0] icmp_ln86_769_reg_1555_pp0_iter3_reg;
reg   [0:0] icmp_ln86_769_reg_1555_pp0_iter4_reg;
wire   [0:0] icmp_ln86_770_fu_580_p2;
reg   [0:0] icmp_ln86_770_reg_1560;
reg   [0:0] icmp_ln86_770_reg_1560_pp0_iter1_reg;
reg   [0:0] icmp_ln86_770_reg_1560_pp0_iter2_reg;
reg   [0:0] icmp_ln86_770_reg_1560_pp0_iter3_reg;
reg   [0:0] icmp_ln86_770_reg_1560_pp0_iter4_reg;
wire   [0:0] icmp_ln86_771_fu_586_p2;
reg   [0:0] icmp_ln86_771_reg_1565;
reg   [0:0] icmp_ln86_771_reg_1565_pp0_iter1_reg;
reg   [0:0] icmp_ln86_771_reg_1565_pp0_iter2_reg;
reg   [0:0] icmp_ln86_771_reg_1565_pp0_iter3_reg;
reg   [0:0] icmp_ln86_771_reg_1565_pp0_iter4_reg;
reg   [0:0] icmp_ln86_771_reg_1565_pp0_iter5_reg;
wire   [0:0] icmp_ln86_772_fu_592_p2;
reg   [0:0] icmp_ln86_772_reg_1570;
reg   [0:0] icmp_ln86_772_reg_1570_pp0_iter1_reg;
reg   [0:0] icmp_ln86_772_reg_1570_pp0_iter2_reg;
reg   [0:0] icmp_ln86_772_reg_1570_pp0_iter3_reg;
reg   [0:0] icmp_ln86_772_reg_1570_pp0_iter4_reg;
reg   [0:0] icmp_ln86_772_reg_1570_pp0_iter5_reg;
wire   [0:0] icmp_ln86_773_fu_598_p2;
reg   [0:0] icmp_ln86_773_reg_1575;
reg   [0:0] icmp_ln86_773_reg_1575_pp0_iter1_reg;
reg   [0:0] icmp_ln86_773_reg_1575_pp0_iter2_reg;
reg   [0:0] icmp_ln86_773_reg_1575_pp0_iter3_reg;
reg   [0:0] icmp_ln86_773_reg_1575_pp0_iter4_reg;
reg   [0:0] icmp_ln86_773_reg_1575_pp0_iter5_reg;
reg   [0:0] icmp_ln86_773_reg_1575_pp0_iter6_reg;
wire   [0:0] and_ln102_fu_604_p2;
reg   [0:0] and_ln102_reg_1580;
reg   [0:0] and_ln102_reg_1580_pp0_iter1_reg;
reg   [0:0] and_ln102_reg_1580_pp0_iter2_reg;
wire   [0:0] and_ln104_fu_615_p2;
reg   [0:0] and_ln104_reg_1590;
wire   [0:0] and_ln102_916_fu_620_p2;
reg   [0:0] and_ln102_916_reg_1596;
wire   [0:0] and_ln104_132_fu_629_p2;
reg   [0:0] and_ln104_132_reg_1603;
wire   [0:0] and_ln102_920_fu_634_p2;
reg   [0:0] and_ln102_920_reg_1608;
wire   [0:0] and_ln102_921_fu_644_p2;
reg   [0:0] and_ln102_921_reg_1614;
wire   [0:0] or_ln117_fu_660_p2;
reg   [0:0] or_ln117_reg_1620;
wire   [0:0] xor_ln104_fu_666_p2;
reg   [0:0] xor_ln104_reg_1625;
wire   [0:0] and_ln102_917_fu_671_p2;
reg   [0:0] and_ln102_917_reg_1631;
wire   [0:0] and_ln104_133_fu_680_p2;
reg   [0:0] and_ln104_133_reg_1637;
reg   [0:0] and_ln104_133_reg_1637_pp0_iter3_reg;
wire   [0:0] and_ln102_922_fu_690_p2;
reg   [0:0] and_ln102_922_reg_1643;
wire   [3:0] select_ln117_727_fu_791_p3;
reg   [3:0] select_ln117_727_reg_1648;
wire   [0:0] or_ln117_655_fu_798_p2;
reg   [0:0] or_ln117_655_reg_1653;
wire   [0:0] and_ln102_915_fu_803_p2;
reg   [0:0] and_ln102_915_reg_1659;
wire   [0:0] and_ln104_131_fu_812_p2;
reg   [0:0] and_ln104_131_reg_1665;
wire   [0:0] and_ln102_918_fu_817_p2;
reg   [0:0] and_ln102_918_reg_1671;
wire   [0:0] and_ln102_924_fu_831_p2;
reg   [0:0] and_ln102_924_reg_1677;
wire   [0:0] or_ln117_659_fu_905_p2;
reg   [0:0] or_ln117_659_reg_1683;
wire   [3:0] select_ln117_733_fu_919_p3;
reg   [3:0] select_ln117_733_reg_1688;
wire   [0:0] and_ln104_134_fu_932_p2;
reg   [0:0] and_ln104_134_reg_1693;
wire   [0:0] and_ln102_919_fu_937_p2;
reg   [0:0] and_ln102_919_reg_1698;
reg   [0:0] and_ln102_919_reg_1698_pp0_iter5_reg;
wire   [0:0] and_ln104_135_fu_946_p2;
reg   [0:0] and_ln104_135_reg_1705;
reg   [0:0] and_ln104_135_reg_1705_pp0_iter5_reg;
reg   [0:0] and_ln104_135_reg_1705_pp0_iter6_reg;
wire   [0:0] and_ln102_925_fu_961_p2;
reg   [0:0] and_ln102_925_reg_1711;
wire   [0:0] or_ln117_664_fu_1044_p2;
reg   [0:0] or_ln117_664_reg_1716;
wire   [4:0] select_ln117_739_fu_1056_p3;
reg   [4:0] select_ln117_739_reg_1721;
wire   [0:0] or_ln117_666_fu_1064_p2;
reg   [0:0] or_ln117_666_reg_1726;
wire   [0:0] or_ln117_668_fu_1070_p2;
reg   [0:0] or_ln117_668_reg_1732;
reg   [0:0] or_ln117_668_reg_1732_pp0_iter5_reg;
wire   [0:0] or_ln117_670_fu_1146_p2;
reg   [0:0] or_ln117_670_reg_1740;
wire   [4:0] select_ln117_745_fu_1159_p3;
reg   [4:0] select_ln117_745_reg_1745;
wire   [0:0] or_ln117_674_fu_1221_p2;
reg   [0:0] or_ln117_674_reg_1750;
wire   [4:0] select_ln117_749_fu_1235_p3;
reg   [4:0] select_ln117_749_reg_1755;
wire    ap_block_pp0_stage0;
wire   [15:0] tmp_fu_504_p4;
wire   [0:0] xor_ln104_351_fu_610_p2;
wire   [0:0] xor_ln104_353_fu_624_p2;
wire   [0:0] xor_ln104_357_fu_639_p2;
wire   [0:0] and_ln102_929_fu_649_p2;
wire   [0:0] and_ln102_930_fu_654_p2;
wire   [0:0] xor_ln104_354_fu_675_p2;
wire   [0:0] xor_ln104_358_fu_685_p2;
wire   [0:0] and_ln102_932_fu_703_p2;
wire   [0:0] and_ln102_928_fu_695_p2;
wire   [0:0] xor_ln117_fu_713_p2;
wire   [1:0] zext_ln117_fu_719_p1;
wire   [1:0] select_ln117_fu_723_p3;
wire   [1:0] select_ln117_722_fu_730_p3;
wire   [0:0] and_ln102_931_fu_699_p2;
wire   [2:0] zext_ln117_79_fu_737_p1;
wire   [0:0] or_ln117_651_fu_741_p2;
wire   [2:0] select_ln117_723_fu_746_p3;
wire   [0:0] or_ln117_652_fu_753_p2;
wire   [0:0] and_ln102_933_fu_708_p2;
wire   [2:0] select_ln117_724_fu_757_p3;
wire   [0:0] or_ln117_653_fu_765_p2;
wire   [2:0] select_ln117_725_fu_771_p3;
wire   [2:0] select_ln117_726_fu_779_p3;
wire   [3:0] zext_ln117_80_fu_787_p1;
wire   [0:0] xor_ln104_352_fu_807_p2;
wire   [0:0] xor_ln104_359_fu_822_p2;
wire   [0:0] and_ln102_935_fu_840_p2;
wire   [0:0] and_ln102_923_fu_827_p2;
wire   [0:0] and_ln102_934_fu_836_p2;
wire   [0:0] or_ln117_654_fu_855_p2;
wire   [0:0] and_ln102_936_fu_845_p2;
wire   [3:0] select_ln117_728_fu_860_p3;
wire   [0:0] or_ln117_656_fu_867_p2;
wire   [3:0] select_ln117_729_fu_872_p3;
wire   [0:0] or_ln117_657_fu_879_p2;
wire   [0:0] and_ln102_937_fu_850_p2;
wire   [3:0] select_ln117_730_fu_883_p3;
wire   [0:0] or_ln117_658_fu_891_p2;
wire   [3:0] select_ln117_731_fu_897_p3;
wire   [3:0] select_ln117_732_fu_911_p3;
wire   [0:0] xor_ln104_355_fu_927_p2;
wire   [0:0] xor_ln104_356_fu_941_p2;
wire   [0:0] xor_ln104_360_fu_951_p2;
wire   [0:0] and_ln102_938_fu_966_p2;
wire   [0:0] xor_ln104_361_fu_956_p2;
wire   [0:0] and_ln102_941_fu_980_p2;
wire   [0:0] and_ln102_939_fu_971_p2;
wire   [0:0] or_ln117_660_fu_990_p2;
wire   [3:0] select_ln117_734_fu_995_p3;
wire   [0:0] and_ln102_940_fu_976_p2;
wire   [4:0] zext_ln117_81_fu_1002_p1;
wire   [0:0] or_ln117_661_fu_1006_p2;
wire   [4:0] select_ln117_735_fu_1011_p3;
wire   [0:0] or_ln117_662_fu_1018_p2;
wire   [0:0] and_ln102_942_fu_985_p2;
wire   [4:0] select_ln117_736_fu_1022_p3;
wire   [0:0] or_ln117_663_fu_1030_p2;
wire   [4:0] select_ln117_737_fu_1036_p3;
wire   [4:0] select_ln117_738_fu_1048_p3;
wire   [0:0] xor_ln104_362_fu_1074_p2;
wire   [0:0] and_ln102_944_fu_1087_p2;
wire   [0:0] and_ln102_926_fu_1079_p2;
wire   [0:0] and_ln102_943_fu_1083_p2;
wire   [0:0] or_ln117_665_fu_1102_p2;
wire   [0:0] and_ln102_945_fu_1092_p2;
wire   [4:0] select_ln117_740_fu_1107_p3;
wire   [0:0] or_ln117_667_fu_1114_p2;
wire   [4:0] select_ln117_741_fu_1119_p3;
wire   [0:0] and_ln102_946_fu_1097_p2;
wire   [4:0] select_ln117_742_fu_1126_p3;
wire   [0:0] or_ln117_669_fu_1134_p2;
wire   [4:0] select_ln117_743_fu_1139_p3;
wire   [4:0] select_ln117_744_fu_1151_p3;
wire   [0:0] xor_ln104_363_fu_1167_p2;
wire   [0:0] and_ln102_947_fu_1176_p2;
wire   [0:0] and_ln102_927_fu_1172_p2;
wire   [0:0] and_ln102_948_fu_1181_p2;
wire   [0:0] or_ln117_671_fu_1191_p2;
wire   [0:0] or_ln117_672_fu_1196_p2;
wire   [0:0] and_ln102_949_fu_1186_p2;
wire   [4:0] select_ln117_746_fu_1200_p3;
wire   [0:0] or_ln117_673_fu_1207_p2;
wire   [4:0] select_ln117_747_fu_1213_p3;
wire   [4:0] select_ln117_748_fu_1227_p3;
wire   [0:0] xor_ln104_364_fu_1243_p2;
wire   [0:0] and_ln102_950_fu_1248_p2;
wire   [0:0] and_ln102_951_fu_1253_p2;
wire   [0:0] or_ln117_675_fu_1258_p2;
wire   [11:0] agg_result_fu_1270_p65;
wire   [4:0] agg_result_fu_1270_p66;
wire   [11:0] agg_result_fu_1270_p67;
reg   [17:0] p_read1_int_reg;
reg   [17:0] p_read2_int_reg;
reg   [17:0] p_read3_int_reg;
reg   [17:0] p_read4_int_reg;
reg   [17:0] p_read5_int_reg;
reg   [17:0] p_read6_int_reg;
reg   [17:0] p_read7_int_reg;
reg   [17:0] p_read8_int_reg;
reg   [17:0] p_read9_int_reg;
reg   [17:0] p_read10_int_reg;
reg   [17:0] p_read11_int_reg;
reg   [17:0] p_read12_int_reg;
reg   [17:0] p_read13_int_reg;
reg   [17:0] p_read14_int_reg;
reg   [17:0] p_read15_int_reg;
reg   [17:0] p_read16_int_reg;
reg   [17:0] p_read17_int_reg;
reg   [17:0] p_read18_int_reg;
reg   [17:0] p_read19_int_reg;
reg   [17:0] p_read20_int_reg;
reg   [17:0] p_read21_int_reg;
wire   [4:0] agg_result_fu_1270_p1;
wire   [4:0] agg_result_fu_1270_p3;
wire   [4:0] agg_result_fu_1270_p5;
wire   [4:0] agg_result_fu_1270_p7;
wire   [4:0] agg_result_fu_1270_p9;
wire   [4:0] agg_result_fu_1270_p11;
wire   [4:0] agg_result_fu_1270_p13;
wire   [4:0] agg_result_fu_1270_p15;
wire   [4:0] agg_result_fu_1270_p17;
wire   [4:0] agg_result_fu_1270_p19;
wire   [4:0] agg_result_fu_1270_p21;
wire   [4:0] agg_result_fu_1270_p23;
wire   [4:0] agg_result_fu_1270_p25;
wire   [4:0] agg_result_fu_1270_p27;
wire   [4:0] agg_result_fu_1270_p29;
wire   [4:0] agg_result_fu_1270_p31;
wire  signed [4:0] agg_result_fu_1270_p33;
wire  signed [4:0] agg_result_fu_1270_p35;
wire  signed [4:0] agg_result_fu_1270_p37;
wire  signed [4:0] agg_result_fu_1270_p39;
wire  signed [4:0] agg_result_fu_1270_p41;
wire  signed [4:0] agg_result_fu_1270_p43;
wire  signed [4:0] agg_result_fu_1270_p45;
wire  signed [4:0] agg_result_fu_1270_p47;
wire  signed [4:0] agg_result_fu_1270_p49;
wire  signed [4:0] agg_result_fu_1270_p51;
wire  signed [4:0] agg_result_fu_1270_p53;
wire  signed [4:0] agg_result_fu_1270_p55;
wire  signed [4:0] agg_result_fu_1270_p57;
wire  signed [4:0] agg_result_fu_1270_p59;
wire  signed [4:0] agg_result_fu_1270_p61;
wire  signed [4:0] agg_result_fu_1270_p63;
wire    ap_ce_reg;

(* dissolve_hierarchy = "yes" *) conifer_jettag_accelerator_sparsemux_65_5_12_1_1_x14 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 12 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 12 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 12 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 12 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 12 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 12 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 12 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 12 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 12 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 12 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 12 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 12 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 12 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 12 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 12 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 12 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 12 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 12 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 12 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 12 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 12 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 12 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 12 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 12 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 12 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 12 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 12 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 12 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
sparsemux_65_5_12_1_1_x14_U811(
    .din0(12'd4002),
    .din1(12'd728),
    .din2(12'd3900),
    .din3(12'd1483),
    .din4(12'd3814),
    .din5(12'd589),
    .din6(12'd3663),
    .din7(12'd19),
    .din8(12'd13),
    .din9(12'd235),
    .din10(12'd121),
    .din11(12'd1160),
    .din12(12'd3972),
    .din13(12'd3808),
    .din14(12'd136),
    .din15(12'd3988),
    .din16(12'd3583),
    .din17(12'd3878),
    .din18(12'd759),
    .din19(12'd3747),
    .din20(12'd3714),
    .din21(12'd4070),
    .din22(12'd3790),
    .din23(12'd1321),
    .din24(12'd4093),
    .din25(12'd1630),
    .din26(12'd3873),
    .din27(12'd174),
    .din28(12'd3805),
    .din29(12'd574),
    .din30(12'd3746),
    .din31(12'd911),
    .def(agg_result_fu_1270_p65),
    .sel(agg_result_fu_1270_p66),
    .dout(agg_result_fu_1270_p67)
);

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        and_ln102_915_reg_1659 <= and_ln102_915_fu_803_p2;
        and_ln102_916_reg_1596 <= and_ln102_916_fu_620_p2;
        and_ln102_917_reg_1631 <= and_ln102_917_fu_671_p2;
        and_ln102_918_reg_1671 <= and_ln102_918_fu_817_p2;
        and_ln102_919_reg_1698 <= and_ln102_919_fu_937_p2;
        and_ln102_919_reg_1698_pp0_iter5_reg <= and_ln102_919_reg_1698;
        and_ln102_920_reg_1608 <= and_ln102_920_fu_634_p2;
        and_ln102_921_reg_1614 <= and_ln102_921_fu_644_p2;
        and_ln102_922_reg_1643 <= and_ln102_922_fu_690_p2;
        and_ln102_924_reg_1677 <= and_ln102_924_fu_831_p2;
        and_ln102_925_reg_1711 <= and_ln102_925_fu_961_p2;
        and_ln102_reg_1580 <= and_ln102_fu_604_p2;
        and_ln102_reg_1580_pp0_iter1_reg <= and_ln102_reg_1580;
        and_ln102_reg_1580_pp0_iter2_reg <= and_ln102_reg_1580_pp0_iter1_reg;
        and_ln104_131_reg_1665 <= and_ln104_131_fu_812_p2;
        and_ln104_132_reg_1603 <= and_ln104_132_fu_629_p2;
        and_ln104_133_reg_1637 <= and_ln104_133_fu_680_p2;
        and_ln104_133_reg_1637_pp0_iter3_reg <= and_ln104_133_reg_1637;
        and_ln104_134_reg_1693 <= and_ln104_134_fu_932_p2;
        and_ln104_135_reg_1705 <= and_ln104_135_fu_946_p2;
        and_ln104_135_reg_1705_pp0_iter5_reg <= and_ln104_135_reg_1705;
        and_ln104_135_reg_1705_pp0_iter6_reg <= and_ln104_135_reg_1705_pp0_iter5_reg;
        and_ln104_reg_1590 <= and_ln104_fu_615_p2;
        icmp_ln86_744_reg_1417 <= icmp_ln86_744_fu_414_p2;
        icmp_ln86_745_reg_1422 <= icmp_ln86_745_fu_420_p2;
        icmp_ln86_745_reg_1422_pp0_iter1_reg <= icmp_ln86_745_reg_1422;
        icmp_ln86_745_reg_1422_pp0_iter2_reg <= icmp_ln86_745_reg_1422_pp0_iter1_reg;
        icmp_ln86_746_reg_1428 <= icmp_ln86_746_fu_426_p2;
        icmp_ln86_747_reg_1434 <= icmp_ln86_747_fu_432_p2;
        icmp_ln86_747_reg_1434_pp0_iter1_reg <= icmp_ln86_747_reg_1434;
        icmp_ln86_748_reg_1440 <= icmp_ln86_748_fu_438_p2;
        icmp_ln86_748_reg_1440_pp0_iter1_reg <= icmp_ln86_748_reg_1440;
        icmp_ln86_748_reg_1440_pp0_iter2_reg <= icmp_ln86_748_reg_1440_pp0_iter1_reg;
        icmp_ln86_748_reg_1440_pp0_iter3_reg <= icmp_ln86_748_reg_1440_pp0_iter2_reg;
        icmp_ln86_749_reg_1446 <= icmp_ln86_749_fu_444_p2;
        icmp_ln86_749_reg_1446_pp0_iter1_reg <= icmp_ln86_749_reg_1446;
        icmp_ln86_749_reg_1446_pp0_iter2_reg <= icmp_ln86_749_reg_1446_pp0_iter1_reg;
        icmp_ln86_749_reg_1446_pp0_iter3_reg <= icmp_ln86_749_reg_1446_pp0_iter2_reg;
        icmp_ln86_750_reg_1452 <= icmp_ln86_750_fu_450_p2;
        icmp_ln86_751_reg_1458 <= icmp_ln86_751_fu_456_p2;
        icmp_ln86_751_reg_1458_pp0_iter1_reg <= icmp_ln86_751_reg_1458;
        icmp_ln86_752_reg_1464 <= icmp_ln86_752_fu_462_p2;
        icmp_ln86_752_reg_1464_pp0_iter1_reg <= icmp_ln86_752_reg_1464;
        icmp_ln86_752_reg_1464_pp0_iter2_reg <= icmp_ln86_752_reg_1464_pp0_iter1_reg;
        icmp_ln86_753_reg_1470 <= icmp_ln86_753_fu_468_p2;
        icmp_ln86_753_reg_1470_pp0_iter1_reg <= icmp_ln86_753_reg_1470;
        icmp_ln86_753_reg_1470_pp0_iter2_reg <= icmp_ln86_753_reg_1470_pp0_iter1_reg;
        icmp_ln86_753_reg_1470_pp0_iter3_reg <= icmp_ln86_753_reg_1470_pp0_iter2_reg;
        icmp_ln86_754_reg_1476 <= icmp_ln86_754_fu_474_p2;
        icmp_ln86_754_reg_1476_pp0_iter1_reg <= icmp_ln86_754_reg_1476;
        icmp_ln86_754_reg_1476_pp0_iter2_reg <= icmp_ln86_754_reg_1476_pp0_iter1_reg;
        icmp_ln86_754_reg_1476_pp0_iter3_reg <= icmp_ln86_754_reg_1476_pp0_iter2_reg;
        icmp_ln86_755_reg_1482 <= icmp_ln86_755_fu_480_p2;
        icmp_ln86_755_reg_1482_pp0_iter1_reg <= icmp_ln86_755_reg_1482;
        icmp_ln86_755_reg_1482_pp0_iter2_reg <= icmp_ln86_755_reg_1482_pp0_iter1_reg;
        icmp_ln86_755_reg_1482_pp0_iter3_reg <= icmp_ln86_755_reg_1482_pp0_iter2_reg;
        icmp_ln86_755_reg_1482_pp0_iter4_reg <= icmp_ln86_755_reg_1482_pp0_iter3_reg;
        icmp_ln86_756_reg_1488 <= icmp_ln86_756_fu_486_p2;
        icmp_ln86_756_reg_1488_pp0_iter1_reg <= icmp_ln86_756_reg_1488;
        icmp_ln86_756_reg_1488_pp0_iter2_reg <= icmp_ln86_756_reg_1488_pp0_iter1_reg;
        icmp_ln86_756_reg_1488_pp0_iter3_reg <= icmp_ln86_756_reg_1488_pp0_iter2_reg;
        icmp_ln86_756_reg_1488_pp0_iter4_reg <= icmp_ln86_756_reg_1488_pp0_iter3_reg;
        icmp_ln86_756_reg_1488_pp0_iter5_reg <= icmp_ln86_756_reg_1488_pp0_iter4_reg;
        icmp_ln86_757_reg_1494 <= icmp_ln86_757_fu_492_p2;
        icmp_ln86_757_reg_1494_pp0_iter1_reg <= icmp_ln86_757_reg_1494;
        icmp_ln86_757_reg_1494_pp0_iter2_reg <= icmp_ln86_757_reg_1494_pp0_iter1_reg;
        icmp_ln86_757_reg_1494_pp0_iter3_reg <= icmp_ln86_757_reg_1494_pp0_iter2_reg;
        icmp_ln86_757_reg_1494_pp0_iter4_reg <= icmp_ln86_757_reg_1494_pp0_iter3_reg;
        icmp_ln86_757_reg_1494_pp0_iter5_reg <= icmp_ln86_757_reg_1494_pp0_iter4_reg;
        icmp_ln86_757_reg_1494_pp0_iter6_reg <= icmp_ln86_757_reg_1494_pp0_iter5_reg;
        icmp_ln86_758_reg_1500 <= icmp_ln86_758_fu_498_p2;
        icmp_ln86_758_reg_1500_pp0_iter1_reg <= icmp_ln86_758_reg_1500;
        icmp_ln86_759_reg_1505 <= icmp_ln86_759_fu_514_p2;
        icmp_ln86_760_reg_1510 <= icmp_ln86_760_fu_520_p2;
        icmp_ln86_760_reg_1510_pp0_iter1_reg <= icmp_ln86_760_reg_1510;
        icmp_ln86_761_reg_1515 <= icmp_ln86_761_fu_526_p2;
        icmp_ln86_761_reg_1515_pp0_iter1_reg <= icmp_ln86_761_reg_1515;
        icmp_ln86_762_reg_1520 <= icmp_ln86_762_fu_532_p2;
        icmp_ln86_762_reg_1520_pp0_iter1_reg <= icmp_ln86_762_reg_1520;
        icmp_ln86_762_reg_1520_pp0_iter2_reg <= icmp_ln86_762_reg_1520_pp0_iter1_reg;
        icmp_ln86_763_reg_1525 <= icmp_ln86_763_fu_538_p2;
        icmp_ln86_763_reg_1525_pp0_iter1_reg <= icmp_ln86_763_reg_1525;
        icmp_ln86_763_reg_1525_pp0_iter2_reg <= icmp_ln86_763_reg_1525_pp0_iter1_reg;
        icmp_ln86_764_reg_1530 <= icmp_ln86_764_fu_544_p2;
        icmp_ln86_764_reg_1530_pp0_iter1_reg <= icmp_ln86_764_reg_1530;
        icmp_ln86_764_reg_1530_pp0_iter2_reg <= icmp_ln86_764_reg_1530_pp0_iter1_reg;
        icmp_ln86_765_reg_1535 <= icmp_ln86_765_fu_550_p2;
        icmp_ln86_765_reg_1535_pp0_iter1_reg <= icmp_ln86_765_reg_1535;
        icmp_ln86_765_reg_1535_pp0_iter2_reg <= icmp_ln86_765_reg_1535_pp0_iter1_reg;
        icmp_ln86_765_reg_1535_pp0_iter3_reg <= icmp_ln86_765_reg_1535_pp0_iter2_reg;
        icmp_ln86_766_reg_1540 <= icmp_ln86_766_fu_556_p2;
        icmp_ln86_766_reg_1540_pp0_iter1_reg <= icmp_ln86_766_reg_1540;
        icmp_ln86_766_reg_1540_pp0_iter2_reg <= icmp_ln86_766_reg_1540_pp0_iter1_reg;
        icmp_ln86_766_reg_1540_pp0_iter3_reg <= icmp_ln86_766_reg_1540_pp0_iter2_reg;
        icmp_ln86_767_reg_1545 <= icmp_ln86_767_fu_562_p2;
        icmp_ln86_767_reg_1545_pp0_iter1_reg <= icmp_ln86_767_reg_1545;
        icmp_ln86_767_reg_1545_pp0_iter2_reg <= icmp_ln86_767_reg_1545_pp0_iter1_reg;
        icmp_ln86_767_reg_1545_pp0_iter3_reg <= icmp_ln86_767_reg_1545_pp0_iter2_reg;
        icmp_ln86_768_reg_1550 <= icmp_ln86_768_fu_568_p2;
        icmp_ln86_768_reg_1550_pp0_iter1_reg <= icmp_ln86_768_reg_1550;
        icmp_ln86_768_reg_1550_pp0_iter2_reg <= icmp_ln86_768_reg_1550_pp0_iter1_reg;
        icmp_ln86_768_reg_1550_pp0_iter3_reg <= icmp_ln86_768_reg_1550_pp0_iter2_reg;
        icmp_ln86_768_reg_1550_pp0_iter4_reg <= icmp_ln86_768_reg_1550_pp0_iter3_reg;
        icmp_ln86_769_reg_1555 <= icmp_ln86_769_fu_574_p2;
        icmp_ln86_769_reg_1555_pp0_iter1_reg <= icmp_ln86_769_reg_1555;
        icmp_ln86_769_reg_1555_pp0_iter2_reg <= icmp_ln86_769_reg_1555_pp0_iter1_reg;
        icmp_ln86_769_reg_1555_pp0_iter3_reg <= icmp_ln86_769_reg_1555_pp0_iter2_reg;
        icmp_ln86_769_reg_1555_pp0_iter4_reg <= icmp_ln86_769_reg_1555_pp0_iter3_reg;
        icmp_ln86_770_reg_1560 <= icmp_ln86_770_fu_580_p2;
        icmp_ln86_770_reg_1560_pp0_iter1_reg <= icmp_ln86_770_reg_1560;
        icmp_ln86_770_reg_1560_pp0_iter2_reg <= icmp_ln86_770_reg_1560_pp0_iter1_reg;
        icmp_ln86_770_reg_1560_pp0_iter3_reg <= icmp_ln86_770_reg_1560_pp0_iter2_reg;
        icmp_ln86_770_reg_1560_pp0_iter4_reg <= icmp_ln86_770_reg_1560_pp0_iter3_reg;
        icmp_ln86_771_reg_1565 <= icmp_ln86_771_fu_586_p2;
        icmp_ln86_771_reg_1565_pp0_iter1_reg <= icmp_ln86_771_reg_1565;
        icmp_ln86_771_reg_1565_pp0_iter2_reg <= icmp_ln86_771_reg_1565_pp0_iter1_reg;
        icmp_ln86_771_reg_1565_pp0_iter3_reg <= icmp_ln86_771_reg_1565_pp0_iter2_reg;
        icmp_ln86_771_reg_1565_pp0_iter4_reg <= icmp_ln86_771_reg_1565_pp0_iter3_reg;
        icmp_ln86_771_reg_1565_pp0_iter5_reg <= icmp_ln86_771_reg_1565_pp0_iter4_reg;
        icmp_ln86_772_reg_1570 <= icmp_ln86_772_fu_592_p2;
        icmp_ln86_772_reg_1570_pp0_iter1_reg <= icmp_ln86_772_reg_1570;
        icmp_ln86_772_reg_1570_pp0_iter2_reg <= icmp_ln86_772_reg_1570_pp0_iter1_reg;
        icmp_ln86_772_reg_1570_pp0_iter3_reg <= icmp_ln86_772_reg_1570_pp0_iter2_reg;
        icmp_ln86_772_reg_1570_pp0_iter4_reg <= icmp_ln86_772_reg_1570_pp0_iter3_reg;
        icmp_ln86_772_reg_1570_pp0_iter5_reg <= icmp_ln86_772_reg_1570_pp0_iter4_reg;
        icmp_ln86_773_reg_1575 <= icmp_ln86_773_fu_598_p2;
        icmp_ln86_773_reg_1575_pp0_iter1_reg <= icmp_ln86_773_reg_1575;
        icmp_ln86_773_reg_1575_pp0_iter2_reg <= icmp_ln86_773_reg_1575_pp0_iter1_reg;
        icmp_ln86_773_reg_1575_pp0_iter3_reg <= icmp_ln86_773_reg_1575_pp0_iter2_reg;
        icmp_ln86_773_reg_1575_pp0_iter4_reg <= icmp_ln86_773_reg_1575_pp0_iter3_reg;
        icmp_ln86_773_reg_1575_pp0_iter5_reg <= icmp_ln86_773_reg_1575_pp0_iter4_reg;
        icmp_ln86_773_reg_1575_pp0_iter6_reg <= icmp_ln86_773_reg_1575_pp0_iter5_reg;
        icmp_ln86_reg_1406 <= icmp_ln86_fu_408_p2;
        icmp_ln86_reg_1406_pp0_iter1_reg <= icmp_ln86_reg_1406;
        icmp_ln86_reg_1406_pp0_iter2_reg <= icmp_ln86_reg_1406_pp0_iter1_reg;
        icmp_ln86_reg_1406_pp0_iter3_reg <= icmp_ln86_reg_1406_pp0_iter2_reg;
        or_ln117_655_reg_1653 <= or_ln117_655_fu_798_p2;
        or_ln117_659_reg_1683 <= or_ln117_659_fu_905_p2;
        or_ln117_664_reg_1716 <= or_ln117_664_fu_1044_p2;
        or_ln117_666_reg_1726 <= or_ln117_666_fu_1064_p2;
        or_ln117_668_reg_1732 <= or_ln117_668_fu_1070_p2;
        or_ln117_668_reg_1732_pp0_iter5_reg <= or_ln117_668_reg_1732;
        or_ln117_670_reg_1740 <= or_ln117_670_fu_1146_p2;
        or_ln117_674_reg_1750 <= or_ln117_674_fu_1221_p2;
        or_ln117_reg_1620 <= or_ln117_fu_660_p2;
        select_ln117_727_reg_1648 <= select_ln117_727_fu_791_p3;
        select_ln117_733_reg_1688 <= select_ln117_733_fu_919_p3;
        select_ln117_739_reg_1721 <= select_ln117_739_fu_1056_p3;
        select_ln117_745_reg_1745 <= select_ln117_745_fu_1159_p3;
        select_ln117_749_reg_1755 <= select_ln117_749_fu_1235_p3;
        xor_ln104_reg_1625 <= xor_ln104_fu_666_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read10_int_reg <= p_read10;
        p_read11_int_reg <= p_read11;
        p_read12_int_reg <= p_read12;
        p_read13_int_reg <= p_read13;
        p_read14_int_reg <= p_read14;
        p_read15_int_reg <= p_read15;
        p_read16_int_reg <= p_read16;
        p_read17_int_reg <= p_read17;
        p_read18_int_reg <= p_read18;
        p_read19_int_reg <= p_read19;
        p_read1_int_reg <= p_read1;
        p_read20_int_reg <= p_read20;
        p_read21_int_reg <= p_read21;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read9_int_reg <= p_read9;
    end
end

assign agg_result_fu_1270_p65 = 'bx;

assign agg_result_fu_1270_p66 = ((or_ln117_675_fu_1258_p2[0:0] == 1'b1) ? select_ln117_749_reg_1755 : 5'd31);

assign and_ln102_915_fu_803_p2 = (xor_ln104_reg_1625 & icmp_ln86_745_reg_1422_pp0_iter2_reg);

assign and_ln102_916_fu_620_p2 = (icmp_ln86_746_reg_1428 & and_ln102_reg_1580);

assign and_ln102_917_fu_671_p2 = (icmp_ln86_747_reg_1434_pp0_iter1_reg & and_ln104_reg_1590);

assign and_ln102_918_fu_817_p2 = (icmp_ln86_748_reg_1440_pp0_iter2_reg & and_ln102_915_fu_803_p2);

assign and_ln102_919_fu_937_p2 = (icmp_ln86_749_reg_1446_pp0_iter3_reg & and_ln104_131_reg_1665);

assign and_ln102_920_fu_634_p2 = (icmp_ln86_750_reg_1452 & and_ln102_916_fu_620_p2);

assign and_ln102_921_fu_644_p2 = (icmp_ln86_751_reg_1458 & and_ln104_132_fu_629_p2);

assign and_ln102_922_fu_690_p2 = (icmp_ln86_752_reg_1464_pp0_iter1_reg & and_ln102_917_fu_671_p2);

assign and_ln102_923_fu_827_p2 = (icmp_ln86_753_reg_1470_pp0_iter2_reg & and_ln104_133_reg_1637);

assign and_ln102_924_fu_831_p2 = (icmp_ln86_754_reg_1476_pp0_iter2_reg & and_ln102_918_fu_817_p2);

assign and_ln102_925_fu_961_p2 = (icmp_ln86_755_reg_1482_pp0_iter3_reg & and_ln104_134_fu_932_p2);

assign and_ln102_926_fu_1079_p2 = (icmp_ln86_756_reg_1488_pp0_iter4_reg & and_ln102_919_reg_1698);

assign and_ln102_927_fu_1172_p2 = (icmp_ln86_757_reg_1494_pp0_iter5_reg & and_ln104_135_reg_1705_pp0_iter5_reg);

assign and_ln102_928_fu_695_p2 = (icmp_ln86_758_reg_1500_pp0_iter1_reg & and_ln102_920_reg_1608);

assign and_ln102_929_fu_649_p2 = (xor_ln104_357_fu_639_p2 & icmp_ln86_759_reg_1505);

assign and_ln102_930_fu_654_p2 = (and_ln102_929_fu_649_p2 & and_ln102_916_fu_620_p2);

assign and_ln102_931_fu_699_p2 = (icmp_ln86_760_reg_1510_pp0_iter1_reg & and_ln102_921_reg_1614);

assign and_ln102_932_fu_703_p2 = (xor_ln104_358_fu_685_p2 & icmp_ln86_761_reg_1515_pp0_iter1_reg);

assign and_ln102_933_fu_708_p2 = (and_ln104_132_reg_1603 & and_ln102_932_fu_703_p2);

assign and_ln102_934_fu_836_p2 = (icmp_ln86_762_reg_1520_pp0_iter2_reg & and_ln102_922_reg_1643);

assign and_ln102_935_fu_840_p2 = (xor_ln104_359_fu_822_p2 & icmp_ln86_763_reg_1525_pp0_iter2_reg);

assign and_ln102_936_fu_845_p2 = (and_ln102_935_fu_840_p2 & and_ln102_917_reg_1631);

assign and_ln102_937_fu_850_p2 = (icmp_ln86_764_reg_1530_pp0_iter2_reg & and_ln102_923_fu_827_p2);

assign and_ln102_938_fu_966_p2 = (xor_ln104_360_fu_951_p2 & icmp_ln86_765_reg_1535_pp0_iter3_reg);

assign and_ln102_939_fu_971_p2 = (and_ln104_133_reg_1637_pp0_iter3_reg & and_ln102_938_fu_966_p2);

assign and_ln102_940_fu_976_p2 = (icmp_ln86_766_reg_1540_pp0_iter3_reg & and_ln102_924_reg_1677);

assign and_ln102_941_fu_980_p2 = (xor_ln104_361_fu_956_p2 & icmp_ln86_767_reg_1545_pp0_iter3_reg);

assign and_ln102_942_fu_985_p2 = (and_ln102_941_fu_980_p2 & and_ln102_918_reg_1671);

assign and_ln102_943_fu_1083_p2 = (icmp_ln86_768_reg_1550_pp0_iter4_reg & and_ln102_925_reg_1711);

assign and_ln102_944_fu_1087_p2 = (xor_ln104_362_fu_1074_p2 & icmp_ln86_769_reg_1555_pp0_iter4_reg);

assign and_ln102_945_fu_1092_p2 = (and_ln104_134_reg_1693 & and_ln102_944_fu_1087_p2);

assign and_ln102_946_fu_1097_p2 = (icmp_ln86_770_reg_1560_pp0_iter4_reg & and_ln102_926_fu_1079_p2);

assign and_ln102_947_fu_1176_p2 = (xor_ln104_363_fu_1167_p2 & icmp_ln86_771_reg_1565_pp0_iter5_reg);

assign and_ln102_948_fu_1181_p2 = (and_ln102_947_fu_1176_p2 & and_ln102_919_reg_1698_pp0_iter5_reg);

assign and_ln102_949_fu_1186_p2 = (icmp_ln86_772_reg_1570_pp0_iter5_reg & and_ln102_927_fu_1172_p2);

assign and_ln102_950_fu_1248_p2 = (xor_ln104_364_fu_1243_p2 & icmp_ln86_773_reg_1575_pp0_iter6_reg);

assign and_ln102_951_fu_1253_p2 = (and_ln104_135_reg_1705_pp0_iter6_reg & and_ln102_950_fu_1248_p2);

assign and_ln102_fu_604_p2 = (icmp_ln86_fu_408_p2 & icmp_ln86_744_fu_414_p2);

assign and_ln104_131_fu_812_p2 = (xor_ln104_reg_1625 & xor_ln104_352_fu_807_p2);

assign and_ln104_132_fu_629_p2 = (xor_ln104_353_fu_624_p2 & and_ln102_reg_1580);

assign and_ln104_133_fu_680_p2 = (xor_ln104_354_fu_675_p2 & and_ln104_reg_1590);

assign and_ln104_134_fu_932_p2 = (xor_ln104_355_fu_927_p2 & and_ln102_915_reg_1659);

assign and_ln104_135_fu_946_p2 = (xor_ln104_356_fu_941_p2 & and_ln104_131_reg_1665);

assign and_ln104_fu_615_p2 = (xor_ln104_351_fu_610_p2 & icmp_ln86_reg_1406);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = agg_result_fu_1270_p67;

assign icmp_ln86_744_fu_414_p2 = (($signed(p_read1_int_reg) < $signed(18'd171450)) ? 1'b1 : 1'b0);

assign icmp_ln86_745_fu_420_p2 = (($signed(p_read1_int_reg) < $signed(18'd22621)) ? 1'b1 : 1'b0);

assign icmp_ln86_746_fu_426_p2 = (($signed(p_read10_int_reg) < $signed(18'd12)) ? 1'b1 : 1'b0);

assign icmp_ln86_747_fu_432_p2 = (($signed(p_read21_int_reg) < $signed(18'd53761)) ? 1'b1 : 1'b0);

assign icmp_ln86_748_fu_438_p2 = (($signed(p_read11_int_reg) < $signed(18'd1350)) ? 1'b1 : 1'b0);

assign icmp_ln86_749_fu_444_p2 = (($signed(p_read17_int_reg) < $signed(18'd430)) ? 1'b1 : 1'b0);

assign icmp_ln86_750_fu_450_p2 = (($signed(p_read20_int_reg) < $signed(18'd81215)) ? 1'b1 : 1'b0);

assign icmp_ln86_751_fu_456_p2 = (($signed(p_read18_int_reg) < $signed(18'd1031)) ? 1'b1 : 1'b0);

assign icmp_ln86_752_fu_462_p2 = (($signed(p_read4_int_reg) < $signed(18'd19807)) ? 1'b1 : 1'b0);

assign icmp_ln86_753_fu_468_p2 = (($signed(p_read6_int_reg) < $signed(18'd4622)) ? 1'b1 : 1'b0);

assign icmp_ln86_754_fu_474_p2 = (($signed(p_read8_int_reg) < $signed(18'd260319)) ? 1'b1 : 1'b0);

assign icmp_ln86_755_fu_480_p2 = (($signed(p_read17_int_reg) < $signed(18'd973)) ? 1'b1 : 1'b0);

assign icmp_ln86_756_fu_486_p2 = (($signed(p_read13_int_reg) < $signed(18'd13476)) ? 1'b1 : 1'b0);

assign icmp_ln86_757_fu_492_p2 = (($signed(p_read19_int_reg) < $signed(18'd110582)) ? 1'b1 : 1'b0);

assign icmp_ln86_758_fu_498_p2 = (($signed(p_read2_int_reg) < $signed(18'd1179)) ? 1'b1 : 1'b0);

assign icmp_ln86_759_fu_514_p2 = (($signed(tmp_fu_504_p4) < $signed(16'd1)) ? 1'b1 : 1'b0);

assign icmp_ln86_760_fu_520_p2 = (($signed(p_read5_int_reg) < $signed(18'd16721)) ? 1'b1 : 1'b0);

assign icmp_ln86_761_fu_526_p2 = (($signed(p_read15_int_reg) < $signed(18'd2179)) ? 1'b1 : 1'b0);

assign icmp_ln86_762_fu_532_p2 = (($signed(p_read19_int_reg) < $signed(18'd87887)) ? 1'b1 : 1'b0);

assign icmp_ln86_763_fu_538_p2 = (($signed(p_read9_int_reg) < $signed(18'd59)) ? 1'b1 : 1'b0);

assign icmp_ln86_764_fu_544_p2 = (($signed(p_read21_int_reg) < $signed(18'd57857)) ? 1'b1 : 1'b0);

assign icmp_ln86_765_fu_550_p2 = (($signed(p_read3_int_reg) < $signed(18'd83591)) ? 1'b1 : 1'b0);

assign icmp_ln86_766_fu_556_p2 = (($signed(p_read16_int_reg) < $signed(18'd5242)) ? 1'b1 : 1'b0);

assign icmp_ln86_767_fu_562_p2 = (($signed(p_read8_int_reg) < $signed(18'd260450)) ? 1'b1 : 1'b0);

assign icmp_ln86_768_fu_568_p2 = (($signed(p_read1_int_reg) < $signed(18'd12672)) ? 1'b1 : 1'b0);

assign icmp_ln86_769_fu_574_p2 = (($signed(p_read2_int_reg) < $signed(18'd262128)) ? 1'b1 : 1'b0);

assign icmp_ln86_770_fu_580_p2 = (($signed(p_read7_int_reg) < $signed(18'd868)) ? 1'b1 : 1'b0);

assign icmp_ln86_771_fu_586_p2 = (($signed(p_read13_int_reg) < $signed(18'd22539)) ? 1'b1 : 1'b0);

assign icmp_ln86_772_fu_592_p2 = (($signed(p_read5_int_reg) < $signed(18'd21623)) ? 1'b1 : 1'b0);

assign icmp_ln86_773_fu_598_p2 = (($signed(p_read12_int_reg) < $signed(18'd302)) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_408_p2 = (($signed(p_read14_int_reg) < $signed(18'd7996)) ? 1'b1 : 1'b0);

assign or_ln117_651_fu_741_p2 = (and_ln102_931_fu_699_p2 | and_ln102_916_reg_1596);

assign or_ln117_652_fu_753_p2 = (and_ln102_921_reg_1614 | and_ln102_916_reg_1596);

assign or_ln117_653_fu_765_p2 = (or_ln117_652_fu_753_p2 | and_ln102_933_fu_708_p2);

assign or_ln117_654_fu_855_p2 = (and_ln102_reg_1580_pp0_iter2_reg | and_ln102_934_fu_836_p2);

assign or_ln117_655_fu_798_p2 = (and_ln102_reg_1580_pp0_iter1_reg | and_ln102_922_fu_690_p2);

assign or_ln117_656_fu_867_p2 = (or_ln117_655_reg_1653 | and_ln102_936_fu_845_p2);

assign or_ln117_657_fu_879_p2 = (and_ln102_reg_1580_pp0_iter2_reg | and_ln102_917_reg_1631);

assign or_ln117_658_fu_891_p2 = (or_ln117_657_fu_879_p2 | and_ln102_937_fu_850_p2);

assign or_ln117_659_fu_905_p2 = (or_ln117_657_fu_879_p2 | and_ln102_923_fu_827_p2);

assign or_ln117_660_fu_990_p2 = (or_ln117_659_reg_1683 | and_ln102_939_fu_971_p2);

assign or_ln117_661_fu_1006_p2 = (icmp_ln86_reg_1406_pp0_iter3_reg | and_ln102_940_fu_976_p2);

assign or_ln117_662_fu_1018_p2 = (icmp_ln86_reg_1406_pp0_iter3_reg | and_ln102_924_reg_1677);

assign or_ln117_663_fu_1030_p2 = (or_ln117_662_fu_1018_p2 | and_ln102_942_fu_985_p2);

assign or_ln117_664_fu_1044_p2 = (icmp_ln86_reg_1406_pp0_iter3_reg | and_ln102_918_reg_1671);

assign or_ln117_665_fu_1102_p2 = (or_ln117_664_reg_1716 | and_ln102_943_fu_1083_p2);

assign or_ln117_666_fu_1064_p2 = (or_ln117_664_fu_1044_p2 | and_ln102_925_fu_961_p2);

assign or_ln117_667_fu_1114_p2 = (or_ln117_666_reg_1726 | and_ln102_945_fu_1092_p2);

assign or_ln117_668_fu_1070_p2 = (icmp_ln86_reg_1406_pp0_iter3_reg | and_ln102_915_reg_1659);

assign or_ln117_669_fu_1134_p2 = (or_ln117_668_reg_1732 | and_ln102_946_fu_1097_p2);

assign or_ln117_670_fu_1146_p2 = (or_ln117_668_reg_1732 | and_ln102_926_fu_1079_p2);

assign or_ln117_671_fu_1191_p2 = (or_ln117_670_reg_1740 | and_ln102_948_fu_1181_p2);

assign or_ln117_672_fu_1196_p2 = (or_ln117_668_reg_1732_pp0_iter5_reg | and_ln102_919_reg_1698_pp0_iter5_reg);

assign or_ln117_673_fu_1207_p2 = (or_ln117_672_fu_1196_p2 | and_ln102_949_fu_1186_p2);

assign or_ln117_674_fu_1221_p2 = (or_ln117_672_fu_1196_p2 | and_ln102_927_fu_1172_p2);

assign or_ln117_675_fu_1258_p2 = (or_ln117_674_reg_1750 | and_ln102_951_fu_1253_p2);

assign or_ln117_fu_660_p2 = (and_ln102_930_fu_654_p2 | and_ln102_920_fu_634_p2);

assign select_ln117_722_fu_730_p3 = ((or_ln117_reg_1620[0:0] == 1'b1) ? select_ln117_fu_723_p3 : 2'd3);

assign select_ln117_723_fu_746_p3 = ((and_ln102_916_reg_1596[0:0] == 1'b1) ? zext_ln117_79_fu_737_p1 : 3'd4);

assign select_ln117_724_fu_757_p3 = ((or_ln117_651_fu_741_p2[0:0] == 1'b1) ? select_ln117_723_fu_746_p3 : 3'd5);

assign select_ln117_725_fu_771_p3 = ((or_ln117_652_fu_753_p2[0:0] == 1'b1) ? select_ln117_724_fu_757_p3 : 3'd6);

assign select_ln117_726_fu_779_p3 = ((or_ln117_653_fu_765_p2[0:0] == 1'b1) ? select_ln117_725_fu_771_p3 : 3'd7);

assign select_ln117_727_fu_791_p3 = ((and_ln102_reg_1580_pp0_iter1_reg[0:0] == 1'b1) ? zext_ln117_80_fu_787_p1 : 4'd8);

assign select_ln117_728_fu_860_p3 = ((or_ln117_654_fu_855_p2[0:0] == 1'b1) ? select_ln117_727_reg_1648 : 4'd9);

assign select_ln117_729_fu_872_p3 = ((or_ln117_655_reg_1653[0:0] == 1'b1) ? select_ln117_728_fu_860_p3 : 4'd10);

assign select_ln117_730_fu_883_p3 = ((or_ln117_656_fu_867_p2[0:0] == 1'b1) ? select_ln117_729_fu_872_p3 : 4'd11);

assign select_ln117_731_fu_897_p3 = ((or_ln117_657_fu_879_p2[0:0] == 1'b1) ? select_ln117_730_fu_883_p3 : 4'd12);

assign select_ln117_732_fu_911_p3 = ((or_ln117_658_fu_891_p2[0:0] == 1'b1) ? select_ln117_731_fu_897_p3 : 4'd13);

assign select_ln117_733_fu_919_p3 = ((or_ln117_659_fu_905_p2[0:0] == 1'b1) ? select_ln117_732_fu_911_p3 : 4'd14);

assign select_ln117_734_fu_995_p3 = ((or_ln117_660_fu_990_p2[0:0] == 1'b1) ? select_ln117_733_reg_1688 : 4'd15);

assign select_ln117_735_fu_1011_p3 = ((icmp_ln86_reg_1406_pp0_iter3_reg[0:0] == 1'b1) ? zext_ln117_81_fu_1002_p1 : 5'd16);

assign select_ln117_736_fu_1022_p3 = ((or_ln117_661_fu_1006_p2[0:0] == 1'b1) ? select_ln117_735_fu_1011_p3 : 5'd17);

assign select_ln117_737_fu_1036_p3 = ((or_ln117_662_fu_1018_p2[0:0] == 1'b1) ? select_ln117_736_fu_1022_p3 : 5'd18);

assign select_ln117_738_fu_1048_p3 = ((or_ln117_663_fu_1030_p2[0:0] == 1'b1) ? select_ln117_737_fu_1036_p3 : 5'd19);

assign select_ln117_739_fu_1056_p3 = ((or_ln117_664_fu_1044_p2[0:0] == 1'b1) ? select_ln117_738_fu_1048_p3 : 5'd20);

assign select_ln117_740_fu_1107_p3 = ((or_ln117_665_fu_1102_p2[0:0] == 1'b1) ? select_ln117_739_reg_1721 : 5'd21);

assign select_ln117_741_fu_1119_p3 = ((or_ln117_666_reg_1726[0:0] == 1'b1) ? select_ln117_740_fu_1107_p3 : 5'd22);

assign select_ln117_742_fu_1126_p3 = ((or_ln117_667_fu_1114_p2[0:0] == 1'b1) ? select_ln117_741_fu_1119_p3 : 5'd23);

assign select_ln117_743_fu_1139_p3 = ((or_ln117_668_reg_1732[0:0] == 1'b1) ? select_ln117_742_fu_1126_p3 : 5'd24);

assign select_ln117_744_fu_1151_p3 = ((or_ln117_669_fu_1134_p2[0:0] == 1'b1) ? select_ln117_743_fu_1139_p3 : 5'd25);

assign select_ln117_745_fu_1159_p3 = ((or_ln117_670_fu_1146_p2[0:0] == 1'b1) ? select_ln117_744_fu_1151_p3 : 5'd26);

assign select_ln117_746_fu_1200_p3 = ((or_ln117_671_fu_1191_p2[0:0] == 1'b1) ? select_ln117_745_reg_1745 : 5'd27);

assign select_ln117_747_fu_1213_p3 = ((or_ln117_672_fu_1196_p2[0:0] == 1'b1) ? select_ln117_746_fu_1200_p3 : 5'd28);

assign select_ln117_748_fu_1227_p3 = ((or_ln117_673_fu_1207_p2[0:0] == 1'b1) ? select_ln117_747_fu_1213_p3 : 5'd29);

assign select_ln117_749_fu_1235_p3 = ((or_ln117_674_fu_1221_p2[0:0] == 1'b1) ? select_ln117_748_fu_1227_p3 : 5'd30);

assign select_ln117_fu_723_p3 = ((and_ln102_920_reg_1608[0:0] == 1'b1) ? zext_ln117_fu_719_p1 : 2'd2);

assign tmp_fu_504_p4 = {{p_read10_int_reg[17:2]}};

assign xor_ln104_351_fu_610_p2 = (icmp_ln86_744_reg_1417 ^ 1'd1);

assign xor_ln104_352_fu_807_p2 = (icmp_ln86_745_reg_1422_pp0_iter2_reg ^ 1'd1);

assign xor_ln104_353_fu_624_p2 = (icmp_ln86_746_reg_1428 ^ 1'd1);

assign xor_ln104_354_fu_675_p2 = (icmp_ln86_747_reg_1434_pp0_iter1_reg ^ 1'd1);

assign xor_ln104_355_fu_927_p2 = (icmp_ln86_748_reg_1440_pp0_iter3_reg ^ 1'd1);

assign xor_ln104_356_fu_941_p2 = (icmp_ln86_749_reg_1446_pp0_iter3_reg ^ 1'd1);

assign xor_ln104_357_fu_639_p2 = (icmp_ln86_750_reg_1452 ^ 1'd1);

assign xor_ln104_358_fu_685_p2 = (icmp_ln86_751_reg_1458_pp0_iter1_reg ^ 1'd1);

assign xor_ln104_359_fu_822_p2 = (icmp_ln86_752_reg_1464_pp0_iter2_reg ^ 1'd1);

assign xor_ln104_360_fu_951_p2 = (icmp_ln86_753_reg_1470_pp0_iter3_reg ^ 1'd1);

assign xor_ln104_361_fu_956_p2 = (icmp_ln86_754_reg_1476_pp0_iter3_reg ^ 1'd1);

assign xor_ln104_362_fu_1074_p2 = (icmp_ln86_755_reg_1482_pp0_iter4_reg ^ 1'd1);

assign xor_ln104_363_fu_1167_p2 = (icmp_ln86_756_reg_1488_pp0_iter5_reg ^ 1'd1);

assign xor_ln104_364_fu_1243_p2 = (icmp_ln86_757_reg_1494_pp0_iter6_reg ^ 1'd1);

assign xor_ln104_fu_666_p2 = (icmp_ln86_reg_1406_pp0_iter1_reg ^ 1'd1);

assign xor_ln117_fu_713_p2 = (1'd1 ^ and_ln102_928_fu_695_p2);

assign zext_ln117_79_fu_737_p1 = select_ln117_722_fu_730_p3;

assign zext_ln117_80_fu_787_p1 = select_ln117_726_fu_779_p3;

assign zext_ln117_81_fu_1002_p1 = select_ln117_734_fu_995_p3;

assign zext_ln117_fu_719_p1 = xor_ln117_fu_713_p2;

endmodule //conifer_jettag_accelerator_decision_function_73
