// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module conifer_jettag_accelerator_decision_function (
        ap_clk,
        ap_rst,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] p_read1;
input  [17:0] p_read2;
input  [17:0] p_read3;
input  [17:0] p_read4;
input  [17:0] p_read5;
input  [17:0] p_read6;
input  [17:0] p_read7;
input  [17:0] p_read8;
input  [17:0] p_read9;
input  [17:0] p_read10;
input  [17:0] p_read11;
input  [17:0] p_read12;
input  [17:0] p_read13;
input  [17:0] p_read14;
input  [17:0] p_read15;
input  [17:0] p_read16;
input  [17:0] p_read17;
input  [17:0] p_read18;
input  [17:0] p_read19;
input  [17:0] p_read20;
input  [17:0] p_read21;
input  [17:0] p_read22;
output  [11:0] ap_return;
input   ap_ce;

wire   [0:0] icmp_ln86_fu_406_p2;
reg   [0:0] icmp_ln86_reg_1285;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln86_1_fu_412_p2;
reg   [0:0] icmp_ln86_1_reg_1291;
wire   [0:0] icmp_ln86_2_fu_418_p2;
reg   [0:0] icmp_ln86_2_reg_1296;
wire   [0:0] icmp_ln86_3_fu_424_p2;
reg   [0:0] icmp_ln86_3_reg_1302;
wire   [0:0] icmp_ln86_4_fu_430_p2;
reg   [0:0] icmp_ln86_4_reg_1308;
wire   [0:0] icmp_ln86_5_fu_436_p2;
reg   [0:0] icmp_ln86_5_reg_1315;
reg   [0:0] icmp_ln86_5_reg_1315_pp0_iter1_reg;
reg   [0:0] icmp_ln86_5_reg_1315_pp0_iter2_reg;
reg   [0:0] icmp_ln86_5_reg_1315_pp0_iter3_reg;
wire   [0:0] icmp_ln86_6_fu_442_p2;
reg   [0:0] icmp_ln86_6_reg_1321;
reg   [0:0] icmp_ln86_6_reg_1321_pp0_iter1_reg;
wire   [0:0] icmp_ln86_7_fu_448_p2;
reg   [0:0] icmp_ln86_7_reg_1327;
reg   [0:0] icmp_ln86_7_reg_1327_pp0_iter1_reg;
reg   [0:0] icmp_ln86_7_reg_1327_pp0_iter2_reg;
wire   [0:0] icmp_ln86_8_fu_454_p2;
reg   [0:0] icmp_ln86_8_reg_1333;
reg   [0:0] icmp_ln86_8_reg_1333_pp0_iter1_reg;
reg   [0:0] icmp_ln86_8_reg_1333_pp0_iter2_reg;
wire   [0:0] icmp_ln86_9_fu_460_p2;
reg   [0:0] icmp_ln86_9_reg_1339;
wire   [0:0] icmp_ln86_10_fu_466_p2;
reg   [0:0] icmp_ln86_10_reg_1346;
reg   [0:0] icmp_ln86_10_reg_1346_pp0_iter1_reg;
reg   [0:0] icmp_ln86_10_reg_1346_pp0_iter2_reg;
reg   [0:0] icmp_ln86_10_reg_1346_pp0_iter3_reg;
wire   [0:0] icmp_ln86_11_fu_472_p2;
reg   [0:0] icmp_ln86_11_reg_1352;
reg   [0:0] icmp_ln86_11_reg_1352_pp0_iter1_reg;
reg   [0:0] icmp_ln86_11_reg_1352_pp0_iter2_reg;
reg   [0:0] icmp_ln86_11_reg_1352_pp0_iter3_reg;
reg   [0:0] icmp_ln86_11_reg_1352_pp0_iter4_reg;
wire   [0:0] icmp_ln86_12_fu_478_p2;
reg   [0:0] icmp_ln86_12_reg_1358;
reg   [0:0] icmp_ln86_12_reg_1358_pp0_iter1_reg;
reg   [0:0] icmp_ln86_12_reg_1358_pp0_iter2_reg;
reg   [0:0] icmp_ln86_12_reg_1358_pp0_iter3_reg;
reg   [0:0] icmp_ln86_12_reg_1358_pp0_iter4_reg;
reg   [0:0] icmp_ln86_12_reg_1358_pp0_iter5_reg;
wire   [0:0] icmp_ln86_13_fu_484_p2;
reg   [0:0] icmp_ln86_13_reg_1364;
reg   [0:0] icmp_ln86_13_reg_1364_pp0_iter1_reg;
wire   [0:0] icmp_ln86_14_fu_490_p2;
reg   [0:0] icmp_ln86_14_reg_1369;
reg   [0:0] icmp_ln86_14_reg_1369_pp0_iter1_reg;
wire   [0:0] icmp_ln86_15_fu_496_p2;
reg   [0:0] icmp_ln86_15_reg_1374;
reg   [0:0] icmp_ln86_15_reg_1374_pp0_iter1_reg;
wire   [0:0] icmp_ln86_16_fu_502_p2;
reg   [0:0] icmp_ln86_16_reg_1379;
reg   [0:0] icmp_ln86_16_reg_1379_pp0_iter1_reg;
reg   [0:0] icmp_ln86_16_reg_1379_pp0_iter2_reg;
wire   [0:0] icmp_ln86_17_fu_508_p2;
reg   [0:0] icmp_ln86_17_reg_1384;
reg   [0:0] icmp_ln86_17_reg_1384_pp0_iter1_reg;
reg   [0:0] icmp_ln86_17_reg_1384_pp0_iter2_reg;
wire   [0:0] icmp_ln86_18_fu_514_p2;
reg   [0:0] icmp_ln86_18_reg_1389;
reg   [0:0] icmp_ln86_18_reg_1389_pp0_iter1_reg;
reg   [0:0] icmp_ln86_18_reg_1389_pp0_iter2_reg;
wire   [0:0] icmp_ln86_19_fu_520_p2;
reg   [0:0] icmp_ln86_19_reg_1394;
reg   [0:0] icmp_ln86_19_reg_1394_pp0_iter1_reg;
reg   [0:0] icmp_ln86_19_reg_1394_pp0_iter2_reg;
reg   [0:0] icmp_ln86_19_reg_1394_pp0_iter3_reg;
wire   [0:0] icmp_ln86_20_fu_526_p2;
reg   [0:0] icmp_ln86_20_reg_1399;
reg   [0:0] icmp_ln86_20_reg_1399_pp0_iter1_reg;
reg   [0:0] icmp_ln86_20_reg_1399_pp0_iter2_reg;
reg   [0:0] icmp_ln86_20_reg_1399_pp0_iter3_reg;
wire   [0:0] icmp_ln86_21_fu_532_p2;
reg   [0:0] icmp_ln86_21_reg_1404;
reg   [0:0] icmp_ln86_21_reg_1404_pp0_iter1_reg;
reg   [0:0] icmp_ln86_21_reg_1404_pp0_iter2_reg;
reg   [0:0] icmp_ln86_21_reg_1404_pp0_iter3_reg;
wire   [0:0] icmp_ln86_22_fu_538_p2;
reg   [0:0] icmp_ln86_22_reg_1409;
reg   [0:0] icmp_ln86_22_reg_1409_pp0_iter1_reg;
reg   [0:0] icmp_ln86_22_reg_1409_pp0_iter2_reg;
reg   [0:0] icmp_ln86_22_reg_1409_pp0_iter3_reg;
reg   [0:0] icmp_ln86_22_reg_1409_pp0_iter4_reg;
wire   [0:0] icmp_ln86_23_fu_544_p2;
reg   [0:0] icmp_ln86_23_reg_1414;
reg   [0:0] icmp_ln86_23_reg_1414_pp0_iter1_reg;
reg   [0:0] icmp_ln86_23_reg_1414_pp0_iter2_reg;
reg   [0:0] icmp_ln86_23_reg_1414_pp0_iter3_reg;
reg   [0:0] icmp_ln86_23_reg_1414_pp0_iter4_reg;
wire   [0:0] icmp_ln86_24_fu_550_p2;
reg   [0:0] icmp_ln86_24_reg_1419;
reg   [0:0] icmp_ln86_24_reg_1419_pp0_iter1_reg;
reg   [0:0] icmp_ln86_24_reg_1419_pp0_iter2_reg;
reg   [0:0] icmp_ln86_24_reg_1419_pp0_iter3_reg;
reg   [0:0] icmp_ln86_24_reg_1419_pp0_iter4_reg;
wire   [0:0] icmp_ln86_25_fu_556_p2;
reg   [0:0] icmp_ln86_25_reg_1424;
reg   [0:0] icmp_ln86_25_reg_1424_pp0_iter1_reg;
reg   [0:0] icmp_ln86_25_reg_1424_pp0_iter2_reg;
reg   [0:0] icmp_ln86_25_reg_1424_pp0_iter3_reg;
reg   [0:0] icmp_ln86_25_reg_1424_pp0_iter4_reg;
reg   [0:0] icmp_ln86_25_reg_1424_pp0_iter5_reg;
wire   [0:0] and_ln102_fu_562_p2;
reg   [0:0] and_ln102_reg_1429;
reg   [0:0] and_ln102_reg_1429_pp0_iter1_reg;
wire   [0:0] and_ln104_fu_574_p2;
reg   [0:0] and_ln104_reg_1436;
wire   [0:0] and_ln102_1_fu_585_p2;
reg   [0:0] and_ln102_1_reg_1442;
reg   [0:0] and_ln102_1_reg_1442_pp0_iter2_reg;
reg   [0:0] and_ln102_1_reg_1442_pp0_iter3_reg;
wire   [0:0] and_ln102_2_fu_590_p2;
reg   [0:0] and_ln102_2_reg_1449;
wire   [0:0] and_ln104_1_fu_599_p2;
reg   [0:0] and_ln104_1_reg_1455;
reg   [0:0] and_ln104_1_reg_1455_pp0_iter2_reg;
wire   [0:0] and_ln102_3_fu_604_p2;
reg   [0:0] and_ln102_3_reg_1461;
reg   [0:0] and_ln102_3_reg_1461_pp0_iter2_reg;
wire   [0:0] xor_ln104_5_fu_622_p2;
reg   [0:0] xor_ln104_5_reg_1468;
reg   [0:0] xor_ln104_5_reg_1468_pp0_iter2_reg;
reg   [0:0] xor_ln104_5_reg_1468_pp0_iter3_reg;
reg   [0:0] xor_ln104_5_reg_1468_pp0_iter4_reg;
reg   [0:0] xor_ln104_5_reg_1468_pp0_iter5_reg;
reg   [0:0] xor_ln104_5_reg_1468_pp0_iter6_reg;
wire   [0:0] and_ln102_5_fu_628_p2;
reg   [0:0] and_ln102_5_reg_1475;
wire   [0:0] and_ln102_8_fu_633_p2;
reg   [0:0] and_ln102_8_reg_1480;
reg   [0:0] and_ln102_8_reg_1480_pp0_iter2_reg;
reg   [0:0] and_ln102_8_reg_1480_pp0_iter3_reg;
wire   [0:0] and_ln104_4_fu_643_p2;
reg   [0:0] and_ln104_4_reg_1486;
wire   [2:0] select_ln117_fu_664_p3;
reg   [2:0] select_ln117_reg_1493;
wire   [0:0] or_ln117_1_fu_672_p2;
reg   [0:0] or_ln117_1_reg_1498;
wire   [0:0] and_ln102_7_fu_687_p2;
reg   [0:0] and_ln102_7_reg_1504;
wire   [0:0] or_ln117_5_fu_764_p2;
reg   [0:0] or_ln117_5_reg_1510;
wire   [3:0] select_ln117_6_fu_778_p3;
reg   [3:0] select_ln117_6_reg_1515;
wire   [0:0] or_ln117_7_fu_786_p2;
reg   [0:0] or_ln117_7_reg_1520;
wire   [0:0] and_ln102_4_fu_790_p2;
reg   [0:0] and_ln102_4_reg_1528;
wire   [0:0] and_ln102_9_fu_804_p2;
reg   [0:0] and_ln102_9_reg_1534;
wire   [0:0] or_ln117_11_fu_883_p2;
reg   [0:0] or_ln117_11_reg_1540;
wire   [3:0] select_ln117_12_fu_895_p3;
reg   [3:0] select_ln117_12_reg_1545;
wire   [0:0] or_ln117_13_fu_903_p2;
reg   [0:0] or_ln117_13_reg_1550;
wire   [0:0] and_ln104_3_fu_913_p2;
reg   [0:0] and_ln104_3_reg_1559;
wire   [0:0] and_ln102_10_fu_923_p2;
reg   [0:0] and_ln102_10_reg_1564;
wire   [0:0] or_ln117_17_fu_1000_p2;
reg   [0:0] or_ln117_17_reg_1569;
wire   [4:0] select_ln117_18_fu_1012_p3;
reg   [4:0] select_ln117_18_reg_1574;
wire   [0:0] or_ln117_19_fu_1020_p2;
reg   [0:0] or_ln117_19_reg_1579;
wire   [0:0] or_ln117_21_fu_1026_p2;
reg   [0:0] or_ln117_21_reg_1585;
reg   [0:0] or_ln117_21_reg_1585_pp0_iter5_reg;
reg   [0:0] or_ln117_21_reg_1585_pp0_iter6_reg;
wire   [0:0] or_ln117_23_fu_1102_p2;
reg   [0:0] or_ln117_23_reg_1593;
wire   [4:0] select_ln117_24_fu_1115_p3;
reg   [4:0] select_ln117_24_reg_1598;
wire   [11:0] tmp_fu_1150_p61;
reg   [11:0] tmp_reg_1603;
wire    ap_block_pp0_stage0;
wire   [12:0] tmp_39_fu_396_p4;
wire   [0:0] xor_ln104_1_fu_568_p2;
wire   [0:0] xor_ln104_fu_580_p2;
wire   [0:0] xor_ln104_2_fu_594_p2;
wire   [0:0] xor_ln104_3_fu_608_p2;
wire   [0:0] or_ln104_fu_618_p2;
wire   [0:0] and_ln104_2_fu_613_p2;
wire   [0:0] xor_ln104_9_fu_638_p2;
wire   [0:0] or_ln117_26_fu_649_p2;
wire   [0:0] or_ln117_27_fu_654_p2;
wire   [0:0] or_ln117_1849_fu_659_p2;
wire   [0:0] xor_ln104_6_fu_678_p2;
wire   [0:0] and_ln102_25_fu_695_p2;
wire   [0:0] and_ln102_6_fu_683_p2;
wire   [0:0] and_ln102_12_fu_691_p2;
wire   [0:0] or_ln117_fu_710_p2;
wire   [0:0] and_ln102_13_fu_700_p2;
wire   [2:0] select_ln117_1_fu_715_p3;
wire   [0:0] or_ln117_2_fu_722_p2;
wire   [2:0] select_ln117_2_fu_727_p3;
wire   [0:0] or_ln117_3_fu_734_p2;
wire   [0:0] and_ln102_14_fu_705_p2;
wire   [2:0] select_ln117_3_fu_738_p3;
wire   [2:0] select_ln117_4_fu_752_p3;
wire   [0:0] or_ln117_4_fu_746_p2;
wire   [3:0] zext_ln117_fu_760_p1;
wire   [3:0] select_ln117_5_fu_770_p3;
wire   [0:0] xor_ln104_7_fu_794_p2;
wire   [0:0] and_ln102_26_fu_809_p2;
wire   [0:0] xor_ln104_8_fu_799_p2;
wire   [0:0] and_ln102_27_fu_823_p2;
wire   [0:0] and_ln102_15_fu_814_p2;
wire   [0:0] or_ln117_6_fu_833_p2;
wire   [0:0] and_ln102_16_fu_819_p2;
wire   [3:0] select_ln117_7_fu_838_p3;
wire   [0:0] or_ln117_8_fu_845_p2;
wire   [3:0] select_ln117_8_fu_850_p3;
wire   [0:0] or_ln117_9_fu_857_p2;
wire   [0:0] and_ln102_17_fu_828_p2;
wire   [3:0] select_ln117_9_fu_861_p3;
wire   [0:0] or_ln117_10_fu_869_p2;
wire   [3:0] select_ln117_10_fu_875_p3;
wire   [3:0] select_ln117_11_fu_887_p3;
wire   [0:0] xor_ln104_4_fu_908_p2;
wire   [0:0] xor_ln104_10_fu_918_p2;
wire   [0:0] and_ln102_28_fu_936_p2;
wire   [0:0] and_ln102_18_fu_928_p2;
wire   [0:0] or_ln117_12_fu_946_p2;
wire   [4:0] zext_ln117_1_fu_951_p1;
wire   [0:0] and_ln102_19_fu_932_p2;
wire   [4:0] select_ln117_13_fu_954_p3;
wire   [0:0] or_ln117_14_fu_962_p2;
wire   [4:0] select_ln117_14_fu_967_p3;
wire   [0:0] or_ln117_15_fu_974_p2;
wire   [0:0] and_ln102_20_fu_941_p2;
wire   [4:0] select_ln117_15_fu_978_p3;
wire   [0:0] or_ln117_16_fu_986_p2;
wire   [4:0] select_ln117_16_fu_992_p3;
wire   [4:0] select_ln117_17_fu_1004_p3;
wire   [0:0] xor_ln104_11_fu_1030_p2;
wire   [0:0] and_ln102_29_fu_1043_p2;
wire   [0:0] and_ln102_11_fu_1035_p2;
wire   [0:0] and_ln102_21_fu_1039_p2;
wire   [0:0] or_ln117_18_fu_1058_p2;
wire   [0:0] and_ln102_22_fu_1048_p2;
wire   [4:0] select_ln117_19_fu_1063_p3;
wire   [0:0] or_ln117_20_fu_1070_p2;
wire   [4:0] select_ln117_20_fu_1075_p3;
wire   [0:0] and_ln102_23_fu_1053_p2;
wire   [4:0] select_ln117_21_fu_1082_p3;
wire   [0:0] or_ln117_22_fu_1090_p2;
wire   [4:0] select_ln117_22_fu_1095_p3;
wire   [4:0] select_ln117_23_fu_1107_p3;
wire   [0:0] xor_ln104_12_fu_1123_p2;
wire   [0:0] and_ln102_30_fu_1128_p2;
wire   [0:0] and_ln102_24_fu_1133_p2;
wire   [0:0] or_ln117_24_fu_1138_p2;
wire   [11:0] tmp_fu_1150_p59;
wire   [4:0] tmp_fu_1150_p60;
wire   [0:0] or_ln117_25_fu_1274_p2;
reg   [17:0] p_read1_int_reg;
reg   [17:0] p_read2_int_reg;
reg   [17:0] p_read3_int_reg;
reg   [17:0] p_read4_int_reg;
reg   [17:0] p_read5_int_reg;
reg   [17:0] p_read6_int_reg;
reg   [17:0] p_read7_int_reg;
reg   [17:0] p_read8_int_reg;
reg   [17:0] p_read9_int_reg;
reg   [17:0] p_read10_int_reg;
reg   [17:0] p_read11_int_reg;
reg   [17:0] p_read12_int_reg;
reg   [17:0] p_read13_int_reg;
reg   [17:0] p_read14_int_reg;
reg   [17:0] p_read15_int_reg;
reg   [17:0] p_read16_int_reg;
reg   [17:0] p_read17_int_reg;
reg   [17:0] p_read18_int_reg;
reg   [17:0] p_read19_int_reg;
reg   [17:0] p_read20_int_reg;
reg   [17:0] p_read21_int_reg;
reg   [17:0] p_read22_int_reg;
wire   [4:0] tmp_fu_1150_p1;
wire   [4:0] tmp_fu_1150_p3;
wire   [4:0] tmp_fu_1150_p5;
wire   [4:0] tmp_fu_1150_p7;
wire   [4:0] tmp_fu_1150_p9;
wire   [4:0] tmp_fu_1150_p11;
wire   [4:0] tmp_fu_1150_p13;
wire   [4:0] tmp_fu_1150_p15;
wire   [4:0] tmp_fu_1150_p17;
wire   [4:0] tmp_fu_1150_p19;
wire   [4:0] tmp_fu_1150_p21;
wire   [4:0] tmp_fu_1150_p23;
wire   [4:0] tmp_fu_1150_p25;
wire   [4:0] tmp_fu_1150_p27;
wire   [4:0] tmp_fu_1150_p29;
wire   [4:0] tmp_fu_1150_p31;
wire  signed [4:0] tmp_fu_1150_p33;
wire  signed [4:0] tmp_fu_1150_p35;
wire  signed [4:0] tmp_fu_1150_p37;
wire  signed [4:0] tmp_fu_1150_p39;
wire  signed [4:0] tmp_fu_1150_p41;
wire  signed [4:0] tmp_fu_1150_p43;
wire  signed [4:0] tmp_fu_1150_p45;
wire  signed [4:0] tmp_fu_1150_p47;
wire  signed [4:0] tmp_fu_1150_p49;
wire  signed [4:0] tmp_fu_1150_p51;
wire  signed [4:0] tmp_fu_1150_p53;
wire  signed [4:0] tmp_fu_1150_p55;
wire  signed [4:0] tmp_fu_1150_p57;
wire    ap_ce_reg;

(* dissolve_hierarchy = "yes" *) conifer_jettag_accelerator_sparsemux_59_5_12_1_1_x0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 12 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 12 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 12 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 12 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 12 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 12 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 12 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 12 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 12 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 12 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 12 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 12 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 12 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 12 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 12 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 12 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 12 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 12 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 12 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 12 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 12 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 12 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 12 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 12 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 12 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 12 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 12 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 12 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 12 ),
    .def_WIDTH( 12 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 12 ))
sparsemux_59_5_12_1_1_x0_U2257(
    .din0(12'd3149),
    .din1(12'd3954),
    .din2(12'd2467),
    .din3(12'd4089),
    .din4(12'd3481),
    .din5(12'd84),
    .din6(12'd4045),
    .din7(12'd3899),
    .din8(12'd425),
    .din9(12'd544),
    .din10(12'd3425),
    .din11(12'd306),
    .din12(12'd3436),
    .din13(12'd403),
    .din14(12'd3911),
    .din15(12'd292),
    .din16(12'd103),
    .din17(12'd3631),
    .din18(12'd2997),
    .din19(12'd412),
    .din20(12'd3325),
    .din21(12'd4002),
    .din22(12'd3387),
    .din23(12'd27),
    .din24(12'd3663),
    .din25(12'd4006),
    .din26(12'd3380),
    .din27(12'd3906),
    .din28(12'd19),
    .def(tmp_fu_1150_p59),
    .sel(tmp_fu_1150_p60),
    .dout(tmp_fu_1150_p61)
);

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        and_ln102_10_reg_1564 <= and_ln102_10_fu_923_p2;
        and_ln102_1_reg_1442 <= and_ln102_1_fu_585_p2;
        and_ln102_1_reg_1442_pp0_iter2_reg <= and_ln102_1_reg_1442;
        and_ln102_1_reg_1442_pp0_iter3_reg <= and_ln102_1_reg_1442_pp0_iter2_reg;
        and_ln102_2_reg_1449 <= and_ln102_2_fu_590_p2;
        and_ln102_3_reg_1461 <= and_ln102_3_fu_604_p2;
        and_ln102_3_reg_1461_pp0_iter2_reg <= and_ln102_3_reg_1461;
        and_ln102_4_reg_1528 <= and_ln102_4_fu_790_p2;
        and_ln102_5_reg_1475 <= and_ln102_5_fu_628_p2;
        and_ln102_7_reg_1504 <= and_ln102_7_fu_687_p2;
        and_ln102_8_reg_1480 <= and_ln102_8_fu_633_p2;
        and_ln102_8_reg_1480_pp0_iter2_reg <= and_ln102_8_reg_1480;
        and_ln102_8_reg_1480_pp0_iter3_reg <= and_ln102_8_reg_1480_pp0_iter2_reg;
        and_ln102_9_reg_1534 <= and_ln102_9_fu_804_p2;
        and_ln102_reg_1429 <= and_ln102_fu_562_p2;
        and_ln102_reg_1429_pp0_iter1_reg <= and_ln102_reg_1429;
        and_ln104_1_reg_1455 <= and_ln104_1_fu_599_p2;
        and_ln104_1_reg_1455_pp0_iter2_reg <= and_ln104_1_reg_1455;
        and_ln104_3_reg_1559 <= and_ln104_3_fu_913_p2;
        and_ln104_4_reg_1486 <= and_ln104_4_fu_643_p2;
        and_ln104_reg_1436 <= and_ln104_fu_574_p2;
        icmp_ln86_10_reg_1346 <= icmp_ln86_10_fu_466_p2;
        icmp_ln86_10_reg_1346_pp0_iter1_reg <= icmp_ln86_10_reg_1346;
        icmp_ln86_10_reg_1346_pp0_iter2_reg <= icmp_ln86_10_reg_1346_pp0_iter1_reg;
        icmp_ln86_10_reg_1346_pp0_iter3_reg <= icmp_ln86_10_reg_1346_pp0_iter2_reg;
        icmp_ln86_11_reg_1352 <= icmp_ln86_11_fu_472_p2;
        icmp_ln86_11_reg_1352_pp0_iter1_reg <= icmp_ln86_11_reg_1352;
        icmp_ln86_11_reg_1352_pp0_iter2_reg <= icmp_ln86_11_reg_1352_pp0_iter1_reg;
        icmp_ln86_11_reg_1352_pp0_iter3_reg <= icmp_ln86_11_reg_1352_pp0_iter2_reg;
        icmp_ln86_11_reg_1352_pp0_iter4_reg <= icmp_ln86_11_reg_1352_pp0_iter3_reg;
        icmp_ln86_12_reg_1358 <= icmp_ln86_12_fu_478_p2;
        icmp_ln86_12_reg_1358_pp0_iter1_reg <= icmp_ln86_12_reg_1358;
        icmp_ln86_12_reg_1358_pp0_iter2_reg <= icmp_ln86_12_reg_1358_pp0_iter1_reg;
        icmp_ln86_12_reg_1358_pp0_iter3_reg <= icmp_ln86_12_reg_1358_pp0_iter2_reg;
        icmp_ln86_12_reg_1358_pp0_iter4_reg <= icmp_ln86_12_reg_1358_pp0_iter3_reg;
        icmp_ln86_12_reg_1358_pp0_iter5_reg <= icmp_ln86_12_reg_1358_pp0_iter4_reg;
        icmp_ln86_13_reg_1364 <= icmp_ln86_13_fu_484_p2;
        icmp_ln86_13_reg_1364_pp0_iter1_reg <= icmp_ln86_13_reg_1364;
        icmp_ln86_14_reg_1369 <= icmp_ln86_14_fu_490_p2;
        icmp_ln86_14_reg_1369_pp0_iter1_reg <= icmp_ln86_14_reg_1369;
        icmp_ln86_15_reg_1374 <= icmp_ln86_15_fu_496_p2;
        icmp_ln86_15_reg_1374_pp0_iter1_reg <= icmp_ln86_15_reg_1374;
        icmp_ln86_16_reg_1379 <= icmp_ln86_16_fu_502_p2;
        icmp_ln86_16_reg_1379_pp0_iter1_reg <= icmp_ln86_16_reg_1379;
        icmp_ln86_16_reg_1379_pp0_iter2_reg <= icmp_ln86_16_reg_1379_pp0_iter1_reg;
        icmp_ln86_17_reg_1384 <= icmp_ln86_17_fu_508_p2;
        icmp_ln86_17_reg_1384_pp0_iter1_reg <= icmp_ln86_17_reg_1384;
        icmp_ln86_17_reg_1384_pp0_iter2_reg <= icmp_ln86_17_reg_1384_pp0_iter1_reg;
        icmp_ln86_18_reg_1389 <= icmp_ln86_18_fu_514_p2;
        icmp_ln86_18_reg_1389_pp0_iter1_reg <= icmp_ln86_18_reg_1389;
        icmp_ln86_18_reg_1389_pp0_iter2_reg <= icmp_ln86_18_reg_1389_pp0_iter1_reg;
        icmp_ln86_19_reg_1394 <= icmp_ln86_19_fu_520_p2;
        icmp_ln86_19_reg_1394_pp0_iter1_reg <= icmp_ln86_19_reg_1394;
        icmp_ln86_19_reg_1394_pp0_iter2_reg <= icmp_ln86_19_reg_1394_pp0_iter1_reg;
        icmp_ln86_19_reg_1394_pp0_iter3_reg <= icmp_ln86_19_reg_1394_pp0_iter2_reg;
        icmp_ln86_1_reg_1291 <= icmp_ln86_1_fu_412_p2;
        icmp_ln86_20_reg_1399 <= icmp_ln86_20_fu_526_p2;
        icmp_ln86_20_reg_1399_pp0_iter1_reg <= icmp_ln86_20_reg_1399;
        icmp_ln86_20_reg_1399_pp0_iter2_reg <= icmp_ln86_20_reg_1399_pp0_iter1_reg;
        icmp_ln86_20_reg_1399_pp0_iter3_reg <= icmp_ln86_20_reg_1399_pp0_iter2_reg;
        icmp_ln86_21_reg_1404 <= icmp_ln86_21_fu_532_p2;
        icmp_ln86_21_reg_1404_pp0_iter1_reg <= icmp_ln86_21_reg_1404;
        icmp_ln86_21_reg_1404_pp0_iter2_reg <= icmp_ln86_21_reg_1404_pp0_iter1_reg;
        icmp_ln86_21_reg_1404_pp0_iter3_reg <= icmp_ln86_21_reg_1404_pp0_iter2_reg;
        icmp_ln86_22_reg_1409 <= icmp_ln86_22_fu_538_p2;
        icmp_ln86_22_reg_1409_pp0_iter1_reg <= icmp_ln86_22_reg_1409;
        icmp_ln86_22_reg_1409_pp0_iter2_reg <= icmp_ln86_22_reg_1409_pp0_iter1_reg;
        icmp_ln86_22_reg_1409_pp0_iter3_reg <= icmp_ln86_22_reg_1409_pp0_iter2_reg;
        icmp_ln86_22_reg_1409_pp0_iter4_reg <= icmp_ln86_22_reg_1409_pp0_iter3_reg;
        icmp_ln86_23_reg_1414 <= icmp_ln86_23_fu_544_p2;
        icmp_ln86_23_reg_1414_pp0_iter1_reg <= icmp_ln86_23_reg_1414;
        icmp_ln86_23_reg_1414_pp0_iter2_reg <= icmp_ln86_23_reg_1414_pp0_iter1_reg;
        icmp_ln86_23_reg_1414_pp0_iter3_reg <= icmp_ln86_23_reg_1414_pp0_iter2_reg;
        icmp_ln86_23_reg_1414_pp0_iter4_reg <= icmp_ln86_23_reg_1414_pp0_iter3_reg;
        icmp_ln86_24_reg_1419 <= icmp_ln86_24_fu_550_p2;
        icmp_ln86_24_reg_1419_pp0_iter1_reg <= icmp_ln86_24_reg_1419;
        icmp_ln86_24_reg_1419_pp0_iter2_reg <= icmp_ln86_24_reg_1419_pp0_iter1_reg;
        icmp_ln86_24_reg_1419_pp0_iter3_reg <= icmp_ln86_24_reg_1419_pp0_iter2_reg;
        icmp_ln86_24_reg_1419_pp0_iter4_reg <= icmp_ln86_24_reg_1419_pp0_iter3_reg;
        icmp_ln86_25_reg_1424 <= icmp_ln86_25_fu_556_p2;
        icmp_ln86_25_reg_1424_pp0_iter1_reg <= icmp_ln86_25_reg_1424;
        icmp_ln86_25_reg_1424_pp0_iter2_reg <= icmp_ln86_25_reg_1424_pp0_iter1_reg;
        icmp_ln86_25_reg_1424_pp0_iter3_reg <= icmp_ln86_25_reg_1424_pp0_iter2_reg;
        icmp_ln86_25_reg_1424_pp0_iter4_reg <= icmp_ln86_25_reg_1424_pp0_iter3_reg;
        icmp_ln86_25_reg_1424_pp0_iter5_reg <= icmp_ln86_25_reg_1424_pp0_iter4_reg;
        icmp_ln86_2_reg_1296 <= icmp_ln86_2_fu_418_p2;
        icmp_ln86_3_reg_1302 <= icmp_ln86_3_fu_424_p2;
        icmp_ln86_4_reg_1308 <= icmp_ln86_4_fu_430_p2;
        icmp_ln86_5_reg_1315 <= icmp_ln86_5_fu_436_p2;
        icmp_ln86_5_reg_1315_pp0_iter1_reg <= icmp_ln86_5_reg_1315;
        icmp_ln86_5_reg_1315_pp0_iter2_reg <= icmp_ln86_5_reg_1315_pp0_iter1_reg;
        icmp_ln86_5_reg_1315_pp0_iter3_reg <= icmp_ln86_5_reg_1315_pp0_iter2_reg;
        icmp_ln86_6_reg_1321 <= icmp_ln86_6_fu_442_p2;
        icmp_ln86_6_reg_1321_pp0_iter1_reg <= icmp_ln86_6_reg_1321;
        icmp_ln86_7_reg_1327 <= icmp_ln86_7_fu_448_p2;
        icmp_ln86_7_reg_1327_pp0_iter1_reg <= icmp_ln86_7_reg_1327;
        icmp_ln86_7_reg_1327_pp0_iter2_reg <= icmp_ln86_7_reg_1327_pp0_iter1_reg;
        icmp_ln86_8_reg_1333 <= icmp_ln86_8_fu_454_p2;
        icmp_ln86_8_reg_1333_pp0_iter1_reg <= icmp_ln86_8_reg_1333;
        icmp_ln86_8_reg_1333_pp0_iter2_reg <= icmp_ln86_8_reg_1333_pp0_iter1_reg;
        icmp_ln86_9_reg_1339 <= icmp_ln86_9_fu_460_p2;
        icmp_ln86_reg_1285 <= icmp_ln86_fu_406_p2;
        or_ln117_11_reg_1540 <= or_ln117_11_fu_883_p2;
        or_ln117_13_reg_1550 <= or_ln117_13_fu_903_p2;
        or_ln117_17_reg_1569 <= or_ln117_17_fu_1000_p2;
        or_ln117_19_reg_1579 <= or_ln117_19_fu_1020_p2;
        or_ln117_1_reg_1498 <= or_ln117_1_fu_672_p2;
        or_ln117_21_reg_1585 <= or_ln117_21_fu_1026_p2;
        or_ln117_21_reg_1585_pp0_iter5_reg <= or_ln117_21_reg_1585;
        or_ln117_21_reg_1585_pp0_iter6_reg <= or_ln117_21_reg_1585_pp0_iter5_reg;
        or_ln117_23_reg_1593 <= or_ln117_23_fu_1102_p2;
        or_ln117_5_reg_1510 <= or_ln117_5_fu_764_p2;
        or_ln117_7_reg_1520 <= or_ln117_7_fu_786_p2;
        select_ln117_12_reg_1545 <= select_ln117_12_fu_895_p3;
        select_ln117_18_reg_1574 <= select_ln117_18_fu_1012_p3;
        select_ln117_24_reg_1598 <= select_ln117_24_fu_1115_p3;
        select_ln117_6_reg_1515 <= select_ln117_6_fu_778_p3;
        select_ln117_reg_1493[1 : 0] <= select_ln117_fu_664_p3[1 : 0];
        tmp_reg_1603 <= tmp_fu_1150_p61;
        xor_ln104_5_reg_1468 <= xor_ln104_5_fu_622_p2;
        xor_ln104_5_reg_1468_pp0_iter2_reg <= xor_ln104_5_reg_1468;
        xor_ln104_5_reg_1468_pp0_iter3_reg <= xor_ln104_5_reg_1468_pp0_iter2_reg;
        xor_ln104_5_reg_1468_pp0_iter4_reg <= xor_ln104_5_reg_1468_pp0_iter3_reg;
        xor_ln104_5_reg_1468_pp0_iter5_reg <= xor_ln104_5_reg_1468_pp0_iter4_reg;
        xor_ln104_5_reg_1468_pp0_iter6_reg <= xor_ln104_5_reg_1468_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read10_int_reg <= p_read10;
        p_read11_int_reg <= p_read11;
        p_read12_int_reg <= p_read12;
        p_read13_int_reg <= p_read13;
        p_read14_int_reg <= p_read14;
        p_read15_int_reg <= p_read15;
        p_read16_int_reg <= p_read16;
        p_read17_int_reg <= p_read17;
        p_read18_int_reg <= p_read18;
        p_read19_int_reg <= p_read19;
        p_read1_int_reg <= p_read1;
        p_read20_int_reg <= p_read20;
        p_read21_int_reg <= p_read21;
        p_read22_int_reg <= p_read22;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read9_int_reg <= p_read9;
    end
end

assign and_ln102_10_fu_923_p2 = (icmp_ln86_11_reg_1352_pp0_iter3_reg & and_ln104_3_fu_913_p2);

assign and_ln102_11_fu_1035_p2 = (xor_ln104_5_reg_1468_pp0_iter4_reg & icmp_ln86_12_reg_1358_pp0_iter4_reg);

assign and_ln102_12_fu_691_p2 = (icmp_ln86_13_reg_1364_pp0_iter1_reg & and_ln102_5_reg_1475);

assign and_ln102_13_fu_700_p2 = (and_ln102_2_reg_1449 & and_ln102_25_fu_695_p2);

assign and_ln102_14_fu_705_p2 = (icmp_ln86_15_reg_1374_pp0_iter1_reg & and_ln102_6_fu_683_p2);

assign and_ln102_15_fu_814_p2 = (and_ln104_1_reg_1455_pp0_iter2_reg & and_ln102_26_fu_809_p2);

assign and_ln102_16_fu_819_p2 = (icmp_ln86_17_reg_1384_pp0_iter2_reg & and_ln102_7_reg_1504);

assign and_ln102_17_fu_828_p2 = (and_ln102_3_reg_1461_pp0_iter2_reg & and_ln102_27_fu_823_p2);

assign and_ln102_18_fu_928_p2 = (icmp_ln86_19_reg_1394_pp0_iter3_reg & and_ln102_8_reg_1480_pp0_iter3_reg);

assign and_ln102_19_fu_932_p2 = (icmp_ln86_20_reg_1399_pp0_iter3_reg & and_ln102_9_reg_1534);

assign and_ln102_1_fu_585_p2 = (xor_ln104_fu_580_p2 & icmp_ln86_2_reg_1296);

assign and_ln102_20_fu_941_p2 = (and_ln102_4_reg_1528 & and_ln102_28_fu_936_p2);

assign and_ln102_21_fu_1039_p2 = (icmp_ln86_22_reg_1409_pp0_iter4_reg & and_ln102_10_reg_1564);

assign and_ln102_22_fu_1048_p2 = (and_ln104_3_reg_1559 & and_ln102_29_fu_1043_p2);

assign and_ln102_23_fu_1053_p2 = (icmp_ln86_24_reg_1419_pp0_iter4_reg & and_ln102_11_fu_1035_p2);

assign and_ln102_24_fu_1133_p2 = (xor_ln104_5_reg_1468_pp0_iter5_reg & and_ln102_30_fu_1128_p2);

assign and_ln102_25_fu_695_p2 = (xor_ln104_6_fu_678_p2 & icmp_ln86_14_reg_1369_pp0_iter1_reg);

assign and_ln102_26_fu_809_p2 = (xor_ln104_7_fu_794_p2 & icmp_ln86_16_reg_1379_pp0_iter2_reg);

assign and_ln102_27_fu_823_p2 = (xor_ln104_8_fu_799_p2 & icmp_ln86_18_reg_1389_pp0_iter2_reg);

assign and_ln102_28_fu_936_p2 = (xor_ln104_10_fu_918_p2 & icmp_ln86_21_reg_1404_pp0_iter3_reg);

assign and_ln102_29_fu_1043_p2 = (xor_ln104_11_fu_1030_p2 & icmp_ln86_23_reg_1414_pp0_iter4_reg);

assign and_ln102_2_fu_590_p2 = (icmp_ln86_3_reg_1302 & and_ln102_reg_1429);

assign and_ln102_30_fu_1128_p2 = (xor_ln104_12_fu_1123_p2 & icmp_ln86_25_reg_1424_pp0_iter5_reg);

assign and_ln102_3_fu_604_p2 = (icmp_ln86_4_reg_1308 & and_ln104_reg_1436);

assign and_ln102_4_fu_790_p2 = (icmp_ln86_5_reg_1315_pp0_iter2_reg & and_ln102_1_reg_1442_pp0_iter2_reg);

assign and_ln102_5_fu_628_p2 = (icmp_ln86_6_reg_1321 & and_ln102_2_fu_590_p2);

assign and_ln102_6_fu_683_p2 = (icmp_ln86_7_reg_1327_pp0_iter1_reg & and_ln104_1_reg_1455);

assign and_ln102_7_fu_687_p2 = (icmp_ln86_8_reg_1333_pp0_iter1_reg & and_ln102_3_reg_1461);

assign and_ln102_8_fu_633_p2 = (icmp_ln86_9_reg_1339 & and_ln104_2_fu_613_p2);

assign and_ln102_9_fu_804_p2 = (icmp_ln86_10_reg_1346_pp0_iter2_reg & and_ln102_4_fu_790_p2);

assign and_ln102_fu_562_p2 = (icmp_ln86_fu_406_p2 & icmp_ln86_1_fu_412_p2);

assign and_ln104_1_fu_599_p2 = (xor_ln104_2_fu_594_p2 & and_ln102_reg_1429);

assign and_ln104_2_fu_613_p2 = (xor_ln104_3_fu_608_p2 & and_ln104_reg_1436);

assign and_ln104_3_fu_913_p2 = (xor_ln104_4_fu_908_p2 & and_ln102_1_reg_1442_pp0_iter3_reg);

assign and_ln104_4_fu_643_p2 = (xor_ln104_9_fu_638_p2 & and_ln104_2_fu_613_p2);

assign and_ln104_fu_574_p2 = (xor_ln104_1_fu_568_p2 & icmp_ln86_fu_406_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_return = ((or_ln117_25_fu_1274_p2[0:0] == 1'b1) ? tmp_reg_1603 : 12'd0);

assign icmp_ln86_10_fu_466_p2 = (($signed(p_read12_int_reg) < $signed(18'd179)) ? 1'b1 : 1'b0);

assign icmp_ln86_11_fu_472_p2 = (($signed(p_read17_int_reg) < $signed(18'd96)) ? 1'b1 : 1'b0);

assign icmp_ln86_12_fu_478_p2 = (($signed(p_read11_int_reg) < $signed(18'd78)) ? 1'b1 : 1'b0);

assign icmp_ln86_13_fu_484_p2 = (($signed(p_read21_int_reg) < $signed(18'd194588)) ? 1'b1 : 1'b0);

assign icmp_ln86_14_fu_490_p2 = (($signed(p_read13_int_reg) < $signed(18'd48510)) ? 1'b1 : 1'b0);

assign icmp_ln86_15_fu_496_p2 = (($signed(p_read18_int_reg) < $signed(18'd31)) ? 1'b1 : 1'b0);

assign icmp_ln86_16_fu_502_p2 = (($signed(p_read20_int_reg) < $signed(18'd7)) ? 1'b1 : 1'b0);

assign icmp_ln86_17_fu_508_p2 = (($signed(p_read8_int_reg) < $signed(18'd476)) ? 1'b1 : 1'b0);

assign icmp_ln86_18_fu_514_p2 = (($signed(p_read22_int_reg) < $signed(18'd83457)) ? 1'b1 : 1'b0);

assign icmp_ln86_19_fu_520_p2 = (($signed(p_read3_int_reg) < $signed(18'd24167)) ? 1'b1 : 1'b0);

assign icmp_ln86_1_fu_412_p2 = (($signed(p_read17_int_reg) < $signed(18'd94)) ? 1'b1 : 1'b0);

assign icmp_ln86_20_fu_526_p2 = (($signed(p_read19_int_reg) < $signed(18'd1242)) ? 1'b1 : 1'b0);

assign icmp_ln86_21_fu_532_p2 = (($signed(p_read8_int_reg) < $signed(18'd491)) ? 1'b1 : 1'b0);

assign icmp_ln86_22_fu_538_p2 = (($signed(p_read16_int_reg) < $signed(18'd656)) ? 1'b1 : 1'b0);

assign icmp_ln86_23_fu_544_p2 = (($signed(p_read1_int_reg) < $signed(18'd27613)) ? 1'b1 : 1'b0);

assign icmp_ln86_24_fu_550_p2 = (($signed(p_read15_int_reg) < $signed(18'd4254)) ? 1'b1 : 1'b0);

assign icmp_ln86_25_fu_556_p2 = (($signed(p_read7_int_reg) < $signed(18'd226)) ? 1'b1 : 1'b0);

assign icmp_ln86_2_fu_418_p2 = (($signed(p_read9_int_reg) < $signed(18'd102)) ? 1'b1 : 1'b0);

assign icmp_ln86_3_fu_424_p2 = (($signed(p_read4_int_reg) < $signed(18'd30421)) ? 1'b1 : 1'b0);

assign icmp_ln86_4_fu_430_p2 = (($signed(p_read14_int_reg) < $signed(18'd25355)) ? 1'b1 : 1'b0);

assign icmp_ln86_5_fu_436_p2 = (($signed(p_read2_int_reg) < $signed(18'd261806)) ? 1'b1 : 1'b0);

assign icmp_ln86_6_fu_442_p2 = (($signed(p_read22_int_reg) < $signed(18'd80385)) ? 1'b1 : 1'b0);

assign icmp_ln86_7_fu_448_p2 = (($signed(p_read6_int_reg) < $signed(18'd814)) ? 1'b1 : 1'b0);

assign icmp_ln86_8_fu_454_p2 = (($signed(p_read15_int_reg) < $signed(18'd6409)) ? 1'b1 : 1'b0);

assign icmp_ln86_9_fu_460_p2 = (($signed(p_read5_int_reg) < $signed(18'd10814)) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_406_p2 = (($signed(tmp_39_fu_396_p4) < $signed(13'd1)) ? 1'b1 : 1'b0);

assign or_ln104_fu_618_p2 = (icmp_ln86_reg_1285 | icmp_ln86_2_reg_1296);

assign or_ln117_10_fu_869_p2 = (or_ln117_9_fu_857_p2 | and_ln102_17_fu_828_p2);

assign or_ln117_11_fu_883_p2 = (or_ln117_7_reg_1520 | and_ln102_3_reg_1461_pp0_iter2_reg);

assign or_ln117_12_fu_946_p2 = (or_ln117_11_reg_1540 | and_ln102_18_fu_928_p2);

assign or_ln117_13_fu_903_p2 = (or_ln117_11_fu_883_p2 | and_ln102_8_reg_1480_pp0_iter2_reg);

assign or_ln117_14_fu_962_p2 = (or_ln117_13_reg_1550 | and_ln102_19_fu_932_p2);

assign or_ln117_15_fu_974_p2 = (or_ln117_13_reg_1550 | and_ln102_9_reg_1534);

assign or_ln117_16_fu_986_p2 = (or_ln117_15_fu_974_p2 | and_ln102_20_fu_941_p2);

assign or_ln117_17_fu_1000_p2 = (or_ln117_13_reg_1550 | and_ln102_4_reg_1528);

assign or_ln117_1849_fu_659_p2 = (or_ln117_27_fu_654_p2 | icmp_ln86_9_reg_1339);

assign or_ln117_18_fu_1058_p2 = (or_ln117_17_reg_1569 | and_ln102_21_fu_1039_p2);

assign or_ln117_19_fu_1020_p2 = (or_ln117_17_fu_1000_p2 | and_ln102_10_fu_923_p2);

assign or_ln117_1_fu_672_p2 = (and_ln104_4_fu_643_p2 | and_ln102_5_fu_628_p2);

assign or_ln117_20_fu_1070_p2 = (or_ln117_19_reg_1579 | and_ln102_22_fu_1048_p2);

assign or_ln117_21_fu_1026_p2 = (or_ln117_13_reg_1550 | and_ln102_1_reg_1442_pp0_iter3_reg);

assign or_ln117_22_fu_1090_p2 = (or_ln117_21_reg_1585 | and_ln102_23_fu_1053_p2);

assign or_ln117_23_fu_1102_p2 = (or_ln117_21_reg_1585 | and_ln102_11_fu_1035_p2);

assign or_ln117_24_fu_1138_p2 = (or_ln117_23_reg_1593 | and_ln102_24_fu_1133_p2);

assign or_ln117_25_fu_1274_p2 = (xor_ln104_5_reg_1468_pp0_iter6_reg | or_ln117_21_reg_1585_pp0_iter6_reg);

assign or_ln117_26_fu_649_p2 = (xor_ln104_fu_580_p2 | icmp_ln86_1_reg_1291);

assign or_ln117_27_fu_654_p2 = (or_ln117_26_fu_649_p2 | icmp_ln86_4_reg_1308);

assign or_ln117_2_fu_722_p2 = (or_ln117_1_reg_1498 | and_ln102_13_fu_700_p2);

assign or_ln117_3_fu_734_p2 = (and_ln104_4_reg_1486 | and_ln102_2_reg_1449);

assign or_ln117_4_fu_746_p2 = (or_ln117_3_fu_734_p2 | and_ln102_14_fu_705_p2);

assign or_ln117_5_fu_764_p2 = (or_ln117_3_fu_734_p2 | and_ln102_6_fu_683_p2);

assign or_ln117_6_fu_833_p2 = (or_ln117_5_reg_1510 | and_ln102_15_fu_814_p2);

assign or_ln117_7_fu_786_p2 = (and_ln104_4_reg_1486 | and_ln102_reg_1429_pp0_iter1_reg);

assign or_ln117_8_fu_845_p2 = (or_ln117_7_reg_1520 | and_ln102_16_fu_819_p2);

assign or_ln117_9_fu_857_p2 = (or_ln117_7_reg_1520 | and_ln102_7_reg_1504);

assign or_ln117_fu_710_p2 = (and_ln104_4_reg_1486 | and_ln102_12_fu_691_p2);

assign select_ln117_10_fu_875_p3 = ((or_ln117_9_fu_857_p2[0:0] == 1'b1) ? select_ln117_9_fu_861_p3 : 4'd13);

assign select_ln117_11_fu_887_p3 = ((or_ln117_10_fu_869_p2[0:0] == 1'b1) ? select_ln117_10_fu_875_p3 : 4'd14);

assign select_ln117_12_fu_895_p3 = ((or_ln117_11_fu_883_p2[0:0] == 1'b1) ? select_ln117_11_fu_887_p3 : 4'd15);

assign select_ln117_13_fu_954_p3 = ((or_ln117_12_fu_946_p2[0:0] == 1'b1) ? zext_ln117_1_fu_951_p1 : 5'd16);

assign select_ln117_14_fu_967_p3 = ((or_ln117_13_reg_1550[0:0] == 1'b1) ? select_ln117_13_fu_954_p3 : 5'd17);

assign select_ln117_15_fu_978_p3 = ((or_ln117_14_fu_962_p2[0:0] == 1'b1) ? select_ln117_14_fu_967_p3 : 5'd18);

assign select_ln117_16_fu_992_p3 = ((or_ln117_15_fu_974_p2[0:0] == 1'b1) ? select_ln117_15_fu_978_p3 : 5'd19);

assign select_ln117_17_fu_1004_p3 = ((or_ln117_16_fu_986_p2[0:0] == 1'b1) ? select_ln117_16_fu_992_p3 : 5'd20);

assign select_ln117_18_fu_1012_p3 = ((or_ln117_17_fu_1000_p2[0:0] == 1'b1) ? select_ln117_17_fu_1004_p3 : 5'd21);

assign select_ln117_19_fu_1063_p3 = ((or_ln117_18_fu_1058_p2[0:0] == 1'b1) ? select_ln117_18_reg_1574 : 5'd22);

assign select_ln117_1_fu_715_p3 = ((or_ln117_fu_710_p2[0:0] == 1'b1) ? select_ln117_reg_1493 : 3'd4);

assign select_ln117_20_fu_1075_p3 = ((or_ln117_19_reg_1579[0:0] == 1'b1) ? select_ln117_19_fu_1063_p3 : 5'd23);

assign select_ln117_21_fu_1082_p3 = ((or_ln117_20_fu_1070_p2[0:0] == 1'b1) ? select_ln117_20_fu_1075_p3 : 5'd24);

assign select_ln117_22_fu_1095_p3 = ((or_ln117_21_reg_1585[0:0] == 1'b1) ? select_ln117_21_fu_1082_p3 : 5'd25);

assign select_ln117_23_fu_1107_p3 = ((or_ln117_22_fu_1090_p2[0:0] == 1'b1) ? select_ln117_22_fu_1095_p3 : 5'd26);

assign select_ln117_24_fu_1115_p3 = ((or_ln117_23_fu_1102_p2[0:0] == 1'b1) ? select_ln117_23_fu_1107_p3 : 5'd27);

assign select_ln117_2_fu_727_p3 = ((or_ln117_1_reg_1498[0:0] == 1'b1) ? select_ln117_1_fu_715_p3 : 3'd5);

assign select_ln117_3_fu_738_p3 = ((or_ln117_2_fu_722_p2[0:0] == 1'b1) ? select_ln117_2_fu_727_p3 : 3'd6);

assign select_ln117_4_fu_752_p3 = ((or_ln117_3_fu_734_p2[0:0] == 1'b1) ? select_ln117_3_fu_738_p3 : 3'd7);

assign select_ln117_5_fu_770_p3 = ((or_ln117_4_fu_746_p2[0:0] == 1'b1) ? zext_ln117_fu_760_p1 : 4'd8);

assign select_ln117_6_fu_778_p3 = ((or_ln117_5_fu_764_p2[0:0] == 1'b1) ? select_ln117_5_fu_770_p3 : 4'd9);

assign select_ln117_7_fu_838_p3 = ((or_ln117_6_fu_833_p2[0:0] == 1'b1) ? select_ln117_6_reg_1515 : 4'd10);

assign select_ln117_8_fu_850_p3 = ((or_ln117_7_reg_1520[0:0] == 1'b1) ? select_ln117_7_fu_838_p3 : 4'd11);

assign select_ln117_9_fu_861_p3 = ((or_ln117_8_fu_845_p2[0:0] == 1'b1) ? select_ln117_8_fu_850_p3 : 4'd12);

assign select_ln117_fu_664_p3 = ((or_ln117_1849_fu_659_p2[0:0] == 1'b1) ? 3'd3 : 3'd0);

assign tmp_39_fu_396_p4 = {{p_read10_int_reg[17:5]}};

assign tmp_fu_1150_p59 = 'bx;

assign tmp_fu_1150_p60 = ((or_ln117_24_fu_1138_p2[0:0] == 1'b1) ? select_ln117_24_reg_1598 : 5'd28);

assign xor_ln104_10_fu_918_p2 = (icmp_ln86_10_reg_1346_pp0_iter3_reg ^ 1'd1);

assign xor_ln104_11_fu_1030_p2 = (icmp_ln86_11_reg_1352_pp0_iter4_reg ^ 1'd1);

assign xor_ln104_12_fu_1123_p2 = (icmp_ln86_12_reg_1358_pp0_iter5_reg ^ 1'd1);

assign xor_ln104_1_fu_568_p2 = (icmp_ln86_1_fu_412_p2 ^ 1'd1);

assign xor_ln104_2_fu_594_p2 = (icmp_ln86_3_reg_1302 ^ 1'd1);

assign xor_ln104_3_fu_608_p2 = (icmp_ln86_4_reg_1308 ^ 1'd1);

assign xor_ln104_4_fu_908_p2 = (icmp_ln86_5_reg_1315_pp0_iter3_reg ^ 1'd1);

assign xor_ln104_5_fu_622_p2 = (or_ln104_fu_618_p2 ^ 1'd1);

assign xor_ln104_6_fu_678_p2 = (icmp_ln86_6_reg_1321_pp0_iter1_reg ^ 1'd1);

assign xor_ln104_7_fu_794_p2 = (icmp_ln86_7_reg_1327_pp0_iter2_reg ^ 1'd1);

assign xor_ln104_8_fu_799_p2 = (icmp_ln86_8_reg_1333_pp0_iter2_reg ^ 1'd1);

assign xor_ln104_9_fu_638_p2 = (icmp_ln86_9_reg_1339 ^ 1'd1);

assign xor_ln104_fu_580_p2 = (icmp_ln86_reg_1285 ^ 1'd1);

assign zext_ln117_1_fu_951_p1 = select_ln117_12_reg_1545;

assign zext_ln117_fu_760_p1 = select_ln117_4_fu_752_p3;

always @ (posedge ap_clk) begin
    select_ln117_reg_1493[2] <= 1'b0;
end

endmodule //conifer_jettag_accelerator_decision_function
