// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_12_12_5_3_0_ap_fixed_15_14_5_3_0_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_14_val,
        data_23_val,
        data_30_val,
        data_32_val,
        data_41_val,
        data_46_val,
        data_47_val,
        data_52_val,
        data_54_val,
        data_55_val,
        data_57_val,
        data_58_val,
        data_62_val,
        data_63_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [11:0] data_14_val;
input  [8:0] data_23_val;
input  [10:0] data_30_val;
input  [8:0] data_32_val;
input  [9:0] data_41_val;
input  [7:0] data_46_val;
input  [7:0] data_47_val;
input  [8:0] data_52_val;
input  [10:0] data_54_val;
input  [8:0] data_55_val;
input  [7:0] data_57_val;
input  [9:0] data_58_val;
input  [7:0] data_62_val;
input  [11:0] data_63_val;
output  [14:0] ap_return_0;
output  [14:0] ap_return_1;
output  [14:0] ap_return_2;
output  [14:0] ap_return_3;
output  [14:0] ap_return_4;
output  [14:0] ap_return_5;
output  [14:0] ap_return_6;
output  [14:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [19:0] mult_42_fu_618_p2;
reg   [19:0] mult_42_reg_38997;
wire    ap_block_pp0_stage0_11001;
wire   [17:0] mul_ln17_fu_871_p2;
reg   [17:0] mul_ln17_reg_39001;
wire   [16:0] mul_ln17_1_fu_401_p2;
reg   [16:0] mul_ln17_1_reg_39005;
wire   [19:0] mult_68_fu_508_p2;
reg   [19:0] mult_68_reg_39012;
wire   [20:0] mult_87_fu_1066_p2;
reg   [20:0] mult_87_reg_39028;
wire   [20:0] mult_90_fu_614_p2;
reg   [20:0] mult_90_reg_39032;
reg   [11:0] data_63_val_read_reg_58374;
reg   [7:0] data_62_val_read_reg_58384;
reg   [9:0] data_58_val_read_reg_58393;
reg   [7:0] data_57_val_read_reg_58403;
reg   [10:0] data_54_val_read_reg_58409;
reg   [7:0] data_47_val_read_reg_58417;
reg   [7:0] data_46_val_read_reg_58425;
reg   [9:0] data_41_val_read_reg_58434;
reg   [8:0] data_32_val_read_reg_58443;
reg   [10:0] data_30_val_read_reg_58452;
reg   [8:0] data_23_val_read_reg_58461;
reg   [11:0] data_14_val_read_reg_58470;
wire   [17:0] sub_ln42_16_fu_56063_p2;
reg   [17:0] sub_ln42_16_reg_58480;
wire   [22:0] zext_ln42_44_fu_56132_p1;
reg   [22:0] zext_ln42_44_reg_58485;
wire   [16:0] mult_94_fu_56339_p2;
reg   [16:0] mult_94_reg_58490;
wire   [20:0] add_ln58_74_fu_56361_p2;
reg   [20:0] add_ln58_74_reg_58495;
wire   [9:0] tmp21_fu_56367_p2;
reg   [9:0] tmp21_reg_58500;
wire   [19:0] add_ln58_96_fu_56379_p2;
reg   [19:0] add_ln58_96_reg_58505;
wire   [20:0] add_ln58_107_fu_56431_p2;
reg   [20:0] add_ln58_107_reg_58510;
wire   [18:0] add_ln58_118_fu_56437_p2;
reg   [18:0] add_ln58_118_reg_58515;
wire   [21:0] add_ln58_137_fu_56477_p2;
reg   [21:0] add_ln58_137_reg_58520;
wire   [22:0] add_ln58_146_fu_56493_p2;
reg   [22:0] add_ln58_146_reg_58525;
wire   [11:0] mult_39_fu_316_p0;
wire  signed [12:0] mult_39_fu_316_p1;
wire    ap_block_pp0_stage0;
wire   [7:0] mul_ln17_1_fu_401_p0;
wire   [10:0] mul_ln17_1_fu_401_p1;
wire   [10:0] mult_75_fu_445_p0;
wire  signed [10:0] mult_75_fu_445_p1;
wire   [11:0] mult_40_fu_483_p0;
wire  signed [11:0] mult_40_fu_483_p1;
wire   [8:0] mult_68_fu_508_p0;
wire   [19:0] zext_ln42_41_fu_56073_p1;
wire  signed [10:0] mult_68_fu_508_p1;
wire   [8:0] mult_78_fu_552_p0;
wire  signed [9:0] mult_78_fu_552_p1;
wire   [9:0] mult_90_fu_614_p0;
wire   [20:0] zext_ln42_57_fu_56297_p1;
wire   [11:0] mult_90_fu_614_p1;
wire   [8:0] mult_42_fu_618_p0;
wire  signed [10:0] mult_42_fu_618_p1;
wire   [7:0] mult_81_fu_706_p0;
wire  signed [9:0] mult_81_fu_706_p1;
wire   [10:0] mult_49_fu_800_p0;
wire   [11:0] mult_49_fu_800_p1;
wire   [8:0] mult_53_fu_856_p0;
wire  signed [11:0] mult_53_fu_856_p1;
wire   [7:0] mul_ln17_fu_871_p0;
wire  signed [10:0] mul_ln17_fu_871_p1;
wire   [8:0] mult_66_fu_960_p0;
wire  signed [10:0] mult_66_fu_960_p1;
wire   [10:0] mult_73_fu_968_p0;
wire  signed [11:0] mult_73_fu_968_p1;
wire   [10:0] mult_76_fu_1022_p0;
wire  signed [11:0] mult_76_fu_1022_p1;
wire   [9:0] mult_87_fu_1066_p0;
wire   [11:0] mult_87_fu_1066_p1;
wire   [15:0] tmp_128_fu_56051_p3;
wire   [17:0] zext_ln42_71_fu_56059_p1;
wire   [19:0] mult_66_fu_960_p2;
wire   [15:0] tmp_129_fu_56083_p3;
wire   [16:0] zext_ln42_73_fu_56091_p1;
wire   [16:0] mult_67_fu_56095_p2;
wire   [18:0] tmp_130_fu_56105_p3;
wire   [19:0] zext_ln42_74_fu_56113_p1;
wire   [19:0] mult_69_fu_56117_p2;
wire   [18:0] mult_72_fu_56137_p3;
wire   [19:0] zext_ln42_75_fu_56145_p1;
wire   [19:0] mult_70_fu_56149_p2;
wire   [14:0] tmp_135_fu_56176_p3;
wire   [16:0] p_shl11_fu_56168_p3;
wire   [16:0] zext_ln42_79_fu_56184_p1;
wire   [16:0] mult_77_fu_56188_p2;
wire   [18:0] mult_78_fu_552_p2;
wire   [18:0] p_shl12_fu_56202_p3;
wire   [18:0] zext_ln42_80_fu_56210_p1;
wire   [15:0] tmp_137_fu_56237_p3;
wire   [13:0] tmp_138_fu_56249_p3;
wire   [16:0] zext_ln42_82_fu_56245_p1;
wire   [16:0] zext_ln42_83_fu_56257_p1;
wire   [16:0] mult_83_fu_56261_p2;
wire   [16:0] mult_84_fu_56271_p3;
wire   [15:0] zext_ln42_84_fu_56283_p1;
wire   [15:0] mult_85_fu_56287_p2;
wire   [19:0] mult_88_fu_56303_p3;
wire   [15:0] tmp_145_fu_56315_p3;
wire   [12:0] tmp_146_fu_56327_p3;
wire   [16:0] zext_ln42_92_fu_56323_p1;
wire   [16:0] zext_ln42_93_fu_56335_p1;
wire  signed [20:0] sext_ln17_32_fu_56079_p1;
wire  signed [20:0] sext_ln17_36_fu_56155_p1;
wire   [17:0] zext_ln17_29_fu_56194_p1;
wire   [17:0] mult_81_fu_706_p2;
wire   [17:0] add_ln58_73_fu_56351_p2;
wire  signed [20:0] sext_ln58_33_fu_56357_p1;
wire   [20:0] add_ln58_72_fu_56345_p2;
wire   [9:0] zext_ln42_47_fu_56159_p1;
wire   [9:0] zext_ln42_39_fu_56069_p1;
wire  signed [19:0] sext_ln17_38_fu_56198_p1;
wire   [19:0] add_ln58_95_fu_56373_p2;
wire  signed [19:0] sext_ln17_33_fu_56101_p1;
wire   [9:0] zext_ln42_23_fu_56032_p1;
wire   [9:0] tmp29_fu_56385_p2;
wire   [18:0] tmp_156_fu_56391_p3;
wire   [16:0] tmp_157_fu_56403_p3;
wire   [19:0] p_shl28_fu_56399_p1;
wire   [19:0] p_shl29_fu_56411_p1;
wire   [19:0] tmp30_fu_56415_p2;
wire   [20:0] zext_ln58_9_fu_56421_p1;
wire   [20:0] zext_ln17_35_fu_56311_p1;
wire   [20:0] add_ln58_106_fu_56425_p2;
wire   [20:0] zext_ln17_30_fu_56267_p1;
wire   [18:0] mult_79_fu_56214_p2;
wire   [18:0] zext_ln17_31_fu_56279_p1;
wire  signed [21:0] sext_ln17_35_fu_56123_p1;
wire   [21:0] mult_75_fu_445_p2;
wire   [8:0] zext_ln42_50_fu_56228_p1;
wire   [8:0] add_ln58_136_fu_56449_p2;
wire   [16:0] tmp_160_fu_56455_p3;
wire   [17:0] zext_ln58_16_fu_56463_p1;
wire   [17:0] sub_ln58_7_fu_56467_p2;
wire  signed [21:0] sext_ln58_62_fu_56473_p1;
wire   [21:0] add_ln58_135_fu_56443_p2;
wire   [17:0] mult_80_fu_56220_p3;
wire   [17:0] zext_ln17_32_fu_56293_p1;
wire   [17:0] add_ln58_145_fu_56483_p2;
wire   [22:0] zext_ln58_18_fu_56489_p1;
wire   [22:0] mult_76_fu_1022_p2;
wire   [22:0] tmp_fu_56510_p3;
wire   [19:0] tmp_108_fu_56521_p3;
wire   [23:0] zext_ln42_34_fu_56528_p1;
wire   [23:0] zext_ln42_33_fu_56517_p1;
wire   [20:0] mult_38_fu_56538_p3;
wire   [23:0] mult_40_fu_483_p2;
wire   [19:0] tmp_109_fu_56553_p3;
wire   [20:0] zext_ln42_37_fu_56560_p1;
wire   [20:0] mult_41_fu_56564_p2;
wire   [15:0] tmp_110_fu_56585_p3;
wire   [17:0] p_shl9_fu_56578_p3;
wire   [17:0] zext_ln42_40_fu_56592_p1;
wire   [17:0] mult_43_fu_56596_p2;
wire   [18:0] mult_44_fu_56606_p3;
wire   [20:0] tmp_111_fu_56617_p3;
wire   [21:0] zext_ln42_45_fu_56624_p1;
wire   [21:0] mult_45_fu_56628_p2;
wire   [20:0] tmp_112_fu_56642_p3;
wire   [17:0] mult_47_fu_56653_p3;
wire   [21:0] zext_ln42_46_fu_56649_p1;
wire   [21:0] zext_ln42_49_fu_56660_p1;
wire   [21:0] mult_46_fu_56664_p2;
wire   [21:0] mult_51_fu_56678_p3;
wire   [22:0] zext_ln42_52_fu_56685_p1;
wire   [22:0] zext_ln42_53_fu_56689_p1;
wire   [22:0] mult_48_fu_56693_p2;
wire   [21:0] mult_49_fu_800_p2;
wire   [18:0] tmp_115_fu_56707_p3;
wire   [21:0] zext_ln42_58_fu_56714_p1;
wire   [21:0] mult_52_fu_56724_p2;
wire   [20:0] mult_53_fu_856_p2;
wire   [17:0] mult_56_fu_56742_p3;
wire   [19:0] zext_ln42_60_fu_56749_p1;
wire   [15:0] tmp_117_fu_56759_p3;
wire   [19:0] sub_ln42_fu_56753_p2;
wire   [19:0] zext_ln42_61_fu_56766_p1;
wire   [16:0] tmp_118_fu_56776_p3;
wire   [14:0] tmp_119_fu_56787_p3;
wire   [17:0] zext_ln42_62_fu_56783_p1;
wire   [17:0] zext_ln42_63_fu_56794_p1;
wire   [17:0] mult_55_fu_56798_p2;
wire   [19:0] tmp_120_fu_56812_p3;
wire   [17:0] tmp_121_fu_56823_p3;
wire   [20:0] zext_ln42_65_fu_56830_p1;
wire   [20:0] zext_ln42_64_fu_56819_p1;
wire   [20:0] mult_57_fu_56834_p2;
wire   [18:0] tmp_122_fu_56844_p3;
wire   [19:0] zext_ln17_19_fu_56851_p1;
wire   [15:0] tmp_123_fu_56861_p3;
wire   [19:0] sub_ln17_fu_56855_p2;
wire   [19:0] zext_ln17_20_fu_56868_p1;
wire   [19:0] zext_ln42_66_fu_56878_p1;
wire   [19:0] sub_ln42_10_fu_56882_p2;
wire   [17:0] zext_ln17_21_fu_56894_p1;
wire   [20:0] sub_ln17_3_fu_56904_p2;
wire   [20:0] zext_ln17_23_fu_56910_p1;
wire   [15:0] mult_59_fu_56923_p3;
wire   [17:0] tmp_124_fu_56938_p3;
wire   [18:0] zext_ln17_28_fu_56945_p1;
wire   [18:0] sub_ln17_5_fu_56949_p2;
wire   [18:0] zext_ln17_41_fu_56955_p1;
wire   [17:0] zext_ln17_25_fu_56934_p1;
wire   [12:0] tmp_125_fu_56971_p3;
wire   [17:0] sub_ln42_12_fu_56965_p2;
wire   [17:0] zext_ln42_67_fu_56978_p1;
wire   [14:0] tmp_126_fu_56998_p3;
wire   [16:0] p_shl10_fu_56991_p3;
wire   [16:0] zext_ln42_68_fu_57005_p1;
wire   [16:0] mult_61_fu_57009_p2;
wire   [13:0] tmp_127_fu_57023_p3;
wire   [17:0] zext_ln42_70_fu_57030_p1;
wire   [17:0] zext_ln42_69_fu_57019_p1;
wire   [17:0] zext_ln42_72_fu_57045_p1;
wire   [17:0] mult_64_fu_57049_p2;
wire   [17:0] mult_65_fu_57059_p2;
wire   [19:0] tmp_132_fu_57076_p3;
wire   [20:0] zext_ln42_76_fu_57083_p1;
wire   [20:0] mult_71_fu_57087_p2;
wire   [20:0] tmp_133_fu_57097_p3;
wire   [17:0] tmp_134_fu_57108_p3;
wire   [21:0] zext_ln42_78_fu_57115_p1;
wire   [21:0] zext_ln42_77_fu_57104_p1;
wire   [14:0] tmp_136_fu_57128_p3;
wire   [15:0] zext_ln42_81_fu_57135_p1;
wire   [15:0] mult_82_fu_57139_p2;
wire   [18:0] tmp_139_fu_57155_p3;
wire   [14:0] tmp_140_fu_57166_p3;
wire   [19:0] zext_ln42_85_fu_57162_p1;
wire   [19:0] zext_ln42_86_fu_57173_p1;
wire   [19:0] mult_86_fu_57177_p2;
wire   [17:0] tmp_141_fu_57198_p3;
wire   [20:0] p_shl13_fu_57191_p3;
wire   [20:0] zext_ln42_87_fu_57205_p1;
wire   [20:0] zext_ln42_88_fu_57219_p1;
wire   [20:0] mult_91_fu_57223_p2;
wire   [16:0] tmp_142_fu_57236_p3;
wire   [18:0] zext_ln42_89_fu_57243_p1;
wire   [13:0] tmp_143_fu_57253_p3;
wire   [18:0] sub_ln42_30_fu_57247_p2;
wire   [18:0] zext_ln42_90_fu_57260_p1;
wire   [18:0] mult_92_fu_57264_p2;
wire   [14:0] tmp_144_fu_57274_p3;
wire   [16:0] zext_ln42_91_fu_57281_p1;
wire   [16:0] mult_93_fu_57285_p2;
wire   [17:0] zext_ln42_94_fu_57298_p1;
wire   [17:0] mult_95_fu_57302_p2;
wire   [20:0] mult_101_fu_57312_p3;
wire   [22:0] zext_ln42_95_fu_57319_p1;
wire   [18:0] tmp_148_fu_57329_p3;
wire   [22:0] sub_ln42_34_fu_57323_p2;
wire   [22:0] zext_ln42_96_fu_57336_p1;
wire   [19:0] zext_ln42_97_fu_57346_p1;
wire   [19:0] mult_97_fu_57350_p2;
wire   [22:0] tmp_149_fu_57360_p3;
wire   [23:0] zext_ln42_99_fu_57371_p1;
wire   [23:0] zext_ln42_98_fu_57367_p1;
wire   [21:0] tmp_150_fu_57381_p3;
wire   [23:0] zext_ln42_100_fu_57388_p1;
wire   [19:0] tmp_151_fu_57398_p3;
wire   [23:0] sub_ln42_38_fu_57392_p2;
wire   [23:0] zext_ln42_101_fu_57405_p1;
wire   [16:0] tmp_152_fu_57419_p3;
wire   [22:0] zext_ln42_103_fu_57426_p1;
wire   [22:0] zext_ln42_102_fu_57415_p1;
wire  signed [22:0] sext_ln17_26_fu_56570_p1;
wire   [22:0] zext_ln17_12_fu_56670_p1;
wire   [22:0] add_ln58_fu_57446_p2;
wire  signed [23:0] sext_ln58_fu_57452_p1;
wire   [23:0] mult_fu_56532_p2;
wire   [23:0] add_ln58_67_fu_57456_p2;
wire  signed [21:0] sext_ln17_29_fu_56738_p1;
wire  signed [21:0] sext_ln17_30_fu_56840_p1;
wire   [18:0] sub_ln17_6_fu_56959_p2;
wire   [18:0] zext_ln17_26_fu_57015_p1;
wire   [18:0] add_ln58_69_fu_57472_p2;
wire  signed [21:0] sext_ln58_31_fu_57478_p1;
wire   [21:0] add_ln58_68_fu_57466_p2;
wire   [21:0] add_ln58_70_fu_57482_p2;
wire  signed [24:0] sext_ln58_32_fu_57488_p1;
wire  signed [24:0] sext_ln58_30_fu_57462_p1;
wire   [20:0] zext_ln17_33_fu_57183_p1;
wire  signed [20:0] sext_ln17_40_fu_57270_p1;
wire   [20:0] add_ln58_75_fu_57501_p2;
wire   [22:0] mult_96_fu_57340_p2;
wire   [22:0] add_ln58_76_fu_57511_p2;
wire  signed [22:0] sext_ln58_35_fu_57507_p1;
wire   [22:0] add_ln58_77_fu_57517_p2;
wire  signed [22:0] sext_ln58_34_fu_57498_p1;
wire   [22:0] add_ln58_78_fu_57523_p2;
wire  signed [24:0] sext_ln58_36_fu_57529_p1;
wire   [24:0] add_ln58_71_fu_57492_p2;
wire   [12:0] zext_ln42_fu_56503_p1;
wire   [12:0] zext_ln42_59_fu_57233_p1;
wire   [12:0] tmp13_fu_57539_p2;
wire   [12:0] zext_ln42_51_fu_57125_p1;
wire   [12:0] tmp19_fu_57545_p2;
wire   [19:0] tmp_153_fu_57559_p3;
wire   [22:0] p_shl34_fu_57567_p1;
wire   [22:0] p_shl14_fu_57551_p3;
wire   [19:0] zext_ln17_13_fu_56674_p1;
wire   [19:0] mult_54_fu_56770_p2;
wire   [19:0] add_ln58_80_fu_57580_p2;
wire   [17:0] mult_60_fu_56982_p2;
wire   [17:0] mult_62_fu_57034_p2;
wire   [17:0] add_ln58_81_fu_57590_p2;
wire  signed [19:0] sext_ln58_38_fu_57596_p1;
wire   [19:0] sub_ln17_1_fu_56872_p2;
wire   [19:0] add_ln58_82_fu_57600_p2;
wire  signed [20:0] sext_ln58_39_fu_57606_p1;
wire  signed [20:0] sext_ln58_37_fu_57586_p1;
wire   [20:0] add_ln58_83_fu_57610_p2;
wire   [10:0] zext_ln58_fu_57577_p1;
wire   [10:0] zext_ln42_56_fu_57152_p1;
wire   [10:0] add_ln58_84_fu_57620_p2;
wire   [16:0] tmp_154_fu_57626_p3;
wire   [17:0] zext_ln58_8_fu_57634_p1;
wire   [17:0] sub_ln58_fu_57638_p2;
wire  signed [21:0] sext_ln58_41_fu_57644_p1;
wire  signed [21:0] sext_ln17_37_fu_57093_p1;
wire   [21:0] add_ln58_85_fu_57648_p2;
wire   [22:0] tmp20_fu_57571_p2;
wire   [22:0] add_ln58_86_fu_57658_p2;
wire  signed [23:0] sext_ln58_43_fu_57664_p1;
wire  signed [23:0] sext_ln17_42_fu_57356_p1;
wire   [23:0] add_ln58_87_fu_57668_p2;
wire  signed [23:0] sext_ln58_42_fu_57654_p1;
wire   [23:0] add_ln58_88_fu_57674_p2;
wire  signed [23:0] sext_ln58_40_fu_57616_p1;
wire  signed [23:0] sext_ln17_27_fu_56574_p1;
wire   [23:0] zext_ln17_14_fu_56699_p1;
wire   [23:0] add_ln58_90_fu_57686_p2;
wire   [23:0] zext_ln17_fu_56545_p1;
wire   [17:0] mult_63_fu_57040_p2;
wire   [17:0] add_ln58_92_fu_57698_p2;
wire  signed [19:0] sext_ln58_44_fu_57704_p1;
wire   [19:0] mult_58_fu_56888_p2;
wire   [19:0] add_ln58_93_fu_57708_p2;
wire  signed [23:0] sext_ln58_45_fu_57714_p1;
wire   [23:0] add_ln58_91_fu_57692_p2;
wire   [23:0] add_ln58_94_fu_57718_p2;
wire  signed [21:0] sext_ln17_39_fu_57145_p1;
wire   [21:0] zext_ln17_34_fu_57187_p1;
wire   [21:0] add_ln58_97_fu_57731_p2;
wire   [23:0] mult_98_fu_57375_p2;
wire   [23:0] add_ln58_98_fu_57741_p2;
wire  signed [23:0] sext_ln58_48_fu_57737_p1;
wire   [23:0] add_ln58_99_fu_57747_p2;
wire  signed [23:0] sext_ln58_47_fu_57728_p1;
wire   [23:0] add_ln58_100_fu_57753_p2;
wire  signed [24:0] sext_ln58_49_fu_57759_p1;
wire  signed [24:0] sext_ln58_46_fu_57724_p1;
wire   [9:0] zext_ln42_35_fu_56920_p1;
wire   [9:0] tmp27_fu_57769_p2;
wire   [14:0] tmp_155_fu_57782_p3;
wire   [17:0] p_shl15_fu_57774_p3;
wire   [17:0] p_shl31_fu_57790_p1;
wire   [17:0] tmp28_fu_57794_p2;
wire   [24:0] mult_39_fu_316_p2;
wire   [24:0] zext_ln17_15_fu_56703_p1;
wire   [22:0] tmp28_cast_fu_57800_p1;
wire   [22:0] mult_73_fu_968_p2;
wire   [22:0] add_ln58_103_fu_57810_p2;
wire   [22:0] zext_ln17_27_fu_57055_p1;
wire   [22:0] add_ln58_104_fu_57816_p2;
wire  signed [24:0] sext_ln58_50_fu_57822_p1;
wire   [24:0] add_ln58_102_fu_57804_p2;
wire   [23:0] mult_99_fu_57409_p2;
wire   [23:0] add_ln58_108_fu_57835_p2;
wire   [23:0] zext_ln17_38_fu_57291_p1;
wire   [23:0] add_ln58_109_fu_57841_p2;
wire   [23:0] zext_ln58_10_fu_57832_p1;
wire   [23:0] add_ln58_110_fu_57847_p2;
wire  signed [24:0] sext_ln58_51_fu_57853_p1;
wire   [24:0] add_ln58_105_fu_57826_p2;
wire   [12:0] zext_ln42_36_fu_56988_p1;
wire   [12:0] tmp32_fu_57863_p2;
wire   [18:0] tmp_158_fu_57877_p3;
wire   [22:0] p_shl16_fu_57869_p3;
wire  signed [22:0] sext_ln58_52_fu_57885_p1;
wire   [21:0] mult_50_fu_56718_p2;
wire   [21:0] zext_ln17_17_fu_56804_p1;
wire   [21:0] add_ln58_112_fu_57895_p2;
wire   [21:0] zext_ln17_10_fu_56602_p1;
wire   [21:0] add_ln58_113_fu_57901_p2;
wire   [17:0] sub_ln17_2_fu_56898_p2;
wire   [17:0] add_ln58_114_fu_57911_p2;
wire  signed [22:0] sext_ln17_34_fu_57069_p1;
wire   [22:0] sub_ln58_5_fu_57889_p2;
wire   [22:0] add_ln58_115_fu_57921_p2;
wire  signed [23:0] sext_ln58_54_fu_57927_p1;
wire  signed [23:0] sext_ln58_53_fu_57917_p1;
wire   [23:0] add_ln58_116_fu_57931_p2;
wire   [23:0] zext_ln58_11_fu_57907_p1;
wire   [23:0] add_ln58_117_fu_57937_p2;
wire   [21:0] zext_ln58_12_fu_57947_p1;
wire   [21:0] mult_74_fu_57119_p2;
wire   [21:0] add_ln58_119_fu_57950_p2;
wire   [20:0] mult_89_fu_57209_p2;
wire   [20:0] zext_ln17_39_fu_57295_p1;
wire   [20:0] add_ln58_120_fu_57960_p2;
wire   [22:0] mult_100_fu_57430_p2;
wire   [22:0] add_ln58_121_fu_57970_p2;
wire   [22:0] zext_ln58_13_fu_57966_p1;
wire   [22:0] add_ln58_122_fu_57976_p2;
wire  signed [23:0] sext_ln58_57_fu_57982_p1;
wire  signed [23:0] sext_ln58_56_fu_57956_p1;
wire   [23:0] add_ln58_123_fu_57986_p2;
wire  signed [24:0] sext_ln58_58_fu_57992_p1;
wire  signed [24:0] sext_ln58_55_fu_57943_p1;
wire   [11:0] zext_ln42_55_fu_57149_p1;
wire   [11:0] zext_ln42_42_fu_57073_p1;
wire   [11:0] tmp34_fu_58002_p2;
wire   [22:0] tmp_159_fu_58008_p3;
wire   [8:0] data_62_val_cast54_fu_58023_p1;
wire   [8:0] data_46_val_cast55_fu_58020_p1;
wire   [8:0] tmp3634_fu_58026_p2;
wire  signed [23:0] sext_ln17_31_fu_57065_p1;
wire   [23:0] p_shl25_fu_58016_p1;
wire   [23:0] sub_ln58_6_fu_58040_p2;
wire   [23:0] zext_ln17_11_fu_56613_p1;
wire   [18:0] tmp37_fu_58032_p3;
wire   [18:0] add_ln58_126_fu_58052_p2;
wire   [21:0] zext_ln58_14_fu_58058_p1;
wire   [21:0] zext_ln17_40_fu_57436_p1;
wire   [21:0] add_ln58_127_fu_58062_p2;
wire   [23:0] zext_ln58_15_fu_58068_p1;
wire   [23:0] add_ln58_125_fu_58046_p2;
wire  signed [22:0] sext_ln17_28_fu_56634_p1;
wire   [22:0] add_ln58_129_fu_58078_p2;
wire  signed [24:0] sext_ln58_59_fu_58084_p1;
wire  signed [24:0] sext_ln17_fu_56549_p1;
wire   [20:0] zext_ln17_18_fu_56808_p1;
wire   [20:0] sub_ln17_4_fu_56914_p2;
wire   [17:0] add_ln58_132_fu_58100_p2;
wire  signed [20:0] sext_ln58_60_fu_58106_p1;
wire   [20:0] add_ln58_131_fu_58094_p2;
wire   [20:0] add_ln58_133_fu_58110_p2;
wire  signed [24:0] sext_ln58_61_fu_58116_p1;
wire   [24:0] add_ln58_130_fu_58088_p2;
wire   [21:0] zext_ln17_36_fu_57215_p1;
wire  signed [21:0] sext_ln17_41_fu_57308_p1;
wire   [19:0] sub_ln58_8_fu_58135_p2;
wire  signed [21:0] sext_ln58_64_fu_58141_p1;
wire   [21:0] add_ln58_138_fu_58129_p2;
wire   [21:0] add_ln58_139_fu_58145_p2;
wire  signed [22:0] sext_ln58_65_fu_58151_p1;
wire  signed [22:0] sext_ln58_63_fu_58126_p1;
wire   [22:0] add_ln58_140_fu_58155_p2;
wire  signed [24:0] sext_ln58_66_fu_58161_p1;
wire   [24:0] add_ln58_134_fu_58120_p2;
wire   [23:0] zext_ln17_16_fu_56730_p1;
wire   [16:0] zext_ln17_24_fu_56930_p1;
wire   [16:0] add_ln58_143_fu_58177_p2;
wire   [17:0] zext_ln58_17_fu_58183_p1;
wire   [17:0] sub_ln58_9_fu_58187_p2;
wire  signed [23:0] sext_ln58_67_fu_58193_p1;
wire   [23:0] add_ln58_142_fu_58171_p2;
wire   [23:0] add_ln58_144_fu_58197_p2;
wire   [23:0] mult_102_fu_57440_p2;
wire   [23:0] add_ln58_147_fu_58210_p2;
wire   [23:0] zext_ln17_37_fu_57229_p1;
wire   [23:0] add_ln58_148_fu_58216_p2;
wire  signed [23:0] sext_ln58_69_fu_58207_p1;
wire   [23:0] add_ln58_149_fu_58222_p2;
wire  signed [24:0] sext_ln58_70_fu_58228_p1;
wire  signed [24:0] sext_ln58_68_fu_58203_p1;
wire   [24:0] add_ln58_79_fu_57533_p2;
wire   [23:0] add_ln58_89_fu_57680_p2;
wire   [13:0] trunc_ln111_s_fu_58248_p4;
wire   [24:0] add_ln58_101_fu_57763_p2;
wire   [24:0] add_ln58_111_fu_57857_p2;
wire   [24:0] add_ln58_124_fu_57996_p2;
wire   [23:0] add_ln58_128_fu_58072_p2;
wire   [13:0] trunc_ln111_4_fu_58292_p4;
wire   [24:0] add_ln58_141_fu_58165_p2;
wire   [24:0] add_ln58_150_fu_58232_p2;
wire  signed [14:0] sext_ln111_fu_58258_p1;
wire  signed [14:0] sext_ln111_8_fu_58302_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [16:0] mul_ln17_1_fu_401_p00;
wire   [17:0] mul_ln17_fu_871_p00;
wire   [24:0] mult_39_fu_316_p00;
wire   [23:0] mult_40_fu_483_p00;
wire   [19:0] mult_42_fu_618_p00;
wire   [21:0] mult_49_fu_800_p00;
wire   [20:0] mult_53_fu_856_p00;
wire   [21:0] mult_75_fu_445_p00;
wire   [22:0] mult_76_fu_1022_p00;
wire   [18:0] mult_78_fu_552_p00;
wire   [17:0] mult_81_fu_706_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_mul_12ns_13s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 25 ))
mul_12ns_13s_25_1_1_U87(
    .din0(mult_39_fu_316_p0),
    .din1(mult_39_fu_316_p1),
    .dout(mult_39_fu_316_p2)
);

myproject_mul_8ns_11ns_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 17 ))
mul_8ns_11ns_17_1_1_U88(
    .din0(mul_ln17_1_fu_401_p0),
    .din1(mul_ln17_1_fu_401_p1),
    .dout(mul_ln17_1_fu_401_p2)
);

myproject_mul_11ns_11s_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 22 ))
mul_11ns_11s_22_1_1_U89(
    .din0(mult_75_fu_445_p0),
    .din1(mult_75_fu_445_p1),
    .dout(mult_75_fu_445_p2)
);

myproject_mul_12ns_12s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
mul_12ns_12s_24_1_1_U90(
    .din0(mult_40_fu_483_p0),
    .din1(mult_40_fu_483_p1),
    .dout(mult_40_fu_483_p2)
);

myproject_mul_9ns_11s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 20 ))
mul_9ns_11s_20_1_1_U91(
    .din0(mult_68_fu_508_p0),
    .din1(mult_68_fu_508_p1),
    .dout(mult_68_fu_508_p2)
);

myproject_mul_9ns_10s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 19 ))
mul_9ns_10s_19_1_1_U92(
    .din0(mult_78_fu_552_p0),
    .din1(mult_78_fu_552_p1),
    .dout(mult_78_fu_552_p2)
);

myproject_mul_10ns_12ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
mul_10ns_12ns_21_1_1_U93(
    .din0(mult_90_fu_614_p0),
    .din1(mult_90_fu_614_p1),
    .dout(mult_90_fu_614_p2)
);

myproject_mul_9ns_11s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 20 ))
mul_9ns_11s_20_1_1_U94(
    .din0(mult_42_fu_618_p0),
    .din1(mult_42_fu_618_p1),
    .dout(mult_42_fu_618_p2)
);

myproject_mul_8ns_10s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 18 ))
mul_8ns_10s_18_1_1_U95(
    .din0(mult_81_fu_706_p0),
    .din1(mult_81_fu_706_p1),
    .dout(mult_81_fu_706_p2)
);

myproject_mul_11ns_12ns_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 22 ))
mul_11ns_12ns_22_1_1_U96(
    .din0(mult_49_fu_800_p0),
    .din1(mult_49_fu_800_p1),
    .dout(mult_49_fu_800_p2)
);

myproject_mul_9ns_12s_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
mul_9ns_12s_21_1_1_U97(
    .din0(mult_53_fu_856_p0),
    .din1(mult_53_fu_856_p1),
    .dout(mult_53_fu_856_p2)
);

myproject_mul_8ns_11s_18_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 18 ))
mul_8ns_11s_18_1_1_U98(
    .din0(mul_ln17_fu_871_p0),
    .din1(mul_ln17_fu_871_p1),
    .dout(mul_ln17_fu_871_p2)
);

myproject_mul_9ns_11s_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 20 ))
mul_9ns_11s_20_1_1_U99(
    .din0(mult_66_fu_960_p0),
    .din1(mult_66_fu_960_p1),
    .dout(mult_66_fu_960_p2)
);

myproject_mul_11ns_12s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 23 ))
mul_11ns_12s_23_1_1_U100(
    .din0(mult_73_fu_968_p0),
    .din1(mult_73_fu_968_p1),
    .dout(mult_73_fu_968_p2)
);

myproject_mul_11ns_12s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 23 ))
mul_11ns_12s_23_1_1_U101(
    .din0(mult_76_fu_1022_p0),
    .din1(mult_76_fu_1022_p1),
    .dout(mult_76_fu_1022_p2)
);

myproject_mul_10ns_12ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 21 ))
mul_10ns_12ns_21_1_1_U102(
    .din0(mult_87_fu_1066_p0),
    .din1(mult_87_fu_1066_p1),
    .dout(mult_87_fu_1066_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln58_107_reg_58510[20 : 6] <= add_ln58_107_fu_56431_p2[20 : 6];
        add_ln58_118_reg_58515[18 : 8] <= add_ln58_118_fu_56437_p2[18 : 8];
        add_ln58_137_reg_58520 <= add_ln58_137_fu_56477_p2;
        add_ln58_146_reg_58525 <= add_ln58_146_fu_56493_p2;
        add_ln58_74_reg_58495 <= add_ln58_74_fu_56361_p2;
        add_ln58_96_reg_58505 <= add_ln58_96_fu_56379_p2;
        data_14_val_read_reg_58470 <= data_14_val;
        data_23_val_read_reg_58461 <= data_23_val;
        data_30_val_read_reg_58452 <= data_30_val;
        data_32_val_read_reg_58443 <= data_32_val;
        data_41_val_read_reg_58434 <= data_41_val;
        data_46_val_read_reg_58425 <= data_46_val;
        data_47_val_read_reg_58417 <= data_47_val;
        data_54_val_read_reg_58409 <= data_54_val;
        data_57_val_read_reg_58403 <= data_57_val;
        data_58_val_read_reg_58393 <= data_58_val;
        data_62_val_read_reg_58384 <= data_62_val;
        data_63_val_read_reg_58374 <= data_63_val;
        mul_ln17_1_reg_39005 <= mul_ln17_1_fu_401_p2;
        mul_ln17_reg_39001 <= mul_ln17_fu_871_p2;
        mult_42_reg_38997 <= mult_42_fu_618_p2;
        mult_68_reg_39012 <= mult_68_fu_508_p2;
        mult_87_reg_39028 <= mult_87_fu_1066_p2;
        mult_90_reg_39032 <= mult_90_fu_614_p2;
        mult_94_reg_58490[16 : 5] <= mult_94_fu_56339_p2[16 : 5];
        sub_ln42_16_reg_58480[17 : 8] <= sub_ln42_16_fu_56063_p2[17 : 8];
        tmp21_reg_58500 <= tmp21_fu_56367_p2;
        zext_ln42_44_reg_58485[10 : 0] <= zext_ln42_44_fu_56132_p1[10 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_100_fu_57753_p2 = ($signed(add_ln58_99_fu_57747_p2) + $signed(sext_ln58_47_fu_57728_p1));

assign add_ln58_101_fu_57763_p2 = ($signed(sext_ln58_49_fu_57759_p1) + $signed(sext_ln58_46_fu_57724_p1));

assign add_ln58_102_fu_57804_p2 = (mult_39_fu_316_p2 + zext_ln17_15_fu_56703_p1);

assign add_ln58_103_fu_57810_p2 = (tmp28_cast_fu_57800_p1 + mult_73_fu_968_p2);

assign add_ln58_104_fu_57816_p2 = (add_ln58_103_fu_57810_p2 + zext_ln17_27_fu_57055_p1);

assign add_ln58_105_fu_57826_p2 = ($signed(sext_ln58_50_fu_57822_p1) + $signed(add_ln58_102_fu_57804_p2));

assign add_ln58_106_fu_56425_p2 = (zext_ln58_9_fu_56421_p1 + zext_ln17_35_fu_56311_p1);

assign add_ln58_107_fu_56431_p2 = (add_ln58_106_fu_56425_p2 + zext_ln17_30_fu_56267_p1);

assign add_ln58_108_fu_57835_p2 = (mult_99_fu_57409_p2 + 24'd65536);

assign add_ln58_109_fu_57841_p2 = (add_ln58_108_fu_57835_p2 + zext_ln17_38_fu_57291_p1);

assign add_ln58_110_fu_57847_p2 = (add_ln58_109_fu_57841_p2 + zext_ln58_10_fu_57832_p1);

assign add_ln58_111_fu_57857_p2 = ($signed(sext_ln58_51_fu_57853_p1) + $signed(add_ln58_105_fu_57826_p2));

assign add_ln58_112_fu_57895_p2 = (mult_50_fu_56718_p2 + zext_ln17_17_fu_56804_p1);

assign add_ln58_113_fu_57901_p2 = (add_ln58_112_fu_57895_p2 + zext_ln17_10_fu_56602_p1);

assign add_ln58_114_fu_57911_p2 = (sub_ln17_2_fu_56898_p2 + zext_ln17_25_fu_56934_p1);

assign add_ln58_115_fu_57921_p2 = ($signed(sext_ln17_34_fu_57069_p1) + $signed(sub_ln58_5_fu_57889_p2));

assign add_ln58_116_fu_57931_p2 = ($signed(sext_ln58_54_fu_57927_p1) + $signed(sext_ln58_53_fu_57917_p1));

assign add_ln58_117_fu_57937_p2 = (add_ln58_116_fu_57931_p2 + zext_ln58_11_fu_57907_p1);

assign add_ln58_118_fu_56437_p2 = (mult_79_fu_56214_p2 + zext_ln17_31_fu_56279_p1);

assign add_ln58_119_fu_57950_p2 = (zext_ln58_12_fu_57947_p1 + mult_74_fu_57119_p2);

assign add_ln58_120_fu_57960_p2 = (mult_89_fu_57209_p2 + zext_ln17_39_fu_57295_p1);

assign add_ln58_121_fu_57970_p2 = (mult_100_fu_57430_p2 + 23'd32768);

assign add_ln58_122_fu_57976_p2 = (add_ln58_121_fu_57970_p2 + zext_ln58_13_fu_57966_p1);

assign add_ln58_123_fu_57986_p2 = ($signed(sext_ln58_57_fu_57982_p1) + $signed(sext_ln58_56_fu_57956_p1));

assign add_ln58_124_fu_57996_p2 = ($signed(sext_ln58_58_fu_57992_p1) + $signed(sext_ln58_55_fu_57943_p1));

assign add_ln58_125_fu_58046_p2 = (sub_ln58_6_fu_58040_p2 + zext_ln17_11_fu_56613_p1);

assign add_ln58_126_fu_58052_p2 = (tmp37_fu_58032_p3 + 19'd2048);

assign add_ln58_127_fu_58062_p2 = (zext_ln58_14_fu_58058_p1 + zext_ln17_40_fu_57436_p1);

assign add_ln58_128_fu_58072_p2 = (zext_ln58_15_fu_58068_p1 + add_ln58_125_fu_58046_p2);

assign add_ln58_129_fu_58078_p2 = ($signed(sext_ln17_28_fu_56634_p1) + $signed(zext_ln42_52_fu_56685_p1));

assign add_ln58_130_fu_58088_p2 = ($signed(sext_ln58_59_fu_58084_p1) + $signed(sext_ln17_fu_56549_p1));

assign add_ln58_131_fu_58094_p2 = (zext_ln17_18_fu_56808_p1 + sub_ln17_4_fu_56914_p2);

assign add_ln58_132_fu_58100_p2 = (mul_ln17_reg_39001 + mult_64_fu_57049_p2);

assign add_ln58_133_fu_58110_p2 = ($signed(sext_ln58_60_fu_58106_p1) + $signed(add_ln58_131_fu_58094_p2));

assign add_ln58_134_fu_58120_p2 = ($signed(sext_ln58_61_fu_58116_p1) + $signed(add_ln58_130_fu_58088_p2));

assign add_ln58_135_fu_56443_p2 = ($signed(sext_ln17_35_fu_56123_p1) + $signed(mult_75_fu_445_p2));

assign add_ln58_136_fu_56449_p2 = (zext_ln42_50_fu_56228_p1 + data_55_val);

assign add_ln58_137_fu_56477_p2 = ($signed(sext_ln58_62_fu_56473_p1) + $signed(add_ln58_135_fu_56443_p2));

assign add_ln58_138_fu_58129_p2 = ($signed(zext_ln17_36_fu_57215_p1) + $signed(sext_ln17_41_fu_57308_p1));

assign add_ln58_139_fu_58145_p2 = ($signed(sext_ln58_64_fu_58141_p1) + $signed(add_ln58_138_fu_58129_p2));

assign add_ln58_140_fu_58155_p2 = ($signed(sext_ln58_65_fu_58151_p1) + $signed(sext_ln58_63_fu_58126_p1));

assign add_ln58_141_fu_58165_p2 = ($signed(sext_ln58_66_fu_58161_p1) + $signed(add_ln58_134_fu_58120_p2));

assign add_ln58_142_fu_58171_p2 = (mult_fu_56532_p2 + zext_ln17_16_fu_56730_p1);

assign add_ln58_143_fu_58177_p2 = (zext_ln17_24_fu_56930_p1 + mul_ln17_1_reg_39005);

assign add_ln58_144_fu_58197_p2 = ($signed(sext_ln58_67_fu_58193_p1) + $signed(add_ln58_142_fu_58171_p2));

assign add_ln58_145_fu_56483_p2 = (mult_80_fu_56220_p3 + zext_ln17_32_fu_56293_p1);

assign add_ln58_146_fu_56493_p2 = (zext_ln58_18_fu_56489_p1 + mult_76_fu_1022_p2);

assign add_ln58_147_fu_58210_p2 = (mult_102_fu_57440_p2 + 24'd4096);

assign add_ln58_148_fu_58216_p2 = (add_ln58_147_fu_58210_p2 + zext_ln17_37_fu_57229_p1);

assign add_ln58_149_fu_58222_p2 = ($signed(add_ln58_148_fu_58216_p2) + $signed(sext_ln58_69_fu_58207_p1));

assign add_ln58_150_fu_58232_p2 = ($signed(sext_ln58_70_fu_58228_p1) + $signed(sext_ln58_68_fu_58203_p1));

assign add_ln58_67_fu_57456_p2 = ($signed(sext_ln58_fu_57452_p1) + $signed(mult_fu_56532_p2));

assign add_ln58_68_fu_57466_p2 = ($signed(sext_ln17_29_fu_56738_p1) + $signed(sext_ln17_30_fu_56840_p1));

assign add_ln58_69_fu_57472_p2 = (sub_ln17_6_fu_56959_p2 + zext_ln17_26_fu_57015_p1);

assign add_ln58_70_fu_57482_p2 = ($signed(sext_ln58_31_fu_57478_p1) + $signed(add_ln58_68_fu_57466_p2));

assign add_ln58_71_fu_57492_p2 = ($signed(sext_ln58_32_fu_57488_p1) + $signed(sext_ln58_30_fu_57462_p1));

assign add_ln58_72_fu_56345_p2 = ($signed(sext_ln17_32_fu_56079_p1) + $signed(sext_ln17_36_fu_56155_p1));

assign add_ln58_73_fu_56351_p2 = (zext_ln17_29_fu_56194_p1 + mult_81_fu_706_p2);

assign add_ln58_74_fu_56361_p2 = ($signed(sext_ln58_33_fu_56357_p1) + $signed(add_ln58_72_fu_56345_p2));

assign add_ln58_75_fu_57501_p2 = ($signed(zext_ln17_33_fu_57183_p1) + $signed(sext_ln17_40_fu_57270_p1));

assign add_ln58_76_fu_57511_p2 = (mult_96_fu_57340_p2 + 23'd2048);

assign add_ln58_77_fu_57517_p2 = ($signed(add_ln58_76_fu_57511_p2) + $signed(sext_ln58_35_fu_57507_p1));

assign add_ln58_78_fu_57523_p2 = ($signed(add_ln58_77_fu_57517_p2) + $signed(sext_ln58_34_fu_57498_p1));

assign add_ln58_79_fu_57533_p2 = ($signed(sext_ln58_36_fu_57529_p1) + $signed(add_ln58_71_fu_57492_p2));

assign add_ln58_80_fu_57580_p2 = (zext_ln17_13_fu_56674_p1 + mult_54_fu_56770_p2);

assign add_ln58_81_fu_57590_p2 = (mult_60_fu_56982_p2 + mult_62_fu_57034_p2);

assign add_ln58_82_fu_57600_p2 = ($signed(sext_ln58_38_fu_57596_p1) + $signed(sub_ln17_1_fu_56872_p2));

assign add_ln58_83_fu_57610_p2 = ($signed(sext_ln58_39_fu_57606_p1) + $signed(sext_ln58_37_fu_57586_p1));

assign add_ln58_84_fu_57620_p2 = (zext_ln58_fu_57577_p1 + zext_ln42_56_fu_57152_p1);

assign add_ln58_85_fu_57648_p2 = ($signed(sext_ln58_41_fu_57644_p1) + $signed(sext_ln17_37_fu_57093_p1));

assign add_ln58_86_fu_57658_p2 = (tmp20_fu_57571_p2 + 23'd16384);

assign add_ln58_87_fu_57668_p2 = ($signed(sext_ln58_43_fu_57664_p1) + $signed(sext_ln17_42_fu_57356_p1));

assign add_ln58_88_fu_57674_p2 = ($signed(add_ln58_87_fu_57668_p2) + $signed(sext_ln58_42_fu_57654_p1));

assign add_ln58_89_fu_57680_p2 = ($signed(add_ln58_88_fu_57674_p2) + $signed(sext_ln58_40_fu_57616_p1));

assign add_ln58_90_fu_57686_p2 = ($signed(sext_ln17_27_fu_56574_p1) + $signed(zext_ln17_14_fu_56699_p1));

assign add_ln58_91_fu_57692_p2 = (add_ln58_90_fu_57686_p2 + zext_ln17_fu_56545_p1);

assign add_ln58_92_fu_57698_p2 = (mul_ln17_reg_39001 + mult_63_fu_57040_p2);

assign add_ln58_93_fu_57708_p2 = ($signed(sext_ln58_44_fu_57704_p1) + $signed(mult_58_fu_56888_p2));

assign add_ln58_94_fu_57718_p2 = ($signed(sext_ln58_45_fu_57714_p1) + $signed(add_ln58_91_fu_57692_p2));

assign add_ln58_95_fu_56373_p2 = ($signed(zext_ln42_75_fu_56145_p1) + $signed(sext_ln17_38_fu_56198_p1));

assign add_ln58_96_fu_56379_p2 = ($signed(add_ln58_95_fu_56373_p2) + $signed(sext_ln17_33_fu_56101_p1));

assign add_ln58_97_fu_57731_p2 = ($signed(sext_ln17_39_fu_57145_p1) + $signed(zext_ln17_34_fu_57187_p1));

assign add_ln58_98_fu_57741_p2 = (mult_98_fu_57375_p2 + 24'd1536);

assign add_ln58_99_fu_57747_p2 = ($signed(add_ln58_98_fu_57741_p2) + $signed(sext_ln58_48_fu_57737_p1));

assign add_ln58_fu_57446_p2 = ($signed(sext_ln17_26_fu_56570_p1) + $signed(zext_ln17_12_fu_56670_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = {{add_ln58_79_fu_57533_p2[24:10]}};

assign ap_return_1 = sext_ln111_fu_58258_p1;

assign ap_return_2 = {{add_ln58_101_fu_57763_p2[24:10]}};

assign ap_return_3 = {{add_ln58_111_fu_57857_p2[24:10]}};

assign ap_return_4 = {{add_ln58_124_fu_57996_p2[24:10]}};

assign ap_return_5 = sext_ln111_8_fu_58302_p1;

assign ap_return_6 = {{add_ln58_141_fu_58165_p2[24:10]}};

assign ap_return_7 = {{add_ln58_150_fu_58232_p2[24:10]}};

assign data_46_val_cast55_fu_58020_p1 = data_46_val_read_reg_58425;

assign data_62_val_cast54_fu_58023_p1 = data_62_val_read_reg_58384;

assign mul_ln17_1_fu_401_p0 = mul_ln17_1_fu_401_p00;

assign mul_ln17_1_fu_401_p00 = data_47_val;

assign mul_ln17_1_fu_401_p1 = 17'd600;

assign mul_ln17_fu_871_p0 = mul_ln17_fu_871_p00;

assign mul_ln17_fu_871_p00 = data_46_val;

assign mul_ln17_fu_871_p1 = 18'd261440;

assign mult_100_fu_57430_p2 = (zext_ln42_103_fu_57426_p1 - zext_ln42_102_fu_57415_p1);

assign mult_101_fu_57312_p3 = {{data_63_val_read_reg_58374}, {9'd0}};

assign mult_102_fu_57440_p2 = (sub_ln42_38_fu_57392_p2 - zext_ln42_99_fu_57371_p1);

assign mult_38_fu_56538_p3 = {{data_14_val_read_reg_58470}, {9'd0}};

assign mult_39_fu_316_p0 = mult_39_fu_316_p00;

assign mult_39_fu_316_p00 = data_14_val_read_reg_58470;

assign mult_39_fu_316_p1 = 25'd33551936;

assign mult_40_fu_483_p0 = mult_40_fu_483_p00;

assign mult_40_fu_483_p00 = data_14_val_read_reg_58470;

assign mult_40_fu_483_p1 = 24'd16775360;

assign mult_41_fu_56564_p2 = (21'd0 - zext_ln42_37_fu_56560_p1);

assign mult_42_fu_618_p0 = mult_42_fu_618_p00;

assign mult_42_fu_618_p00 = data_23_val;

assign mult_42_fu_618_p1 = 20'd1047744;

assign mult_43_fu_56596_p2 = (p_shl9_fu_56578_p3 - zext_ln42_40_fu_56592_p1);

assign mult_44_fu_56606_p3 = {{data_23_val_read_reg_58461}, {10'd0}};

assign mult_45_fu_56628_p2 = (22'd0 - zext_ln42_45_fu_56624_p1);

assign mult_46_fu_56664_p2 = (zext_ln42_46_fu_56649_p1 + zext_ln42_49_fu_56660_p1);

assign mult_47_fu_56653_p3 = {{data_30_val_read_reg_58452}, {7'd0}};

assign mult_48_fu_56693_p2 = (zext_ln42_52_fu_56685_p1 + zext_ln42_53_fu_56689_p1);

assign mult_49_fu_800_p0 = mult_49_fu_800_p00;

assign mult_49_fu_800_p00 = data_30_val_read_reg_58452;

assign mult_49_fu_800_p1 = 22'd1248;

assign mult_50_fu_56718_p2 = (zext_ln42_46_fu_56649_p1 + zext_ln42_58_fu_56714_p1);

assign mult_51_fu_56678_p3 = {{data_30_val_read_reg_58452}, {11'd0}};

assign mult_52_fu_56724_p2 = (mult_51_fu_56678_p3 - zext_ln42_49_fu_56660_p1);

assign mult_53_fu_856_p0 = mult_53_fu_856_p00;

assign mult_53_fu_856_p00 = data_32_val_read_reg_58443;

assign mult_53_fu_856_p1 = 21'd2095552;

assign mult_54_fu_56770_p2 = (sub_ln42_fu_56753_p2 - zext_ln42_61_fu_56766_p1);

assign mult_55_fu_56798_p2 = (zext_ln42_62_fu_56783_p1 + zext_ln42_63_fu_56794_p1);

assign mult_56_fu_56742_p3 = {{data_32_val_read_reg_58443}, {9'd0}};

assign mult_57_fu_56834_p2 = (zext_ln42_65_fu_56830_p1 - zext_ln42_64_fu_56819_p1);

assign mult_58_fu_56888_p2 = (sub_ln42_10_fu_56882_p2 - zext_ln17_20_fu_56868_p1);

assign mult_59_fu_56923_p3 = {{data_46_val_read_reg_58425}, {8'd0}};

assign mult_60_fu_56982_p2 = (sub_ln42_12_fu_56965_p2 - zext_ln42_67_fu_56978_p1);

assign mult_61_fu_57009_p2 = (p_shl10_fu_56991_p3 - zext_ln42_68_fu_57005_p1);

assign mult_62_fu_57034_p2 = (zext_ln42_70_fu_57030_p1 - zext_ln42_69_fu_57019_p1);

assign mult_63_fu_57040_p2 = (sub_ln42_16_reg_58480 - zext_ln42_70_fu_57030_p1);

assign mult_64_fu_57049_p2 = (zext_ln42_69_fu_57019_p1 + zext_ln42_72_fu_57045_p1);

assign mult_65_fu_57059_p2 = (18'd0 - zext_ln42_69_fu_57019_p1);

assign mult_66_fu_960_p0 = zext_ln42_41_fu_56073_p1;

assign mult_66_fu_960_p1 = 20'd1047744;

assign mult_67_fu_56095_p2 = (17'd0 - zext_ln42_73_fu_56091_p1);

assign mult_68_fu_508_p0 = zext_ln42_41_fu_56073_p1;

assign mult_68_fu_508_p1 = 20'd1047776;

assign mult_69_fu_56117_p2 = (20'd0 - zext_ln42_74_fu_56113_p1);

assign mult_70_fu_56149_p2 = (20'd0 - zext_ln42_75_fu_56145_p1);

assign mult_71_fu_57087_p2 = (21'd0 - zext_ln42_76_fu_57083_p1);

assign mult_72_fu_56137_p3 = {{data_54_val}, {8'd0}};

assign mult_73_fu_968_p0 = zext_ln42_44_reg_58485;

assign mult_73_fu_968_p1 = 23'd8387200;

assign mult_74_fu_57119_p2 = (zext_ln42_78_fu_57115_p1 - zext_ln42_77_fu_57104_p1);

assign mult_75_fu_445_p0 = mult_75_fu_445_p00;

assign mult_75_fu_445_p00 = data_54_val;

assign mult_75_fu_445_p1 = 22'd4193472;

assign mult_76_fu_1022_p0 = mult_76_fu_1022_p00;

assign mult_76_fu_1022_p00 = data_54_val;

assign mult_76_fu_1022_p1 = 23'd8387224;

assign mult_77_fu_56188_p2 = (p_shl11_fu_56168_p3 - zext_ln42_79_fu_56184_p1);

assign mult_78_fu_552_p0 = mult_78_fu_552_p00;

assign mult_78_fu_552_p00 = data_55_val;

assign mult_78_fu_552_p1 = 19'd523872;

assign mult_79_fu_56214_p2 = (p_shl12_fu_56202_p3 - zext_ln42_80_fu_56210_p1);

assign mult_80_fu_56220_p3 = {{data_55_val}, {9'd0}};

assign mult_81_fu_706_p0 = mult_81_fu_706_p00;

assign mult_81_fu_706_p00 = data_57_val;

assign mult_81_fu_706_p1 = 18'd261680;

assign mult_82_fu_57139_p2 = (16'd0 - zext_ln42_81_fu_57135_p1);

assign mult_83_fu_56261_p2 = (zext_ln42_82_fu_56245_p1 + zext_ln42_83_fu_56257_p1);

assign mult_84_fu_56271_p3 = {{data_57_val}, {9'd0}};

assign mult_85_fu_56287_p2 = (tmp_137_fu_56237_p3 - zext_ln42_84_fu_56283_p1);

assign mult_86_fu_57177_p2 = (zext_ln42_85_fu_57162_p1 + zext_ln42_86_fu_57173_p1);

assign mult_87_fu_1066_p0 = zext_ln42_57_fu_56297_p1;

assign mult_87_fu_1066_p1 = 21'd1664;

assign mult_88_fu_56303_p3 = {{data_58_val}, {10'd0}};

assign mult_89_fu_57209_p2 = (p_shl13_fu_57191_p3 - zext_ln42_87_fu_57205_p1);

assign mult_90_fu_614_p0 = zext_ln42_57_fu_56297_p1;

assign mult_90_fu_614_p1 = 21'd1504;

assign mult_91_fu_57223_p2 = (p_shl13_fu_57191_p3 - zext_ln42_88_fu_57219_p1);

assign mult_92_fu_57264_p2 = (sub_ln42_30_fu_57247_p2 - zext_ln42_90_fu_57260_p1);

assign mult_93_fu_57285_p2 = (tmp_142_fu_57236_p3 - zext_ln42_91_fu_57281_p1);

assign mult_94_fu_56339_p2 = (zext_ln42_92_fu_56323_p1 + zext_ln42_93_fu_56335_p1);

assign mult_95_fu_57302_p2 = (18'd0 - zext_ln42_94_fu_57298_p1);

assign mult_96_fu_57340_p2 = (sub_ln42_34_fu_57323_p2 - zext_ln42_96_fu_57336_p1);

assign mult_97_fu_57350_p2 = (20'd0 - zext_ln42_97_fu_57346_p1);

assign mult_98_fu_57375_p2 = (zext_ln42_99_fu_57371_p1 - zext_ln42_98_fu_57367_p1);

assign mult_99_fu_57409_p2 = (sub_ln42_38_fu_57392_p2 - zext_ln42_101_fu_57405_p1);

assign mult_fu_56532_p2 = (zext_ln42_34_fu_56528_p1 - zext_ln42_33_fu_56517_p1);

assign p_shl10_fu_56991_p3 = {{data_47_val_read_reg_58417}, {9'd0}};

assign p_shl11_fu_56168_p3 = {{data_55_val}, {8'd0}};

assign p_shl12_fu_56202_p3 = {{data_55_val}, {10'd0}};

assign p_shl13_fu_57191_p3 = {{data_58_val_read_reg_58393}, {11'd0}};

assign p_shl14_fu_57551_p3 = {{tmp19_fu_57545_p2}, {10'd0}};

assign p_shl15_fu_57774_p3 = {{tmp27_fu_57769_p2}, {8'd0}};

assign p_shl16_fu_57869_p3 = {{tmp32_fu_57863_p2}, {10'd0}};

assign p_shl25_fu_58016_p1 = tmp_159_fu_58008_p3;

assign p_shl28_fu_56399_p1 = tmp_156_fu_56391_p3;

assign p_shl29_fu_56411_p1 = tmp_157_fu_56403_p3;

assign p_shl31_fu_57790_p1 = tmp_155_fu_57782_p3;

assign p_shl34_fu_57567_p1 = tmp_153_fu_57559_p3;

assign p_shl9_fu_56578_p3 = {{data_23_val_read_reg_58461}, {9'd0}};

assign sext_ln111_8_fu_58302_p1 = $signed(trunc_ln111_4_fu_58292_p4);

assign sext_ln111_fu_58258_p1 = $signed(trunc_ln111_s_fu_58248_p4);

assign sext_ln17_26_fu_56570_p1 = $signed(mult_41_fu_56564_p2);

assign sext_ln17_27_fu_56574_p1 = $signed(mult_42_reg_38997);

assign sext_ln17_28_fu_56634_p1 = $signed(mult_45_fu_56628_p2);

assign sext_ln17_29_fu_56738_p1 = $signed(mult_53_fu_856_p2);

assign sext_ln17_30_fu_56840_p1 = $signed(mult_57_fu_56834_p2);

assign sext_ln17_31_fu_57065_p1 = $signed(mult_65_fu_57059_p2);

assign sext_ln17_32_fu_56079_p1 = $signed(mult_66_fu_960_p2);

assign sext_ln17_33_fu_56101_p1 = $signed(mult_67_fu_56095_p2);

assign sext_ln17_34_fu_57069_p1 = $signed(mult_68_reg_39012);

assign sext_ln17_35_fu_56123_p1 = $signed(mult_69_fu_56117_p2);

assign sext_ln17_36_fu_56155_p1 = $signed(mult_70_fu_56149_p2);

assign sext_ln17_37_fu_57093_p1 = $signed(mult_71_fu_57087_p2);

assign sext_ln17_38_fu_56198_p1 = $signed(mult_78_fu_552_p2);

assign sext_ln17_39_fu_57145_p1 = $signed(mult_82_fu_57139_p2);

assign sext_ln17_40_fu_57270_p1 = $signed(mult_92_fu_57264_p2);

assign sext_ln17_41_fu_57308_p1 = $signed(mult_95_fu_57302_p2);

assign sext_ln17_42_fu_57356_p1 = $signed(mult_97_fu_57350_p2);

assign sext_ln17_fu_56549_p1 = $signed(mult_40_fu_483_p2);

assign sext_ln58_30_fu_57462_p1 = $signed(add_ln58_67_fu_57456_p2);

assign sext_ln58_31_fu_57478_p1 = $signed(add_ln58_69_fu_57472_p2);

assign sext_ln58_32_fu_57488_p1 = $signed(add_ln58_70_fu_57482_p2);

assign sext_ln58_33_fu_56357_p1 = $signed(add_ln58_73_fu_56351_p2);

assign sext_ln58_34_fu_57498_p1 = $signed(add_ln58_74_reg_58495);

assign sext_ln58_35_fu_57507_p1 = $signed(add_ln58_75_fu_57501_p2);

assign sext_ln58_36_fu_57529_p1 = $signed(add_ln58_78_fu_57523_p2);

assign sext_ln58_37_fu_57586_p1 = $signed(add_ln58_80_fu_57580_p2);

assign sext_ln58_38_fu_57596_p1 = $signed(add_ln58_81_fu_57590_p2);

assign sext_ln58_39_fu_57606_p1 = $signed(add_ln58_82_fu_57600_p2);

assign sext_ln58_40_fu_57616_p1 = $signed(add_ln58_83_fu_57610_p2);

assign sext_ln58_41_fu_57644_p1 = $signed(sub_ln58_fu_57638_p2);

assign sext_ln58_42_fu_57654_p1 = $signed(add_ln58_85_fu_57648_p2);

assign sext_ln58_43_fu_57664_p1 = $signed(add_ln58_86_fu_57658_p2);

assign sext_ln58_44_fu_57704_p1 = $signed(add_ln58_92_fu_57698_p2);

assign sext_ln58_45_fu_57714_p1 = $signed(add_ln58_93_fu_57708_p2);

assign sext_ln58_46_fu_57724_p1 = $signed(add_ln58_94_fu_57718_p2);

assign sext_ln58_47_fu_57728_p1 = $signed(add_ln58_96_reg_58505);

assign sext_ln58_48_fu_57737_p1 = $signed(add_ln58_97_fu_57731_p2);

assign sext_ln58_49_fu_57759_p1 = $signed(add_ln58_100_fu_57753_p2);

assign sext_ln58_50_fu_57822_p1 = $signed(add_ln58_104_fu_57816_p2);

assign sext_ln58_51_fu_57853_p1 = $signed(add_ln58_110_fu_57847_p2);

assign sext_ln58_52_fu_57885_p1 = $signed(tmp_158_fu_57877_p3);

assign sext_ln58_53_fu_57917_p1 = $signed(add_ln58_114_fu_57911_p2);

assign sext_ln58_54_fu_57927_p1 = $signed(add_ln58_115_fu_57921_p2);

assign sext_ln58_55_fu_57943_p1 = $signed(add_ln58_117_fu_57937_p2);

assign sext_ln58_56_fu_57956_p1 = $signed(add_ln58_119_fu_57950_p2);

assign sext_ln58_57_fu_57982_p1 = $signed(add_ln58_122_fu_57976_p2);

assign sext_ln58_58_fu_57992_p1 = $signed(add_ln58_123_fu_57986_p2);

assign sext_ln58_59_fu_58084_p1 = $signed(add_ln58_129_fu_58078_p2);

assign sext_ln58_60_fu_58106_p1 = $signed(add_ln58_132_fu_58100_p2);

assign sext_ln58_61_fu_58116_p1 = $signed(add_ln58_133_fu_58110_p2);

assign sext_ln58_62_fu_56473_p1 = $signed(sub_ln58_7_fu_56467_p2);

assign sext_ln58_63_fu_58126_p1 = $signed(add_ln58_137_reg_58520);

assign sext_ln58_64_fu_58141_p1 = $signed(sub_ln58_8_fu_58135_p2);

assign sext_ln58_65_fu_58151_p1 = $signed(add_ln58_139_fu_58145_p2);

assign sext_ln58_66_fu_58161_p1 = $signed(add_ln58_140_fu_58155_p2);

assign sext_ln58_67_fu_58193_p1 = $signed(sub_ln58_9_fu_58187_p2);

assign sext_ln58_68_fu_58203_p1 = $signed(add_ln58_144_fu_58197_p2);

assign sext_ln58_69_fu_58207_p1 = $signed(add_ln58_146_reg_58525);

assign sext_ln58_70_fu_58228_p1 = $signed(add_ln58_149_fu_58222_p2);

assign sext_ln58_fu_57452_p1 = $signed(add_ln58_fu_57446_p2);

assign sub_ln17_1_fu_56872_p2 = (sub_ln17_fu_56855_p2 - zext_ln17_20_fu_56868_p1);

assign sub_ln17_2_fu_56898_p2 = (zext_ln17_21_fu_56894_p1 - tmp_121_fu_56823_p3);

assign sub_ln17_3_fu_56904_p2 = (21'd0 - zext_ln42_64_fu_56819_p1);

assign sub_ln17_4_fu_56914_p2 = (sub_ln17_3_fu_56904_p2 - zext_ln17_23_fu_56910_p1);

assign sub_ln17_5_fu_56949_p2 = (19'd0 - zext_ln17_28_fu_56945_p1);

assign sub_ln17_6_fu_56959_p2 = (sub_ln17_5_fu_56949_p2 - zext_ln17_41_fu_56955_p1);

assign sub_ln17_fu_56855_p2 = (20'd0 - zext_ln17_19_fu_56851_p1);

assign sub_ln42_10_fu_56882_p2 = (20'd0 - zext_ln42_66_fu_56878_p1);

assign sub_ln42_12_fu_56965_p2 = (18'd0 - zext_ln17_25_fu_56934_p1);

assign sub_ln42_16_fu_56063_p2 = (18'd0 - zext_ln42_71_fu_56059_p1);

assign sub_ln42_30_fu_57247_p2 = (19'd0 - zext_ln42_89_fu_57243_p1);

assign sub_ln42_34_fu_57323_p2 = (23'd0 - zext_ln42_95_fu_57319_p1);

assign sub_ln42_38_fu_57392_p2 = (24'd0 - zext_ln42_100_fu_57388_p1);

assign sub_ln42_fu_56753_p2 = (20'd0 - zext_ln42_60_fu_56749_p1);

assign sub_ln58_5_fu_57889_p2 = ($signed(p_shl16_fu_57869_p3) - $signed(sext_ln58_52_fu_57885_p1));

assign sub_ln58_6_fu_58040_p2 = ($signed(sext_ln17_31_fu_57065_p1) - $signed(p_shl25_fu_58016_p1));

assign sub_ln58_7_fu_56467_p2 = (18'd0 - zext_ln58_16_fu_56463_p1);

assign sub_ln58_8_fu_58135_p2 = (20'd4096 - zext_ln42_97_fu_57346_p1);

assign sub_ln58_9_fu_58187_p2 = (zext_ln58_17_fu_58183_p1 - tmp_121_fu_56823_p3);

assign sub_ln58_fu_57638_p2 = (18'd0 - zext_ln58_8_fu_57634_p1);

assign tmp13_fu_57539_p2 = (zext_ln42_fu_56503_p1 + zext_ln42_59_fu_57233_p1);

assign tmp19_fu_57545_p2 = (tmp13_fu_57539_p2 + zext_ln42_51_fu_57125_p1);

assign tmp20_fu_57571_p2 = (p_shl34_fu_57567_p1 - p_shl14_fu_57551_p3);

assign tmp21_fu_56367_p2 = (zext_ln42_47_fu_56159_p1 + zext_ln42_39_fu_56069_p1);

assign tmp27_fu_57769_p2 = (zext_ln42_35_fu_56920_p1 + data_41_val_read_reg_58434);

assign tmp28_cast_fu_57800_p1 = tmp28_fu_57794_p2;

assign tmp28_fu_57794_p2 = (p_shl15_fu_57774_p3 - p_shl31_fu_57790_p1);

assign tmp29_fu_56385_p2 = (zext_ln42_47_fu_56159_p1 + zext_ln42_23_fu_56032_p1);

assign tmp30_fu_56415_p2 = (p_shl28_fu_56399_p1 + p_shl29_fu_56411_p1);

assign tmp32_fu_57863_p2 = (zext_ln42_36_fu_56988_p1 - zext_ln42_fu_56503_p1);

assign tmp34_fu_58002_p2 = (zext_ln42_55_fu_57149_p1 + zext_ln42_42_fu_57073_p1);

assign tmp3634_fu_58026_p2 = (data_62_val_cast54_fu_58023_p1 + data_46_val_cast55_fu_58020_p1);

assign tmp37_fu_58032_p3 = {{tmp3634_fu_58026_p2}, {10'd0}};

assign tmp_108_fu_56521_p3 = {{data_14_val_read_reg_58470}, {8'd0}};

assign tmp_109_fu_56553_p3 = {{data_23_val_read_reg_58461}, {11'd0}};

assign tmp_110_fu_56585_p3 = {{data_23_val_read_reg_58461}, {7'd0}};

assign tmp_111_fu_56617_p3 = {{data_23_val_read_reg_58461}, {12'd0}};

assign tmp_112_fu_56642_p3 = {{data_30_val_read_reg_58452}, {10'd0}};

assign tmp_115_fu_56707_p3 = {{data_30_val_read_reg_58452}, {8'd0}};

assign tmp_117_fu_56759_p3 = {{data_32_val_read_reg_58443}, {7'd0}};

assign tmp_118_fu_56776_p3 = {{data_32_val_read_reg_58443}, {8'd0}};

assign tmp_119_fu_56787_p3 = {{data_32_val_read_reg_58443}, {6'd0}};

assign tmp_120_fu_56812_p3 = {{data_41_val_read_reg_58434}, {10'd0}};

assign tmp_121_fu_56823_p3 = {{data_41_val_read_reg_58434}, {8'd0}};

assign tmp_122_fu_56844_p3 = {{data_41_val_read_reg_58434}, {9'd0}};

assign tmp_123_fu_56861_p3 = {{data_41_val_read_reg_58434}, {6'd0}};

assign tmp_124_fu_56938_p3 = {{data_46_val_read_reg_58425}, {10'd0}};

assign tmp_125_fu_56971_p3 = {{data_46_val_read_reg_58425}, {5'd0}};

assign tmp_126_fu_56998_p3 = {{data_47_val_read_reg_58417}, {7'd0}};

assign tmp_127_fu_57023_p3 = {{data_47_val_read_reg_58417}, {6'd0}};

assign tmp_128_fu_56051_p3 = {{data_47_val}, {8'd0}};

assign tmp_129_fu_56083_p3 = {{data_52_val}, {7'd0}};

assign tmp_130_fu_56105_p3 = {{data_52_val}, {10'd0}};

assign tmp_132_fu_57076_p3 = {{data_54_val_read_reg_58409}, {9'd0}};

assign tmp_133_fu_57097_p3 = {{data_54_val_read_reg_58409}, {10'd0}};

assign tmp_134_fu_57108_p3 = {{data_54_val_read_reg_58409}, {7'd0}};

assign tmp_135_fu_56176_p3 = {{data_55_val}, {6'd0}};

assign tmp_136_fu_57128_p3 = {{data_57_val_read_reg_58403}, {7'd0}};

assign tmp_137_fu_56237_p3 = {{data_57_val}, {8'd0}};

assign tmp_138_fu_56249_p3 = {{data_57_val}, {6'd0}};

assign tmp_139_fu_57155_p3 = {{data_58_val_read_reg_58393}, {9'd0}};

assign tmp_140_fu_57166_p3 = {{data_58_val_read_reg_58393}, {5'd0}};

assign tmp_141_fu_57198_p3 = {{data_58_val_read_reg_58393}, {8'd0}};

assign tmp_142_fu_57236_p3 = {{data_62_val_read_reg_58384}, {9'd0}};

assign tmp_143_fu_57253_p3 = {{data_62_val_read_reg_58384}, {6'd0}};

assign tmp_144_fu_57274_p3 = {{data_62_val_read_reg_58384}, {7'd0}};

assign tmp_145_fu_56315_p3 = {{data_62_val}, {8'd0}};

assign tmp_146_fu_56327_p3 = {{data_62_val}, {5'd0}};

assign tmp_148_fu_57329_p3 = {{data_63_val_read_reg_58374}, {7'd0}};

assign tmp_149_fu_57360_p3 = {{data_63_val_read_reg_58374}, {11'd0}};

assign tmp_150_fu_57381_p3 = {{data_63_val_read_reg_58374}, {10'd0}};

assign tmp_151_fu_57398_p3 = {{data_63_val_read_reg_58374}, {8'd0}};

assign tmp_152_fu_57419_p3 = {{data_63_val_read_reg_58374}, {5'd0}};

assign tmp_153_fu_57559_p3 = {{tmp19_fu_57545_p2}, {7'd0}};

assign tmp_154_fu_57626_p3 = {{add_ln58_84_fu_57620_p2}, {6'd0}};

assign tmp_155_fu_57782_p3 = {{tmp27_fu_57769_p2}, {5'd0}};

assign tmp_156_fu_56391_p3 = {{tmp29_fu_56385_p2}, {9'd0}};

assign tmp_157_fu_56403_p3 = {{tmp29_fu_56385_p2}, {7'd0}};

assign tmp_158_fu_57877_p3 = {{tmp32_fu_57863_p2}, {6'd0}};

assign tmp_159_fu_58008_p3 = {{tmp34_fu_58002_p2}, {11'd0}};

assign tmp_160_fu_56455_p3 = {{add_ln58_136_fu_56449_p2}, {8'd0}};

assign tmp_fu_56510_p3 = {{data_14_val_read_reg_58470}, {11'd0}};

assign trunc_ln111_4_fu_58292_p4 = {{add_ln58_128_fu_58072_p2[23:10]}};

assign trunc_ln111_s_fu_58248_p4 = {{add_ln58_89_fu_57680_p2[23:10]}};

assign zext_ln17_10_fu_56602_p1 = mult_43_fu_56596_p2;

assign zext_ln17_11_fu_56613_p1 = mult_44_fu_56606_p3;

assign zext_ln17_12_fu_56670_p1 = mult_46_fu_56664_p2;

assign zext_ln17_13_fu_56674_p1 = mult_47_fu_56653_p3;

assign zext_ln17_14_fu_56699_p1 = mult_48_fu_56693_p2;

assign zext_ln17_15_fu_56703_p1 = mult_49_fu_800_p2;

assign zext_ln17_16_fu_56730_p1 = mult_52_fu_56724_p2;

assign zext_ln17_17_fu_56804_p1 = mult_55_fu_56798_p2;

assign zext_ln17_18_fu_56808_p1 = mult_56_fu_56742_p3;

assign zext_ln17_19_fu_56851_p1 = tmp_122_fu_56844_p3;

assign zext_ln17_20_fu_56868_p1 = tmp_123_fu_56861_p3;

assign zext_ln17_21_fu_56894_p1 = tmp_123_fu_56861_p3;

assign zext_ln17_23_fu_56910_p1 = tmp_123_fu_56861_p3;

assign zext_ln17_24_fu_56930_p1 = mult_59_fu_56923_p3;

assign zext_ln17_25_fu_56934_p1 = mult_59_fu_56923_p3;

assign zext_ln17_26_fu_57015_p1 = mult_61_fu_57009_p2;

assign zext_ln17_27_fu_57055_p1 = mult_64_fu_57049_p2;

assign zext_ln17_28_fu_56945_p1 = tmp_124_fu_56938_p3;

assign zext_ln17_29_fu_56194_p1 = mult_77_fu_56188_p2;

assign zext_ln17_30_fu_56267_p1 = mult_83_fu_56261_p2;

assign zext_ln17_31_fu_56279_p1 = mult_84_fu_56271_p3;

assign zext_ln17_32_fu_56293_p1 = mult_85_fu_56287_p2;

assign zext_ln17_33_fu_57183_p1 = mult_86_fu_57177_p2;

assign zext_ln17_34_fu_57187_p1 = mult_87_reg_39028;

assign zext_ln17_35_fu_56311_p1 = mult_88_fu_56303_p3;

assign zext_ln17_36_fu_57215_p1 = mult_90_reg_39032;

assign zext_ln17_37_fu_57229_p1 = mult_91_fu_57223_p2;

assign zext_ln17_38_fu_57291_p1 = mult_93_fu_57285_p2;

assign zext_ln17_39_fu_57295_p1 = mult_94_reg_58490;

assign zext_ln17_40_fu_57436_p1 = mult_101_fu_57312_p3;

assign zext_ln17_41_fu_56955_p1 = mult_59_fu_56923_p3;

assign zext_ln17_fu_56545_p1 = mult_38_fu_56538_p3;

assign zext_ln42_100_fu_57388_p1 = tmp_150_fu_57381_p3;

assign zext_ln42_101_fu_57405_p1 = tmp_151_fu_57398_p3;

assign zext_ln42_102_fu_57415_p1 = tmp_150_fu_57381_p3;

assign zext_ln42_103_fu_57426_p1 = tmp_152_fu_57419_p3;

assign zext_ln42_23_fu_56032_p1 = data_23_val;

assign zext_ln42_33_fu_56517_p1 = tmp_fu_56510_p3;

assign zext_ln42_34_fu_56528_p1 = tmp_108_fu_56521_p3;

assign zext_ln42_35_fu_56920_p1 = data_46_val_read_reg_58425;

assign zext_ln42_36_fu_56988_p1 = data_47_val_read_reg_58417;

assign zext_ln42_37_fu_56560_p1 = tmp_109_fu_56553_p3;

assign zext_ln42_39_fu_56069_p1 = data_52_val;

assign zext_ln42_40_fu_56592_p1 = tmp_110_fu_56585_p3;

assign zext_ln42_41_fu_56073_p1 = data_52_val;

assign zext_ln42_42_fu_57073_p1 = data_54_val_read_reg_58409;

assign zext_ln42_44_fu_56132_p1 = data_54_val;

assign zext_ln42_45_fu_56624_p1 = tmp_111_fu_56617_p3;

assign zext_ln42_46_fu_56649_p1 = tmp_112_fu_56642_p3;

assign zext_ln42_47_fu_56159_p1 = data_55_val;

assign zext_ln42_49_fu_56660_p1 = mult_47_fu_56653_p3;

assign zext_ln42_50_fu_56228_p1 = data_57_val;

assign zext_ln42_51_fu_57125_p1 = data_57_val_read_reg_58403;

assign zext_ln42_52_fu_56685_p1 = mult_51_fu_56678_p3;

assign zext_ln42_53_fu_56689_p1 = mult_47_fu_56653_p3;

assign zext_ln42_55_fu_57149_p1 = data_58_val_read_reg_58393;

assign zext_ln42_56_fu_57152_p1 = data_58_val_read_reg_58393;

assign zext_ln42_57_fu_56297_p1 = data_58_val;

assign zext_ln42_58_fu_56714_p1 = tmp_115_fu_56707_p3;

assign zext_ln42_59_fu_57233_p1 = data_62_val_read_reg_58384;

assign zext_ln42_60_fu_56749_p1 = mult_56_fu_56742_p3;

assign zext_ln42_61_fu_56766_p1 = tmp_117_fu_56759_p3;

assign zext_ln42_62_fu_56783_p1 = tmp_118_fu_56776_p3;

assign zext_ln42_63_fu_56794_p1 = tmp_119_fu_56787_p3;

assign zext_ln42_64_fu_56819_p1 = tmp_120_fu_56812_p3;

assign zext_ln42_65_fu_56830_p1 = tmp_121_fu_56823_p3;

assign zext_ln42_66_fu_56878_p1 = tmp_121_fu_56823_p3;

assign zext_ln42_67_fu_56978_p1 = tmp_125_fu_56971_p3;

assign zext_ln42_68_fu_57005_p1 = tmp_126_fu_56998_p3;

assign zext_ln42_69_fu_57019_p1 = p_shl10_fu_56991_p3;

assign zext_ln42_70_fu_57030_p1 = tmp_127_fu_57023_p3;

assign zext_ln42_71_fu_56059_p1 = tmp_128_fu_56051_p3;

assign zext_ln42_72_fu_57045_p1 = tmp_126_fu_56998_p3;

assign zext_ln42_73_fu_56091_p1 = tmp_129_fu_56083_p3;

assign zext_ln42_74_fu_56113_p1 = tmp_130_fu_56105_p3;

assign zext_ln42_75_fu_56145_p1 = mult_72_fu_56137_p3;

assign zext_ln42_76_fu_57083_p1 = tmp_132_fu_57076_p3;

assign zext_ln42_77_fu_57104_p1 = tmp_133_fu_57097_p3;

assign zext_ln42_78_fu_57115_p1 = tmp_134_fu_57108_p3;

assign zext_ln42_79_fu_56184_p1 = tmp_135_fu_56176_p3;

assign zext_ln42_80_fu_56210_p1 = p_shl11_fu_56168_p3;

assign zext_ln42_81_fu_57135_p1 = tmp_136_fu_57128_p3;

assign zext_ln42_82_fu_56245_p1 = tmp_137_fu_56237_p3;

assign zext_ln42_83_fu_56257_p1 = tmp_138_fu_56249_p3;

assign zext_ln42_84_fu_56283_p1 = tmp_138_fu_56249_p3;

assign zext_ln42_85_fu_57162_p1 = tmp_139_fu_57155_p3;

assign zext_ln42_86_fu_57173_p1 = tmp_140_fu_57166_p3;

assign zext_ln42_87_fu_57205_p1 = tmp_141_fu_57198_p3;

assign zext_ln42_88_fu_57219_p1 = tmp_139_fu_57155_p3;

assign zext_ln42_89_fu_57243_p1 = tmp_142_fu_57236_p3;

assign zext_ln42_90_fu_57260_p1 = tmp_143_fu_57253_p3;

assign zext_ln42_91_fu_57281_p1 = tmp_144_fu_57274_p3;

assign zext_ln42_92_fu_56323_p1 = tmp_145_fu_56315_p3;

assign zext_ln42_93_fu_56335_p1 = tmp_146_fu_56327_p3;

assign zext_ln42_94_fu_57298_p1 = tmp_142_fu_57236_p3;

assign zext_ln42_95_fu_57319_p1 = mult_101_fu_57312_p3;

assign zext_ln42_96_fu_57336_p1 = tmp_148_fu_57329_p3;

assign zext_ln42_97_fu_57346_p1 = tmp_148_fu_57329_p3;

assign zext_ln42_98_fu_57367_p1 = tmp_149_fu_57360_p3;

assign zext_ln42_99_fu_57371_p1 = tmp_148_fu_57329_p3;

assign zext_ln42_fu_56503_p1 = data_14_val_read_reg_58470;

assign zext_ln58_10_fu_57832_p1 = add_ln58_107_reg_58510;

assign zext_ln58_11_fu_57907_p1 = add_ln58_113_fu_57901_p2;

assign zext_ln58_12_fu_57947_p1 = add_ln58_118_reg_58515;

assign zext_ln58_13_fu_57966_p1 = add_ln58_120_fu_57960_p2;

assign zext_ln58_14_fu_58058_p1 = add_ln58_126_fu_58052_p2;

assign zext_ln58_15_fu_58068_p1 = add_ln58_127_fu_58062_p2;

assign zext_ln58_16_fu_56463_p1 = tmp_160_fu_56455_p3;

assign zext_ln58_17_fu_58183_p1 = add_ln58_143_fu_58177_p2;

assign zext_ln58_18_fu_56489_p1 = add_ln58_145_fu_56483_p2;

assign zext_ln58_8_fu_57634_p1 = tmp_154_fu_57626_p3;

assign zext_ln58_9_fu_56421_p1 = tmp30_fu_56415_p2;

assign zext_ln58_fu_57577_p1 = tmp21_reg_58500;

always @ (posedge ap_clk) begin
    sub_ln42_16_reg_58480[7:0] <= 8'b00000000;
    zext_ln42_44_reg_58485[22:11] <= 12'b000000000000;
    mult_94_reg_58490[4:0] <= 5'b00000;
    add_ln58_107_reg_58510[5:0] <= 6'b000000;
    add_ln58_118_reg_58515[7:0] <= 8'b00000000;
end

endmodule //myproject_dense_latency_ap_ufixed_12_12_5_3_0_ap_fixed_15_14_5_3_0_config8_s
